tools:
    shell:
        allow:
            - ls *
            - rm *
            - wc *
            - which mdbook
            - mdbook build *
            - echo *
            - cd *
            - zig build
            - head *
            - ./zig-out/bin/duo *
            - ./zig-out/bin/duo dump-c *
            - awk *
            - xargs *
            - zig build *
            - tail *
            - sleep 30
