tools:
    shell:
        allow:
            - ls *
            - rm *
            - wc *
            - which mdbook
            - mdbook build *
            - echo *
            - cd *
            - zig build
            - head *
            - ./zig-out/bin/duo *
            - ./zig-out/bin/duo dump-c *
            - awk *
            - xargs *
            - zig build *
            - tail *
            - sleep 30
            - "true"
            - cat *
            - zig test *
            - grep *
            - file *
            - du *
            - node *
            - ./ext/duo-lsp/duo-lsp
            - sleep 1
            - strings *
            - ./ext/duo-lsp/duo-lsp *
            - pwd
            - sleep *
            - sed *
            - otool *
            - timeout 2 *
            - timeout 1 nc localhost *
            - kill $PID
            - git diff HEAD *
            - git status *
