[language-server.id-lsp]
command = "duo-lsp"

[[language]]
name = "duo"
scope = "source.id"
file-types = ["duo"]
roots = ["build.id"]
comment-token = "--"
injection-regex = "duo"
indent = { tab-width = 4, unit = "    " }
language-servers = ["duo-lsp"]

[[grammar]]
name = "duo"
source = { path = "../tree-sitter-duo" }
