/**
 * @file tree-sitter grammar for Duo — PARTIALLY GENERATED.
 *
 * GENERATED by scripts/treesitter_emit.duo — do not edit the generated
 * regions by hand. Regenerate with:
 *
 *     duo run scripts/treesitter_emit.duo
 *
 * `zig build treesitter-projection` regenerates and FAILS unless the result is
 * byte-identical to the tracked file, so a hand edit to a generated region
 * cannot survive review. A generated file nobody regenerates is an authored
 * file with extra steps.
 *
 * ── THE BOUNDARY, stated rather than banner-washed ──────────────────────────
 *
 * Everything OUTSIDE the @@residue markers below is emitted from registries in
 * the generator. Everything BETWEEN them is AUTHORED — currently
 *
 *     1410 lines
 *
 * and that number is what gaps/GAP-049 is measured by. It must go down.
 *
 * GENERATED, and from what:
 *   name / extras / supertypes    the head registry
 *   literal tokens                the token registry
 *   long_string levels 0..2       ONE template per level; the body
 *                                 alternation that excludes the closing
 *                                 delimiter is computed from the level
 *   double / single quoted string ONE template, two quote characters
 *   binary_expression             one table of spelling, level and
 *   unary_expression              associativity, compared pair by pair
 *                                 against docs/spec/grammar.md §2 with every
 *                                 divergence PRINTED. That comparison is how
 *                                 the inverted precedence table was found.
 *   comment / helpers             the tail registry
 *
 * AUTHORED, and why:
 *   the structural productions    docs/spec/grammar.md §3 states them as EBNF
 *                                 — for the PASS-100 surface. The tracked
 *                                 corpus is still mostly pre-Pass-100, so
 *                                 projecting §3 here would drop editor
 *                                 recognition from 755/775 to near zero. That
 *                                 is a language decision, not a build-system
 *                                 one — see gaps/GAP-049.
 *   the conflicts list            94 LR conflicts, each proven necessary by
 *                                 dropping it and re-running the generator.
 *                                 Knowledge about an LR automaton is not in
 *                                 any grammar document and cannot be.
 *   NEWLINE / INDENT / DEDENT     tree-sitter has no offside layer. It needs
 *                                 an external scanner, which is a C file, and
 *                                 this tree has none — see
 *                                 ext/tree-sitter-duo/src. That hole is why
 *                                 examples/spec100/offside.duo is a single
 *                                 ERROR node from [0,0] to end of file.
 *
 * Still counted as one of three tracked `.js` files by
 * scripts/language_census.duo, which classifies by EXTENSION and therefore
 * cannot see the difference this file makes. Said here so nobody reads the
 * unchanged census row as evidence that nothing happened.
 */

module.exports = grammar({
  name: 'duo',

  extras: $ => [
    /\s/,
    $.comment,
  ],

  supertypes: $ => [
    $.statement,
    $.expression,
    $.type,
    $.pattern,
  ],

  // @@residue:begin — AUTHORED to @@residue:end, carried verbatim; see the banner.
/**
 * @file Tree-sitter grammar for the Duo programming language.
 *
 * Duo is a Lua-like language with optional static typing that compiles to
 * native C and WebAssembly.
 *
 * Based on the lexer tokens from src/lexer.zig and AST from src/ast.zig.
 *
 * ── STATUS: AUTHORED. It is not supposed to be. ──────────────────────────────
 *
 * Pass 100 §19 lists tree-sitter as "a generated grammar projection (output,
 * never authored)". These 106 rules are hand-written, so this file is a live
 * violation of the spec it describes, and it is the largest non-Duo authored
 * source in the repository.
 *
 * It is NOT converted, and not deleted, because the surface it would be
 * generated FROM does not exist: there is no declarative production registry
 * in Duo. `lib/std/compiler/parser.duo` is an imperative recursive-descent
 * parser over a bounded subset (~12 productions), `docs/GRAMMAR_SPEC.md` is
 * prose, and `duo token-tables emit` is lexical only. See gaps/GAP-049 for the
 * three missing pieces and the order they have to land in.
 *
 * The rules below still spell a PRE-PASS-100 surface alongside the Pass 100
 * one — match / enum / try / catch / concept / local / const / function are all
 * still here, and CLAUDE.md §1 denies every one of them by name. They are kept
 * because the CORPUS still uses them (8 statement-initial `match`, 9 `enum`,
 * 59 `concept`, 23 `local`, 348 `fun`), and because `try`/`catch`/`defer`, with
 * no statement uses left, are still assigned token numbers by the GENERATED
 * `lib/std/token/classify.duo`. Dropping a rule here alone desynchronises the
 * front-ends; retiring one is a language decision, not a grammar edit.
 *
 * ONE rule was retired, and only because the corpus said so: `type_definition`
 * (`type X = T`) has ZERO statement-initial uses against 231 for `type(`, and
 * a tree-sitter keyword token beats `identifier` in every state that admits
 * both, so as long as `'type'` was spelled here `type(obj: any): any` could
 * not parse as the declaration it is. `duo check` accepts both spellings; the
 * exclusion was this grammar's lexer, not the language's. See the note at the
 * rule's former site.
 *
 * `macro` is NOT added, and that is a decision rather than an omission. Pass
 * 100 §15 graveyards macro syntax outright, three tracked files use it, and
 * the unquote it needs (`,x` inside a quoted body) would have to live in
 * `expression` — which would make every comma-separated argument list in the
 * other 756 files ambiguous. Three files is not worth that, and the spec is
 * not asking for it.
 *
 * It BUILDS as of 2026-08-08. It did not before: `tree-sitter generate`
 * exited 1 on an unresolved conflict on `return_statement` ('return' • '(' —
 * an argument list versus a bare `return` followed by a parenthesised
 * statement), and the tracked `src/grammar.json` beside this file was NOT a
 * usable fallback: regenerating from that JSON alone fails with the identical
 * conflict, so no editor on this tree had a working parser at all. The repair
 * is `prec.right` on `return_statement` plus the `conflicts:` entries below,
 * each one proven necessary by dropping it and re-running the generator — all
 * 94 of them, re-proved after every change in this pass.
 *
 * What it recognises, MEASURED with `tree-sitter parse --paths` over every
 * tracked `.duo` file, counting a file as recognised only when its tree has no
 * ERROR / MISSING / UNEXPECTED node:
 *
 *   75/748  (10.0 %)  before any of this
 *  702/748  (93.8 %)  after the first pass (nine steps, listed in GAP-049)
 *  705/759  (93.0 %)  the same grammar, re-measured on a corpus grown by 11
 *  711/759  (93.7 %)  + newline as the separator inside `{ … }` — §7 X8
 *  724/759  (95.3 %)  + expression-body lambda and the `()` block form — §5
 *  733/759  (96.5 %)  + binding conditions (§6), value-list tails, `type(x)`
 *  739/759  (97.3 %)  + tuple/applied/attributed types, case sets, `p.@eq`
 *  743/759  (97.8 %)  + `..` spread, levelled long strings, open `match` arms
 *  744/759  (98.0 %)  + unannotated declarations in directive arguments
 *
 * THE ORACLE FOR THIS PASS WAS `duo check`, NOT THE CORPUS. Every construct
 * above was first put to the compiler in isolation, and a rule was added only
 * where the compiler accepts the form. That is what kept three plausible
 * clusters OUT: `(v) return v * 2` is rejected (`expected ')', got 'return'`),
 * so the expression-body lambda takes an expression and nothing else; and `#`
 * and `//` line comments are rejected at LEX time (`UnexpectedChar`), so the
 * two files that use them do not compile and this grammar is right to refuse
 * them. Recognising them would have made the editor accept programs the
 * compiler does not.
 *
 * A file with no ERROR node is not the same as a CORRECT tree, and this count
 * does not claim it is. `require "x"` parsed as two unrelated statements in 95
 * files without ever producing an error node; it is fixed here, and the
 * recognition number could not see either the defect or the repair. The same
 * blindness is still live in one place: THREE OR MORE STACKED BODYLESS
 * DECLARATIONS degrade after the second — `@ffi("a")\nf1(): i64` repeated
 * reads the third onward as loose expression statements. It is tree-sitter's
 * GLR version budget, not a missing rule (the "declaration whose body has not
 * started" reading survives to EOF and one version is spent per declaration),
 * it behaves identically on the pristine `HEAD` grammar, and it is what keeps
 * `lib/std/fs_watch.duo` and `examples/benchmark.duo` unrecognised.
 *
 * `zig build tree-sitter-coverage` is the gate. It runs the generator, fails
 * on a non-zero exit AND on an "unnecessary conflicts" warning, measures the
 * corpus, ratchets on a ceiling of unrecognised files, and positive-controls
 * its own detector on every run.
 *
 * Counted, until then, as one of three tracked `.js` files in the G11 debt
 * line (`scripts/language_census.duo`, ratchet `CENSUS_JS_FLOOR`). Editing
 * this comment does not make the file generated.
 */

  // Duo statements are not separated by a terminator and an expression is a
  // statement, so the LR(1) item set genuinely cannot decide these without
  // lookahead past the conflict point. Each entry below was proven NECESSARY:
  // a script drops one at a time and re-runs `tree-sitter generate`, and all
  // 94 are still required for it to exit 0. See gaps/GAP-049.
  conflicts: $ => [
    // statement head vs expression statement
    [$.struct_definition, $.expression],
    [$.typed_binding, $.call_expression],
    [$.assignment, $.call_expression],
    [$.compound_assignment, $.call_expression],
    [$.local_declaration, $.call_expression],
    [$.const_declaration, $.call_expression],
    [$.global_declaration, $.call_expression],
    [$.return_statement, $.call_expression],
    [$.repeat_loop, $.call_expression],
    [$.expression_statement, $.call_expression],
    // `f "s"` / `f { … }` — the sugar call, or two adjacent expressions. The
    // dynamic precedence on `call_expression` attaches it.
    [$.expression, $.call_expression],
    [$.match_arm, $.expression_statement, $.call_expression],
    // `{ f (x) }` / `{ f "s" }` — with the newline as separator, an element
    // followed by `(`/a string is a CALL or two adjacent elements. Same fork
    // as the statement case, same resolution: `call_expression` carries the
    // dynamic precedence and attaches.
    [$.table_entry, $.call_expression],
    // `{ a\n [k] = v }` — a bracket-keyed entry, or `a[k]` indexed and then
    // assigned. Only what follows the `]` decides.
    [$.table_entry, $.index_expression],
    [$.table_entry, $.expression],
    [$.spread_entry, $.call_expression],
    [$.spread_entry, $.index_expression],
    [$.call_expression, $.parenthesized_expression],
    // GR-001: `f(` is a declaration head or a call, decided only at the `:`
    // that annotates a parameter or the result — past the conflict point.
    // `f(): i64 … end` — a NAMED declaration, or the expression `f` followed
    // by an anonymous function value. Both are structurally valid; the
    // dynamic precedence on `bare_function_declaration` picks the declaration.
    // `@name` — an attribute BINDING to the next declaration, or a directive
    // standing alone as a statement. The dynamic precedence on
    // `_attribute_list` decides; both readings are in the corpus.
    [$._attribute_list, $.expression],
    // `M:hash(` / `pkg.fn(` — a declaration NAME or an expression that is
    // about to be called. Same tokens; the `:` inside the parameter list or
    // after the `)` is what decides.
    [$.function_name, $.expression],
    [$.function_name, $.jai_type_definition, $.typed_binding, $.expression],
    [$.function_name, $.catch_clause, $.expression],
    // `M:hash(…)` — a method declaration NAME, or `M:` annotating a value
    // whose type is the applied `hash(…)`.
    [$.function_name, $.applied_type],
    // `f(a, b)` in TYPE position — the parameter list of a function type, or
    // a tuple of two types. The `->` after the `)` is what decides.
    // `f(): result(x)` — the result type applied to arguments, or the plain
    // named result followed by a call in the body.
    [$.applied_type, $.named_type],
    // `Map<K, V>` — a generic type, or the plain name followed by `<`.
    [$.named_type, $.generic_type],
    // `*T & packed` — the `&` attaches to the whole pointer type or to `T`.
    [$.type_attribute],
    [$.attributed_type, $.pointer_type],
    [$.attributed_type, $.optional_type],
    [$.attributed_type, $.array_type],
    [$.attributed_type, $.function_type],
    // A signature with a body, or a bodyless declaration whose statements
    // happen to follow. `bare_function_declaration` carries the dynamic
    // precedence, so a body wins wherever one closes with `end`.
    [$.bare_function_declaration, $.foreign_declaration],
    // A directive's unannotated declaration argument shares its opening
    // parenthesis with the annotated signature both other declaration forms use.
    [$.directive_function, $._annotated_signature],
    // `f(...)` — a vararg PARAMETER (`zip(...): any`) or a call forwarding the
    // enclosing vararg. Only the `): type` after the paren tells them apart.
    [$.vararg_parameter, $.vararg],
    // `f(a, b)` — an unannotated PARAMETER list awaiting `): type`, or an
    // argument list of bare identifiers. Same token, decided after the `)`.
    // A lambda's parameter list uses the general `parameter`, which is a
    // superset of GR-001's `_plain_parameter`; both are live until the token
    // after the `)` says which signature this was.
    [$.parameter, $._plain_parameter],
    [$.parameter, $._plain_parameter, $.expression],
    // `() f()` — a zero-parameter lambda over the call, or the `()` block form
    // whose first statement is the call. The `end` is what decides, and it is
    // arbitrarily far away.
    [$.expression_statement, $.lambda_expression],
    [$.expression_statement, $.lambda_expression, $.call_expression],
    // `f()` — a zero-argument CALL, or the head of the `()` block form whose
    // body has not started yet.
    [$.function_value_expression, $.call_expression],
    [$.function_value_expression, $.lambda_expression, $.call_expression],
    [$.assignment, $.lambda_expression],
    // `a, b` — a value LIST standing as a statement, or the left side of an
    // assignment whose `=` has not arrived yet.
    [$.assignment, $.expression_statement, $.lambda_expression],
    [$.assignment, $.expression_statement, $.call_expression],
    // `if v, e = f()` — a binding CONDITION, or an expression list that is
    // about to be assigned. Identical until after the `=`.
    [$.binding_condition, $.call_expression],
    [$.compound_assignment, $.lambda_expression],
    [$.lambda_expression, $.call_expression],
    [$.lambda_expression, $.method_call_expression],
    [$.lambda_expression, $.index_expression],
    [$.lambda_expression, $.try_expression],
    [$.lambda_expression, $.unwrap_expression],
    // `(a: i64): i64 …` — an annotated signature awaiting a block body and an
    // `end`, or a lambda whose one-expression body starts right here. Only
    // reaching the `end` (or not) tells them apart.
    [$._annotated_signature, $.lambda_expression],
    [$._annotated_signature, $.lambda_expression, $.call_expression],
    [$.parameter, $._typed_parameter],
    [$.parameter, $._typed_parameter, $.expression],
    // `f(a: …)` — an annotated PARAMETER or the receiver of a method call
    // argument, `f(a:greet())`. The `:` is shared; the type is not.
    // `f()` immediately followed by `(): i64 … end` — a call, or a call whose
    // argument is a function VALUE. Only the token after the `)` decides.
    // unterminated statement lists — where does the body stop
    [$.do_block, $.while_loop],
    [$.do_block, $.numeric_for],
    [$.do_block, $.generic_for],
    [$.statement, $.try_statement],
    [$.catch_clause],
    [$.catch_clause, $.expression],
    [$.binding_name],
    // pattern position overlaps expression position
    [$.literal_pattern, $.expression],
    [$.literal_pattern, $.nil],
    [$.literal_pattern, $.boolean],
    [$.binding_pattern, $.expression],
    // `case Circle(r) …` with the `then` now optional — a variant PATTERN, or
    // a binding pattern followed by a one-expression arm that happens to be a
    // call.
    [$.binding_pattern, $.variant_pattern],
    [$.variant_pattern, $.expression],
    [$.table_pattern, $.table_constructor],
    // `{ a = ... b }` — a rest PATTERN binding `b`, or the vararg value
    // followed by the next newline-separated element.
    [$.rest_pattern, $.vararg],
    [$.match_statement, $.match_expression],
    [$.expression_statement, $.match_arm],
    [$.match_arm, $.index_expression],
    // An arm with no `then` and no `end` is closed by the next `case`/`else`
    // or by the `match`'s own `end`, and which of those it was is only known
    // once that token arrives.
    [$.match_arm],
    [$.do_block, $.match_arm],
    [$.repeat_loop, $.index_expression],
    [$.expression_statement, $.index_expression],
    // A `match` arm that writes neither `then` nor its own `end` leaves the
    // statement list open, so EVERY statement-final expression in it is
    // ambiguous with a postfix continuation on the next line — `x = f()` then
    // `[k]` is either an index on `f()` or a new statement. This is the same
    // family as the `do_block`/`while_loop` entries above; it is larger only
    // because an arm can hold any statement.
    [$.assignment, $.index_expression],
    [$.assignment, $.expression_statement, $.index_expression],
    [$.compound_assignment, $.index_expression],
    [$.local_declaration, $.index_expression],
    [$.const_declaration, $.index_expression],
    [$.global_declaration, $.index_expression],
    [$.return_statement, $.index_expression],
    [$.typed_binding, $.index_expression],
    // `case p if f(x)` — the arm's GUARD, or an `if` statement opening the
    // arm's body. Both are `if` followed by a condition; only the absence of
    // an `end` tells them apart.
    [$.guard, $.index_expression],
    [$.if_statement, $.guard],
    [$.if_statement, $.guard, $.call_expression],
    // prefix operators bind before the LR item is decided.
    //
    // Two entries were REMOVED here when the operator table was repaired —
    // `[binary_expression, unary_expression]` and the three-way with
    // `contains_expression`. They were necessary only because the precedence
    // table was inverted: with `-` and `not` carrying LESS binding power than
    // the binary operators they prefix, the automaton could not decide
    // `- a * b` and the conflict had to be declared. With unary at 12 and the
    // binaries at 2..13 around it, precedence decides, and the generator now
    // reports both as "unnecessary conflicts" — which the coverage gate treats
    // as a failure, so this is not an optional tidy-up.
    [$.binary_expression, $.contains_expression],
    [$.call_expression, $.await_expression],
    [$.index_expression, $.await_expression],
    [$.method_call_expression, $.await_expression],
    [$.try_expression, $.await_expression],
    [$.unwrap_expression, $.await_expression],
  ],

  // ── Rules ──────────────────────────────────────────────────────────────────

  rules: {
    // ── Top-level ───────────────────────────────────────────────────────────

    module: $ => seq(
      optional($.shebang),
      repeat($.statement),
    ),

    // `#!/usr/bin/env duo`. src/lexer.zig recognises `#!` only at index 0 and
    // so does this: `#` is the length operator everywhere else.
    shebang: $ => token(seq('#!', /[^\n]*/)),

    // ── Statements ──────────────────────────────────────────────────────────

    statement: $ => choice(
      $.local_declaration,
      $.const_declaration,
      $.global_declaration,
      $.assignment,
      $.compound_assignment,
      $.typed_binding,
      $.jai_type_definition,
      $.struct_definition,
      $.do_block,
      $.if_statement,
      $.while_loop,
      $.repeat_loop,
      $.numeric_for,
      $.generic_for,
      $.function_declaration,
      $.bare_function_declaration,
      $.foreign_declaration,
      $.return_statement,
      $.break_statement,
      $.goto_statement,
      $.label_statement,
      $.expression_statement,
      $.match_statement,
      $.try_statement,
      $.defer_statement,
      $.enum_definition,
      $.concept_definition,
      $.alias_definition,
      $.empty_statement,
    ),

    // Duo has no statement terminator, but `;` is a token (`semi`) and 16
    // tracked files use it to put two statements on one line.
    empty_statement: $ => ';',

    // ── Attributes ──────────────────────────────────────────────────────────

    // `@export`, `@ffi("puts")`, `@c.emit("code")`, `@comp.define.derive(…)`,
    // `@(expr)`.
    //
    // Two things were wrong here. The path was capped at TWO segments, so
    // `@comp.define.derive` and `@comp.embed.json` had no rule; and the
    // argument list was the raw regex `/[^)]*/`, which stops at the first `)`
    // it sees — so `@comp.assert(@comp.satisfies(Point, "HasXY"), "…")` ended
    // mid-argument and every nested call was an error. Arguments are ordinary
    // expressions, which is what they are in the compiler too.
    attribute: $ => prec.right(choice(
      seq('@', $.attribute_path, optional(seq(
        '(',
        // A directive argument may be a whole function: 22 tracked files write
        // `@comp.define.derive("Name", generate(meta) -> str … end)`, where the
        // second argument is a NAMED declaration, not an expression.
        commaSep(choice($.expression, $.bare_function_declaration, $.directive_function)),
        ')',
      ))),
      // @(expr) — compile-time evaluation
      seq('@', '(', $.expression, ')'),
    )),

    // `@comp.define.derive("Printable", generate(type_info) … end)` — a
    // declaration with NO annotation anywhere, which GR-001 forbids in
    // statement position because it would make a declaration candidate out of
    // every ordinary call. Inside a directive's argument list that objection
    // does not apply: a call reading exists but cannot complete, because the
    // statements that follow are not arguments. So the rule is REACHABLE ONLY
    // HERE — it is not in `statement` and not in `expression` — and the
    // exclusion that protects 791 call sites is untouched.
    directive_function: $ => seq(
      field('name', $.function_name),
      '(',
      commaSep(choice($.parameter, $.vararg_parameter)),
      ')',
      optional(seq($._result_arrow, field('result', $.type))),
      repeat($.statement),
      'end',
    ),

    // Right-associative so the path is GREEDY: `@comp.type.name(x)` is one
    // three-segment directive, not `@comp` with a field access hanging off it.
    attribute_path: $ => prec.right(seq(
      $.identifier,
      repeat(seq('.', $.identifier)),
    )),

    // An attribute BINDS to the declaration it precedes wherever one follows;
    // where none does (`@c.emit("code")` on its own line) the same syntax is a
    // statement. Both readings exist in the corpus, so the list carries a
    // dynamic precedence and attachment wins when it is available at all.
    _attribute_list: $ => prec.dynamic(1, repeat1($.attribute)),

    // ── Local declaration ───────────────────────────────────────────────────

    local_declaration: $ => seq(
      optional($._attribute_list),
      'local',
      commaSep1($.binding_name),
      optional(seq(
        ':',
        $.type,
      )),
      optional(seq(
        '=',
        commaSep1($.expression),
      )),
    ),

    binding_name: $ => seq(
      optional($._attribute_list),
      $.identifier,
      optional(seq(':', field('type', $.type))),
    ),

    // ── Const declaration ───────────────────────────────────────────────────

    const_declaration: $ => seq(
      'const',
      $.identifier,
      optional(seq(':', $.type)),
      '=',
      $.expression,
    ),

    // ── Global declaration ──────────────────────────────────────────────────

    global_declaration: $ => seq(
      'global',
      choice(
        '*',
        commaSep1($.binding_name),
      ),
      optional(seq(
        '=',
        commaSep1($.expression),
      )),
    ),

    // ── Assignment ──────────────────────────────────────────────────────────

    assignment: $ => seq(
      commaSep1($.expression),
      '=',
      commaSep1($.expression),
    ),

    // ── Compound assignment ─────────────────────────────────────────────────
    //
    // `+= -= *= /= %= ^=` are six distinct token kinds in src/lexer.zig
    // (`plus_assign` … `caret_assign`) and this grammar had none of them, so
    // `sub -= 1` parsed as `sub -` followed by `= 1`.
    compound_assignment: $ => seq(
      $.expression,
      choice('+=', '-=', '*=', '/=', '%=', '^='),
      $.expression,
    ),

    // ── Do block ────────────────────────────────────────────────────────────

    do_block: $ => seq(
      'do',
      repeat($.statement),
      'end',
    ),

    // ── If statement ────────────────────────────────────────────────────────

    if_statement: $ => seq(
      'if',
      choice($.binding_condition, $.expression),
      optional('then'),
      repeat($.statement),
      repeat($.elseif_clause),
      optional($.else_clause),
      'end',
    ),

    elseif_clause: $ => seq(
      'elseif',
      choice($.binding_condition, $.expression),
      optional('then'),
      repeat($.statement),
    ),

    // ── Condition ───────────────────────────────────────────────────────────
    //
    // Pass 100 §6: "binding condition IS the pattern match".
    //
    //   if v = f() use(v) else report(err)
    //   if v, err = parse(s) use(v) else log(err)      correlated refinement
    //   while b = cursor:next() mix(b)                 consumption loop
    //
    // A condition is therefore a BINDING or an expression, and the three
    // §6 fixtures (`examples/spec100/consume.duo`, `guard.duo`,
    // `examples/pass42_binding_conditions_proof.duo`) all open with one.
    // `duo check` accepts every form above.
    //
    // What this does NOT express is the guard chain's split. Pass 100 §6 says
    // `while b = pull() and small(b)` binds `b` to `pull()` alone and treats
    // the `and` as a correlated guard; here the `and` is inside the bound
    // expression, because `expression` already owns `and` at prec.left(10) and
    // excluding it would need a parallel expression hierarchy. The file is
    // recognised and the tree is well formed; the binding EXTENT is a
    // semantic fact this grammar does not carry, and `guard.duo` says
    // outright that the distinction has to be checked by value.
    binding_condition: $ => seq(
      commaSep1($.identifier),
      '=',
      $.expression,
    ),

    else_clause: $ => seq(
      'else',
      repeat($.statement),
    ),

    // ── While loop ──────────────────────────────────────────────────────────

    while_loop: $ => seq(
      'while',
      choice($.binding_condition, $.expression),
      optional('do'),
      repeat($.statement),
      'end',
    ),

    // ── Repeat loop ─────────────────────────────────────────────────────────

    repeat_loop: $ => seq(
      'repeat',
      repeat($.statement),
      'until',
      $.expression,
    ),

    // ── Numeric for ─────────────────────────────────────────────────────────

    numeric_for: $ => seq(
      'for',
      $.identifier,
      optional(seq(':', $.type)),
      '=',
      $.expression,
      ',',
      $.expression,
      optional(seq(',', $.expression)),
      optional('do'),
      repeat($.statement),
      'end',
    ),

    // ── Generic for ─────────────────────────────────────────────────────────

    generic_for: $ => seq(
      'for',
      commaSep1($.identifier),
      'in',
      commaSep1($.expression),
      optional('do'),
      repeat($.statement),
      'end',
    ),

    // ── Function declaration ────────────────────────────────────────────────

    function_declaration: $ => seq(
      optional($._attribute_list),
      optional('local'),
      choice('function', 'fun'),
      field('name', $.function_name),
      optional($.type_parameters),
      '(',
      commaSep($.parameter),
      optional(seq(',', '...')),
      ')',
      optional(seq($._result_arrow, $.type)),
      repeat($.statement),
      'end',
    ),

    // `<T>`, and `<T: Hashable>` / `<T: Hashable + Counter>` — a type
    // parameter may carry constraints, which `commaSep1($.type)` could not
    // express because `T: Hashable` is not a type.
    type_parameters: $ => seq(
      '<',
      commaSep1($.type_parameter),
      '>',
    ),

    type_parameter: $ => seq(
      $.identifier,
      optional(seq(':', $.type, repeat(seq('+', $.type)))),
    ),

    function_name: $ => seq(
      $.identifier,
      repeat(seq('.', $.identifier)),
      optional(seq(':', $.identifier)),
    ),

    // `step: i64 = default_step` — a default value. It is part of the
    // parameter, not an assignment smuggled into the list.
    parameter: $ => seq(
      optional($._attribute_list),
      $.identifier,
      optional(seq(':', field('type', $.type))),
      optional(seq('=', $.expression)),
    ),

    // ── Bare function declaration (GR-001) ──────────────────────────────────
    //
    // `fib(n: any)` / `_env_or(n: str, d: str): str` — no `fun`, no
    // `function`. This is Pass 100's canonical declaration form and it is 63 %
    // of what this grammar used to fail on.
    //
    // The two arms below are GR-001's disambiguation, not a stylistic choice.
    // `main()` followed by statements and an `end` is a CALL in this language,
    // not a declaration, so a bare head is only a declaration when it carries
    // AT LEAST ONE type annotation:
    //
    //   arm (a)  NO parameter is annotated, so a return type is REQUIRED —
    //            `f(a, b): i64`, `main(): i64`. `): i64` cannot follow a call.
    //   arm (b)  some parameter IS annotated, so the return type is optional —
    //            `fib(n: any)`, `arena_alloc(self, bytes: i64)`,
    //            `_env_or(n: str, d: str): str`. `x: T` is not an expression,
    //            so this cannot be an argument list either.
    //
    // The split is by the PARAMETERS, not by the return type, and that is what
    // keeps it LR(1): both arms open with the same unannotated-parameter
    // symbol, so nothing forks at `(`. The arms separate at the first `:`
    // inside the list — one token of lookahead after a parameter name, which
    // arm (a) cannot follow and arm (b) must.
    //
    // Corpus evidence for the exclusion (statement-initial heads, 748 tracked
    // files): 4645 have a return type, 230 have an annotated parameter and no
    // return type, 48 are `main()`-shaped with neither, and 791 are ordinary
    // calls like `print(out)`. Accepting the 48 would make every one of the
    // 791 a candidate declaration.
    // The precedence is against `function_value_expression`, not against the
    // call: `f(): i64 … end` is either this rule, or the bare expression `f`
    // followed by an anonymous function value. Both are structurally valid and
    // only one is ever meant, so it is settled statically rather than left to
    // GLR to pick a tree by size.
    bare_function_declaration: $ => prec.dynamic(3, seq(
      optional($._attribute_list),
      // `function_name` rather than a bare identifier: `M:hash(): i64` and
      // `pkg.fn(x: i64): i64` are declarations too.
      field('name', $.function_name),
      $._annotated_signature,
      repeat($.statement),
      'end',
    )),

    // ── Foreign / bodyless declaration ──────────────────────────────────────
    //
    // `@ffi("llabs")` then `llabs(n: i64): i64` — a signature with no body and
    // no `end`. 43 tracked files declare something this way (`@ffi`, `@export`,
    // `@native`, `@hot`, `@device(.cuda)`, `@test.unit`).
    //
    // An attribute list is REQUIRED, and that is what keeps the rule safe: a
    // bare signature with no body is otherwise indistinguishable from one whose
    // body follows, and the dynamic precedence on `bare_function_declaration`
    // is what settles the case where an `end` does turn up.
    foreign_declaration: $ => seq(
      $._attribute_list,
      field('name', $.function_name),
      $._annotated_signature,
    ),

    // The signature carrying GR-001's annotation requirement. Shared with
    // `function_value_expression` so the two spellings of a Duo function
    // cannot drift apart.
    _annotated_signature: $ => choice(
      seq(
        '(',
        optional(seq(
          optional($._plain_parameter_prefix),
          choice(alias($._plain_parameter, $.parameter), $.vararg_parameter),
        )),
        ')',
        $._result_arrow,
        field('result', $.type),
      ),
      seq(
        '(',
        optional($._plain_parameter_prefix),
        alias($._typed_parameter, $.parameter),
        repeat(seq(',', choice($.parameter, $.vararg_parameter))),
        ')',
        optional(seq($._result_arrow, field('result', $.type))),
      ),
    ),

    // `:` and `->` are the same thing here — `hash(self) -> i64` in a concept
    // body, `generate(meta) -> str` as a derive argument, `f(n: i64): i64`
    // everywhere else. `arrow` is its own token in src/lexer.zig.
    _result_arrow: $ => choice(':', '->'),

    // Both arms open on THIS symbol, which is why nothing forks at `(`. One
    // token of lookahead after a parameter name settles it: `,` continues the
    // prefix, `)` ends arm (a), `:` starts arm (b)'s pivot.
    _plain_parameter_prefix: $ => repeat1(
      seq(alias($._plain_parameter, $.parameter), ','),
    ),

    _plain_parameter: $ => seq(
      optional($._attribute_list),
      $.identifier,
    ),

    _typed_parameter: $ => seq(
      optional($._attribute_list),
      $.identifier,
      ':',
      field('type', $.type),
      optional(seq('=', $.expression)),
    ),

    vararg_parameter: $ => seq(
      '...',
      optional($.identifier),
    ),

    // ── Return ──────────────────────────────────────────────────────────────

    return_statement: $ => prec.right(seq(
      'return',
      optional(commaSep1($.expression)),
    )),

    // ── Break ───────────────────────────────────────────────────────────────

    break_statement: $ => 'break',

    // ── Goto ────────────────────────────────────────────────────────────────

    goto_statement: $ => seq(
      'goto',
      $.identifier,
    ),

    label_statement: $ => seq(
      '::',
      $.identifier,
      '::',
    ),

    // ── Expression statement ────────────────────────────────────────────────

    // `best_len, best_offset` and `buf:sub(1, n), nil` — a comma-separated
    // VALUE list standing as the last statement of a body. Pass 100 §5 makes
    // it the normal way to return a pair (`parse = (lx): ast | error`, the
    // last expression realized through one direct edge), and there is no
    // `return` to mark it. `duo check` accepts it; this grammar had only the
    // single-expression form, so a two-value tail was an error node.
    expression_statement: $ => commaSep1($.expression),

    // ── Match statement ─────────────────────────────────────────────────────

    match_statement: $ => seq(
      'match',
      $.expression,
      repeat($.match_arm),
      'end',
    ),

    match_arm: $ => choice(
      seq(
        'case',
        $.pattern,
        optional($.guard),
        // `then`/`do` is OPTIONAL, and so is the arm's own `end`. Both
        // spellings are live in the corpus and both compile:
        //
        //   case 0x7F "int32_t"                 one expression, no ceremony
        //   case 0 -- u8
        //     val, new_pos = read(data, pos), pos + 1
        //   case Circle(r) then … end           the fully written form
        //
        // An arm with neither `then` nor `end` is closed by the NEXT `case`,
        // by `else`, or by the `match`'s own `end` — the same self-delimiting
        // clause rule Pass 100 §6 gives `if`, and the reason this needs a
        // `conflicts:` entry of its own: where the arm stops is not decidable
        // until the token that stops it arrives.
        optional(choice('then', 'do')),
        repeat($.statement),
        optional('end'),
      ),
      // The default arm of a `match`, spelled with `else` rather than `_`.
      seq('else', repeat($.statement), optional('end')),
      seq(
        $.pattern,
        optional($.guard),
        '=>',
        choice(
          $.expression,
          seq(repeat($.statement), 'end'),
        ),
      ),
    ),

    guard: $ => seq(
      'if',
      $.expression,
    ),

    // ── Pattern ─────────────────────────────────────────────────────────────

    pattern: $ => choice(
      $.literal_pattern,
      $.binding_pattern,
      $.variant_pattern,
      $.table_pattern,
      $.array_pattern,
      $.rest_pattern,
      '_',
    ),

    literal_pattern: $ => choice(
      $.number,
      $.string,
      'true',
      'false',
      'nil',
    ),

    binding_pattern: $ => seq(
      $.identifier,
      optional(seq(':', $.type)),
    ),

    variant_pattern: $ => seq(
      $.identifier,
      '(',
      commaSep($.pattern),
      ')',
    ),

    table_pattern: $ => seq(
      '{',
      commaSep($.table_pattern_entry),
      '}',
    ),

    table_pattern_entry: $ => seq(
      $.identifier,
      '=',
      $.pattern,
    ),

    array_pattern: $ => seq(
      '[',
      commaSep($.pattern),
      ']',
    ),

    rest_pattern: $ => seq(
      '...',
      $.identifier,
    ),

    // ── Try statement ───────────────────────────────────────────────────────

    try_statement: $ => seq(
      'try',
      repeat($.statement),
      repeat($.catch_clause),
      optional($.defer_statement),
      'end',
    ),

    catch_clause: $ => seq(
      'catch',
      optional($.identifier),
      repeat($.statement),
    ),

    // ── Defer statement ─────────────────────────────────────────────────────

    defer_statement: $ => seq(
      'defer',
      repeat($.statement),
      'end',
    ),

    // ── Enum definition ─────────────────────────────────────────────────────

    enum_definition: $ => seq(
      optional($._attribute_list),
      'enum',
      $.identifier,
      optional($.type_parameters),
      repeat($.enum_variant),
      'end',
    ),

    enum_variant: $ => seq(
      $.identifier,
      optional(seq(
        '(',
        commaSep1($.enum_field),
        ')',
      )),
    ),

    enum_field: $ => seq(
      optional(seq($.identifier, ':')),
      $.type,
    ),

    // ── Concept definition ──────────────────────────────────────────────────

    concept_definition: $ => seq(
      optional($._attribute_list),
      'concept',
      $.identifier,
      optional($.type_parameters),
      repeat(choice(
        $.concept_method,
        $.concept_field,
      )),
      'end',
    ),

    concept_method: $ => seq(
      $.identifier,
      '(',
      commaSep($.parameter),
      ')',
      $._result_arrow,
      $.type,
    ),

    concept_field: $ => seq(
      $.identifier,
      ':',
      $.type,
    ),

    // ── Alias definition ────────────────────────────────────────────────────

    // Two forms. The block form (`alias Name extends Base … end`) was here;
    // `alias Point = { x: f64, y: f64 }`, which 7 tracked files open with, was
    // not, so those files failed on their first line.
    alias_definition: $ => seq(
      optional($._attribute_list),
      'alias',
      $.identifier,
      choice(
        seq('=', $.type),
        seq(
          optional(seq('extends', $.identifier)),
          repeat($.alias_member),
          'end',
        ),
      ),
    ),

    // ── Type definition (type Name = Type) — REMOVED ────────────────────────
    //
    // `type` is a plain identifier in Duo, and reserving it here was what made
    // `type(x)` unparseable. The removal is measured, not assumed:
    //
    //   `type X = T` statement-initial, over the tracked corpus:    0
    //   `type(` as a call or declaration head:                    231
    //
    // and both authorities agree with the count — CLAUDE.md §1 denies
    // `type X = type(` by name, and Pass 100 §15 lists `type` among the
    // keywords that are retiring (`local self type req new init end`). So the
    // canonical reading of a file that writes `type(obj: any): any` is a
    // DECLARATION of a function called `type`, which is what `lib/std/io.duo`,
    // `lib/std/meta.duo` and `lib/std/reflect.duo` all mean by it.
    //
    // This is the one rule this pass removed, and it is removed rather than
    // kept-and-shadowed because a tree-sitter keyword token wins over
    // `identifier` in every state that admits both: as long as `'type'` is
    // spelled anywhere in the grammar, `type(x)` cannot lex as a call.
    // `duo check` accepts both spellings, so the exclusion is this grammar's
    // lexer, not the language's.

    // ── Jai-like type definition (Name: { fields }) ─────────────────────────

    jai_type_definition: $ => seq(
      optional($._attribute_list),
      $.identifier,
      ':',
      $.record_type,
    ),

    // ── Typed binding (name: Type = expr) ───────────────────────────────────

    typed_binding: $ => seq(
      optional($._attribute_list),
      $.identifier,
      ':',
      $.type,
      '=',
      $.expression,
    ),

    // ── Struct definition (Name = struct ... end) ────────────────────────────

    struct_definition: $ => seq(
      optional($._attribute_list),
      $.identifier,
      '=',
      'struct',
      repeat($.struct_field),
      'end',
    ),

    struct_field: $ => seq(
      $.identifier,
      optional(seq(':', $.type)),
      optional(seq('=', $.expression)),
    ),

    alias_member: $ => choice(
      $.alias_field,
      $.function_declaration,
    ),

    alias_field: $ => seq(
      optional('private'),
      $.identifier,
      ':',
      $.type,
      optional(seq('=', $.expression)),
    ),

    // ── Types ───────────────────────────────────────────────────────────────

    type: $ => choice(
      $.named_type,
      $.array_type,
      $.pointer_type,
      $.optional_type,
      $.generic_type,
      $.function_type,
      $.record_type,
      $.tuple_type,
      $.applied_type,
      $.attributed_type,
      // `ptr: *@c.type("void")` — a directive standing in TYPE position, which
      // is where a foreign type comes from. `duo check` accepts it and the
      // directive's own rule already parses the arguments.
      $.attribute,
    ),

    // `fun gguf_read_string(data, pos): (str, i64)` — a result that is a PAIR.
    // Pass 100 §5's return contract routinely carries two values
    // (`: ast | error`, `: u64 | error`), and the parenthesised spelling is
    // what `ext/ward/src/nn/init.duo` writes for it.
    tuple_type: $ => seq(
      '(',
      commaSep1($.type),
      ')',
    ),

    // `tags: list(str)` — a type CONSTRUCTOR applied with parentheses. Pass
    // 100 §15 graveyards `<T>` generics syntax, so the family form
    // (`list(str)`, `map(str, i64)`) is the surviving spelling and
    // `examples/spec100/level.duo` is its fixture.
    applied_type: $ => seq(
      $.identifier,
      '(',
      commaSep1($.type),
      ')',
    ),

    // `{ x: i8, y: i64 } & packed & align(16)` — layout attributes hung off a
    // type with `&`. `examples/layout_refinements_test.duo` is the fixture and
    // the compiler accepts it.
    attributed_type: $ => prec.left(seq(
      $.type,
      repeat1(seq('&', $.type_attribute)),
    )),

    type_attribute: $ => seq(
      $.identifier,
      optional(seq('(', commaSep($.expression), ')')),
    ),

    named_type: $ => $.identifier,

    // `[4]i32` (Jai-style, element type after the brackets) and `[string]` /
    // `[float]` (element type INSIDE them). Both are in the corpus; only the
    // first was in this grammar.
    array_type: $ => choice(
      seq('[', optional($.number), ']', $.type),
      seq('[', $.type, ']'),
    ),

    pointer_type: $ => seq(
      '*',
      $.type,
    ),

    optional_type: $ => seq(
      '?',
      $.type,
    ),

    // `Map<K, V>` and `Tensor[784, 256, f32]` — the bracket form takes shape
    // arguments, so a dimension is a NUMBER where a type would otherwise be.
    generic_type: $ => choice(
      seq($.identifier, '<', commaSep1($.type), '>'),
      seq($.identifier, '[', commaSep1(choice($.type, $.number)), ']'),
    ),

    function_type: $ => seq(
      '(',
      commaSep($.type),
      ')',
      '->',
      $.type,
    ),

    // `{ x: f64, y: f64 }` and its Pass 100 spelling `@{ x: f64, y: f64 }`.
    // CLAUDE.md §0.4 names `@{ … }` as the descriptor form; 25 tracked files
    // open a record with it and this grammar had no `@` here at all.
    // The separator is the NEWLINE and the comma is the optional one. Pass 100
    // §7 X8 — ">=2 named fields -> one per line, always" — makes the one-per-
    // line spelling mandatory for a record of two or more fields, so a record
    // type that carries no comma at all is the CANONICAL one, not a variant.
    // `examples/spec100/x8.duo` is the fixture and `duo check` accepts it; this
    // grammar stopped at the first missing comma. Extras already eat the
    // newline, so the separator is simply optional here.
    //
    // `commaSep1` -> `sepBy` also makes the EMPTY record (`alias M = {}`,
    // `type Empty = {}`) legal, which it is: a concept with no requirements is
    // satisfied by everything, which is what those two fixtures are testing.
    record_type: $ => seq(
      optional('@'),
      '{',
      sepBy(choice($.record_field, $.spread_entry)),
      '}',
    ),

    // The type is OPTIONAL because a bare name is a CASE, not an untyped
    // field: `Direction: @{ North, South, East, West }` is CLAUDE.md §0.3's
    // "case-set inline at the field", and it is how `examples/architecture_
    // proof.duo` and `examples/pass3_syntax_showcase.duo` spell an enum now
    // that `enum … end` is denied. `duo check` accepts it.
    record_field: $ => seq(
      $.identifier,
      optional(seq(':', $.type)),
    ),

    // ── Expressions ─────────────────────────────────────────────────────────

    expression: $ => choice(
      $.nil,
      $.boolean,
      $.number,
      $.string,
      $.vararg,
      $.identifier,
      $.binary_expression,
      $.unary_expression,
      $.function_expression,
      $.function_value_expression,
      $.lambda_expression,
      $.table_constructor,
      $.descriptor_constructor,
      $.attribute,
      $.field_projection,
      $.index_expression,
      $.field_expression,
      $.semantic_field_expression,
      $.call_expression,
      $.method_call_expression,
      $.try_expression,
      $.unwrap_expression,
      $.match_expression,
      $.await_expression,
      $.contains_expression,
      $.parenthesized_expression,
    ),

    // ── Function expression ─────────────────────────────────────────────────

    function_expression: $ => seq(
      choice('function', 'fun'),
      '(',
      commaSep($.parameter),
      optional(seq(',', '...')),
      ')',
      optional(seq($._result_arrow, $.type)),
      repeat($.statement),
      'end',
    ),

    // ── Function value (the VALUE form of GR-001) ───────────────────────────
    //
    // `main = (): i64 … end`, `sum = (a: i64, b: i64): i64 … end`. Same
    // annotation requirement as the bare declaration, and for the same reason:
    // without it `x = (a) f() end` is indistinguishable from a parenthesised
    // expression followed by two more statements.
    function_value_expression: $ => choice(
      seq($._annotated_signature, repeat($.statement), 'end'),
      // `pull = ()\n  pos = pos + 1\n  src[pos]\nend` — ZERO parameters, so
      // there is nothing to annotate and `_annotated_signature` cannot reach
      // it. It needs no dynamic precedence and no exclusion because `()` is
      // not a parenthesized expression: an empty paren pair in value position
      // can only be a signature. `examples/spec100/consume.duo` and
      // `guard.duo` are the §6 fixtures, and `lib/std/sync.duo` writes the
      // same thing as an argument (`coroutine.create(() … end)`).
      //
      // `prec.dynamic(-1)`, and it is load-bearing. Without it
      // `_platform = detect_platform()` on one line and ordinary statements
      // below it also reads as `detect_platform` followed by a zero-parameter
      // function VALUE whose body runs to the next stray `end` — a reading
      // that stays alive to the end of the file and took two whole modules
      // (`lib/std/fs_watch.duo`, `examples/benchmark.duo`) down to a single
      // file-wide ERROR node. A `(` that can attach to the expression on its
      // left is a CALL; this arm only wins where nothing precedes it.
      prec.dynamic(-1, seq('(', ')', repeat($.statement), 'end')),
    ),

    // ── Expression-body function value ──────────────────────────────────────
    //
    // `less = (a, b) a < b`, `fh.close = (self: any) nil`,
    // `cmp or ((a, b) a < b)`, `small = (n) n < 7`. Pass 100 §5 states it as
    // law — "A one-expression body IS one line (mandatory)" — so this is the
    // canonical spelling of a one-expression function and `… end` is the
    // variant, not the other way round.
    //
    // The body is an EXPRESSION and nothing else. `(v) return v * 2` is NOT
    // accepted, and that is not an omission: `duo check` rejects it
    // (`expected ')', got 'return'`), Pass 100 §15 graveyards the trailing
    // `return expr`, and the three tracked files that write it therefore stay
    // unrecognised because they do not compile. The compiler was used as the
    // oracle for every arm here rather than the corpus, so the grammar cannot
    // drift into accepting what the language does not.
    //
    // `prec.dynamic(-1)` is what keeps it from eating ordinary code. `(a) - 1`
    // is a subtraction, not a lambda over `-1`; `(f)(x)` is a call, not a
    // lambda over `(x)`. Both readings are structurally valid and GLR keeps
    // both alive, so the lambda has to LOSE by default and win only where no
    // other reading exists — which is exactly the `(a, b) …` / `() …` /
    // `(x: T) …` shapes, none of which can be a parenthesized expression.
    // Static `prec` cannot express this: it would resolve at the `(`, before
    // the token that decides has been seen.
    lambda_expression: $ => prec.dynamic(-1, seq(
      '(',
      commaSep(choice($.parameter, $.vararg_parameter)),
      ')',
      optional(seq($._result_arrow, field('result', $.type))),
      field('body', $.expression),
    )),

    // ── Table constructor ───────────────────────────────────────────────────

    // Same newline-is-the-separator rule as `record_type`, and for the same
    // reason: `config = { name = "duo"\n version = "0.5.0" }` and
    // `nn { linear(784, 256)\n relu\n softmax }` are both accepted by
    // `duo check` and both stopped this grammar at the first missing comma.
    // A string KEY (`["a"] = 1` written as `"a" = 1`) is here too — one
    // tracked file writes it and the compiler takes it.
    table_constructor: $ => seq(
      '{',
      sepBy(choice($.table_entry, $.spread_entry)),
      '}',
    ),

    table_entry: $ => choice(
      seq(choice($.identifier, $.string), '=', $.expression),
      // `hobbies: [string] = { … }` — an entry that declares its own type.
      // `examples/file_scoped_guy.duo` writes a whole record this way.
      seq($.identifier, ':', field('type', $.type), '=', $.expression),
      seq('[', $.expression, ']', '=', $.expression),
      $.expression,
    ),

    // ── Field projection / method reference ─────────────────────────────────
    //
    // `has(.err)(r)`, `map(users, .name)`, `t:sort(.key)`,. A leading `.` in VALUE
    // position names a field of whatever the receiver turns out to be —
    // CLAUDE.md §0 spells `t:sort(.key)` as canonical. 35 tracked files use it
    // and this grammar could only see `.` as a field access on a preceding
    // expression.
    // Lowest precedence of anything that can consume a `.`: wherever the dot
    // could extend a dotted NAME or attach to the expression on its left, it
    // does, and a projection is only what is left over in value position.
    field_projection: $ => prec(-1, seq('.', $.identifier)),

    // ── Descriptor constructor ──────────────────────────────────────────────
    //
    // `@{ eof = 0, ident = 1 }` and the update form `@{ ..self, x = nx }`.
    // Field TYPES (`@{ kind: i64 }`) are not here: that spelling only occurs
    // in type position, where `record_type` now carries the same `@`.
    descriptor_constructor: $ => seq(
      '@',
      '{',
      sepBy(choice($.table_entry, $.spread_entry)),
      '}',
    ),

    // `@{ ..self, x = nx }` — CLAUDE.md §0.4's update form — and the same
    // spelling in a plain `{ ..defaults, color = "red" }` and in a record TYPE
    // (`Sprite: @{ ..Named, ..Colored, x: f64 }`, composition by inclusion).
    // One rule, because it is one construct: take everything from that, then
    // override.
    spread_entry: $ => seq('..', $.expression),

    // ── Postfix expressions ─────────────────────────────────────────────────

    index_expression: $ => seq(
      $.expression,
      '[',
      $.expression,
      ']',
    ),

    // Higher precedence than starting a new statement with a
    // `field_projection`: a `.` that CAN attach to the expression on its left
    // always does. `f(x)\n.y` is a field access, not two statements.
    field_expression: $ => prec(1, seq(
      $.expression,
      '.',
      $.identifier,
    )),

    // `p.@eq` — reaching the DESCRIPTOR's own surface rather than a data
    // field. CLAUDE.md §0.2 keeps bare `@` as "my descriptor" after the
    // directive prefix was retired, and `examples/pass38_semantic_access_g6.
    // duo` reads `p.@eq` to prove the semantic is present.
    semantic_field_expression: $ => prec(1, seq(
      $.expression,
      '.',
      '@',
      $.identifier,
    )),

    // The dynamic precedence is what makes a `(` following an expression
    // ATTACH as a call. Without it `if f(x) …` read its condition as the bare
    // `f` and made `(x)` a separate statement — a wrong tree with no ERROR
    // node, so nothing counted it. Pre-existing; fixed here because the same
    // ambiguity governs the two sugar forms below.
    //
    // `req "std.os"` and `nn { … }` are Lua's argument sugar: a single string
    // or table literal may be passed without parentheses. 95 tracked files use
    // the string form, and every one of them was parsing as two unrelated
    // statements rather than as an error, so this is a correctness repair that
    // the recognition count could not see.
    call_expression: $ => prec.dynamic(1, seq(
      $.expression,
      choice(
        seq('(', commaSep($.expression), ')'),
        $.string,
        $.table_constructor,
      ),
    )),

    method_call_expression: $ => seq(
      $.expression,
      ':',
      $.identifier,
      '(',
      commaSep($.expression),
      ')',
    ),

    // ── Try/unwrap expressions ──────────────────────────────────────────────

    try_expression: $ => seq(
      $.expression,
      '?',
    ),

    unwrap_expression: $ => seq(
      $.expression,
      '!',
    ),

    // ── Match expression ────────────────────────────────────────────────────

    match_expression: $ => seq(
      'match',
      $.expression,
      repeat($.match_arm),
      'end',
    ),

    // ── Await expression ────────────────────────────────────────────────────

    await_expression: $ => seq(
      'await',
      $.expression,
    ),

    // ── Contains expression ─────────────────────────────────────────────────

    contains_expression: $ => seq(
      $.expression,
      'in',
      $.expression,
    ),

    // ── Parenthesized ───────────────────────────────────────────────────────

    parenthesized_expression: $ => seq(
      '(',
      $.expression,
      ')',
    ),
  // @@residue:end

    nil: $ => 'nil',

    boolean: $ => choice('true', 'false'),

    number: $ => choice(
      $.integer,
      $.float,
    ),

    integer: $ => token(choice(
      /[0-9]+/,
      /0x[0-9a-fA-F]+/,
    )),

    float: $ => token(choice(
      /[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?/,
      /[0-9]+[eE][+-]?[0-9]+/,
    )),

    string: $ => choice(
      $.double_quoted_string,
      $.single_quoted_string,
      $.long_string,
    ),

    double_quoted_string: $ => token(seq(
      '"',
      repeat(choice(
        /[^"\\]+/,
        /\\./,
      )),
      '"',
    )),

    single_quoted_string: $ => token(seq(
      "'",
      repeat(choice(
        /[^'\\]+/,
        /\\./,
      )),
      "'",
    )),

    // The body was `/[^]]*/` — "no `]` at all" — so a long string containing
    // an index expression (`a[i]`) or a C statement ended at the first `]` and
    // took the rest of the file with it. A `]` is body text unless the NEXT
    // character is also `]`, which is the closing delimiter. Stated as an
    // alternation rather than a lookahead because tree-sitter's token DFA has
    // none; it stays non-greedy across two long strings in one file precisely
    // because `]]` can never be consumed as body.
    //
    // ONE ALTERNATIVE PER LEVEL, and the GENERATOR writes them now. A single
    // token DFA cannot remember how many `=` it opened with, so each body is
    // "any character, or a `]` run shorter than MY closer" — a function of the
    // level, and previously three lines that had to be checked by eye.
    // Levels 0 and 1 are what the corpus uses (108 `[[` and 1 `[=[`); level 2
    // is here so the next one does not reopen this.
    long_string: $ => token(choice(
      seq('[[', repeat(choice(/[^\]]/, /\][^\]]/)), ']]'),
      seq('[=[', repeat(choice(/[^\]]/, /\][^=]/, /\]=[^\]]/)), ']=]'),
      seq('[==[', repeat(choice(/[^\]]/, /\][^=]/, /\]=[^=]/, /\]==[^\]]/)), ']==]'),
    )),

    vararg: $ => '...',

    identifier: $ => /[a-zA-Z_][a-zA-Z0-9_]*/,

    // ── Binary operators ──────────────────────────────────────────────

    binary_expression: $ => choice(
      prec.left(3, seq($.expression, 'or', $.expression)),
      prec.left(4, seq($.expression, 'and', $.expression)),
      prec.left(5, seq($.expression, '<', $.expression)),
      prec.left(5, seq($.expression, '>', $.expression)),
      prec.left(5, seq($.expression, '<=', $.expression)),
      prec.left(5, seq($.expression, '>=', $.expression)),
      prec.left(5, seq($.expression, '~=', $.expression)),
      // `!=` is the SAME token as `~=` in src/lexer.zig (both lex to `.neq`),
      // and it is the spelling 271 tracked files actually use. Without it
      // `a != nil` lexed as an unwrap_expression `a!` followed by `= nil`.
      prec.left(5, seq($.expression, '!=', $.expression)),
      prec.left(5, seq($.expression, '==', $.expression)),
      prec.left(5, seq($.expression, 'in', $.expression)),
      prec.left(7, seq($.expression, '|', $.expression)),
      // `&` (amp) and binary `~` (xor) are in the lexer's token table and were
      // not in this one; `|` alone was.
      prec.left(8, seq($.expression, '&', $.expression)),
      prec.left(7, seq($.expression, '~', $.expression)),
      prec.left(9, seq($.expression, '<<', $.expression)),
      prec.left(9, seq($.expression, '>>', $.expression)),
      prec.left(2, seq($.expression, '|>', $.expression)),
      prec.left(6, seq($.expression, '..', $.expression)),
      prec.left(10, seq($.expression, '+', $.expression)),
      prec.left(10, seq($.expression, '-', $.expression)),
      prec.left(11, seq($.expression, '*', $.expression)),
      prec.left(11, seq($.expression, '/', $.expression)),
      prec.left(11, seq($.expression, '//', $.expression)),
      prec.left(11, seq($.expression, '%', $.expression)),
      prec.right(13, seq($.expression, '^', $.expression)),
    ),

    // ── Unary operators ───────────────────────────────────────────────

    // Unary binds tighter than every binary operator except `^`, which is what
    // `-a^b` meaning `-(a^b)` requires. Its level is one below `^` and one
    // above `*`, and it moves with them because it is in the same table.
    unary_expression: $ => choice(
      prec(12, seq('not', $.expression)),
      prec(12, seq('#', $.expression)),
      prec(12, seq('##', $.expression)),
      prec(12, seq('comptime', $.expression)),
      prec(12, seq('-', $.expression)),
      prec(12, seq('~', $.expression)),
    ),

    // ── Comments ───────────────────────────────────────────────────

    comment: $ => token(choice(
      seq('--', /[^\n]*/),
      seq('--', '[', repeat('='), '[',
          repeat(choice(/[^\]]/, seq(']', /[^\]]/))),
          ']', repeat('='), ']'),
    )),
  },
});

// ── Helpers ────────────────────────────────────────────────────────────────────────────

function commaSep(rule) {
  return optional(commaSep1(rule));
}

function commaSep1(rule) {
  return seq(rule, repeat(seq(',', rule)));
}

// Pass 100 §7 X8: the NEWLINE is the canonical separator inside a braced group
// and the comma is the optional one. `extras` already consumes the newline, so
// "optional comma between elements, optional trailing comma" is the whole rule.
function sepBy(rule) {
  return optional(seq(rule, repeat(seq(optional(','), rule)), optional(',')));
}
