/**
 * @file tree-sitter grammar for Duo — GENERATED.
 *
 * GENERATED by scripts/treesitter_emit.id — do not edit the generated
 * regions by hand. Regenerate with:
 *
 *     duo run scripts/treesitter_emit.id
 *
 * `zig build treesitter-projection` regenerates and FAILS unless the result is
 * byte-identical to the tracked file, so a hand edit to a generated region
 * cannot survive review. A generated file nobody regenerates is an authored
 * file with extra steps.
 *
 * ── THE BOUNDARY, stated rather than banner-washed ──────────────────────────
 *
 * Everything in this file is emitted from registries in the generator.
 * The carried authored residue is currently
 *
 *     0 lines
 *
 * and that number is what gaps/GAP-049 is measured by.
 *
 * GENERATED, and from what:
 *   name / extras / supertypes    the head registry
 *   conflicts                     the conflict registry
 *   module / statement shell      the rule head registry
 *   attributes                    the attribute rule registry
 *   declarations / assignments    the declaration rule registry
 *   control flow                  the control rule registry
 *   function forms                the function rule registry
 *   tail statements               the tail statement registry
 *   match and pattern forms       the pattern registry
 *   definitions                   the definition registry
 *   types                         the type registry
 *   expression head               the expression registry
 *   expression tail               the expression registry
 *   literal tokens                the token registry
 *   long_string levels 0..2       ONE template per level; the body
 *                                 alternation that excludes the closing
 *                                 delimiter is computed from the level
 *   double / single quoted string ONE template, two quote characters
 *   binary_expression             one table of spelling, level and
 *   unary_expression              associativity, compared pair by pair
 *                                 against docs/spec/grammar.md §2 with every
 *                                 divergence PRINTED. That comparison is how
 *                                 the inverted precedence table was found.
 *   comment / helpers             the tail registry
 *
 * NOT GENERATED FROM DOC EBNF, and why:
 *   structural productions         docs/spec/grammar.md §3 states them as EBNF
 *                                  for the PASS-100 surface. The tracked corpus
 *                                  is still mostly pre-Pass-100, so the registry
 *                                  intentionally preserves editor recognition.
 *   NEWLINE / INDENT / DEDENT      tree-sitter has no offside layer. It needs
 *                                 an external scanner, which is a C file, and
 *                                 this tree has none — see
 *                                 ext/tree-sitter-duo/src. That hole is why
 *                                 examples/layout/offside.id is a single
 *                                 ERROR node from [0,0] to end of file.
 *
 * Classified as generated by scripts/jsledger.id only when
 * TSEMIT_CHECK=1 regeneration is byte-identical to the tracked file.
 */

module.exports = grammar({
  name: 'duo',

  extras: $ => [
    /\s/,
    $.comment,
  ],

  supertypes: $ => [
    $.statement,
    $.expression,
    $.type,
    $.pattern,
  ],

  conflicts: $ => [
    [$.struct_definition, $.expression],
    [$.typed_binding, $.call_expression],
    [$.assignment, $.call_expression],
    [$.compound_assignment, $.call_expression],
    [$.local_declaration, $.call_expression],
    [$.const_declaration, $.call_expression],
    [$.global_declaration, $.call_expression],
    [$.return_statement, $.call_expression],
    [$.repeat_loop, $.call_expression],
    [$.expression_statement, $.call_expression],
    [$.expression, $.call_expression],
    [$.match_arm, $.expression_statement, $.call_expression],
    [$.table_entry, $.call_expression],
    [$.table_entry, $.index_expression],
    [$.table_entry, $.expression],
    [$.spread_entry, $.call_expression],
    [$.spread_entry, $.index_expression],
    [$.call_expression, $.parenthesized_expression],
    [$.attribute, $.anchor_expression],
    [$.descriptor_constructor, $.anchor_expression],
    [$._attribute_list, $.expression],
    [$.function_name, $.expression],
    [$.function_name, $.function_expression],
    [$.function_name, $.jai_type_definition, $.type_alias_definition, $.typed_binding, $.expression],
    [$.function_name, $.catch_clause, $.expression],
    [$.function_name, $.applied_type, $.named_type],
    [$.jai_type_definition, $.type],
    [$.applied_type, $.named_type],
    [$.named_type, $.generic_type],
    [$.type_attribute],
    [$.attributed_type, $.pointer_type],
    [$.attributed_type, $.optional_type],
    [$.attributed_type, $.array_type],
    [$.attributed_type, $.function_type],
    [$.pack_type, $.pointer_type],
    [$.pack_type, $.optional_type],
    [$.pack_type, $.array_type],
    [$.pack_type, $.function_type],
    [$.bare_function_declaration, $.foreign_declaration],
    [$.bare_function_declaration, $.builtinname],
    [$.type_alias_definition, $.builtinname],
    [$.directive_function, $._annotated_signature],
    [$.vararg_parameter, $.vararg],
    [$.parameter, $._plain_parameter],
    [$.parameter, $._plain_parameter, $.expression],
    [$.expression_statement, $.lambda_expression],
    [$.expression_statement, $.if_expression],
    [$.expression_statement, $.lambda_expression, $.call_expression],
    [$.function_value_expression, $.call_expression],
    [$.function_value_expression, $.lambda_expression, $.call_expression],
    [$.assignment, $.lambda_expression],
    [$.assignment, $.expression_statement, $.lambda_expression],
    [$.assignment, $.expression_statement, $.call_expression],
    [$.binding_condition, $.call_expression],
    [$.compound_assignment, $.lambda_expression],
    [$.lambda_expression, $.call_expression],
    [$.lambda_expression, $.method_call_expression],
    [$.lambda_expression, $.index_expression],
    [$.lambda_expression, $.try_expression],
    [$.lambda_expression, $.unwrap_expression],
    [$._annotated_signature, $.lambda_expression],
    [$._annotated_signature, $.lambda_expression, $.call_expression],
    [$.parameter, $._typed_parameter],
    [$.parameter, $._typed_parameter, $.expression],
    [$.do_block, $.while_loop],
    [$.do_block, $.numeric_for],
    [$.do_block, $.generic_for],
    [$.statement, $.try_statement],
    [$.catch_clause],
    [$.catch_clause, $.expression],
    [$.binding_name],
    [$.literal_pattern, $.expression],
    [$.literal_pattern, $.nil],
    [$.literal_pattern, $.boolean],
    [$.binding_pattern, $.expression],
    [$.binding_pattern, $.variant_pattern],
    [$.variant_pattern, $.expression],
    [$.table_pattern, $.table_constructor],
    [$.rest_pattern, $.vararg],
    [$.match_statement, $.match_expression],
    [$.expression_statement, $.match_arm],
    [$.match_arm, $.index_expression],
    [$.match_arm],
    [$.do_block, $.match_arm],
    [$.repeat_loop, $.index_expression],
    [$.expression_statement, $.index_expression],
    [$.assignment, $.index_expression],
    [$.assignment, $.expression_statement, $.index_expression],
    [$.compound_assignment, $.index_expression],
    [$.local_declaration, $.index_expression],
    [$.const_declaration, $.index_expression],
    [$.global_declaration, $.index_expression],
    [$.return_statement, $.index_expression],
    [$.typed_binding, $.index_expression],
    [$.guard, $.index_expression],
    [$.if_statement, $.guard],
    [$.if_statement, $.guard, $.if_expression],
    [$.if_statement, $.guard, $.call_expression, $.if_expression],
    [$.binary_expression, $.contains_expression],
    [$.call_expression, $.await_expression],
    [$.index_expression, $.await_expression],
    [$.method_call_expression, $.await_expression],
    [$.try_expression, $.await_expression],
    [$.unwrap_expression, $.await_expression],
  ],

  // ── Rules ──────────────────────────────────────────────────────────────────

  rules: {
    // ── Top-level ───────────────────────────────────────────────────────────

    module: $ => seq(
      optional($.shebang),
      repeat($.statement),
    ),

    // `#!/usr/bin/env duo`. src/lexer.zig recognises `#!` only at index 0 and
    // so does this: `#` is the length operator everywhere else.
    shebang: $ => token(seq('#!', /[^\n]*/)),

    // ── Statements ──────────────────────────────────────────────────────────

    statement: $ => choice(
      $.local_declaration,
      $.const_declaration,
      $.global_declaration,
      $.assignment,
      $.compound_assignment,
      $.typed_binding,
      $.type_alias_definition,
      $.jai_type_definition,
      $.struct_definition,
      $.do_block,
      $.if_statement,
      $.while_loop,
      $.repeat_loop,
      $.numeric_for,
      $.generic_for,
      $.function_declaration,
      $.bare_function_declaration,
      $.foreign_declaration,
      $.return_statement,
      $.break_statement,
      $.goto_statement,
      $.label_statement,
      $.expression_statement,
      $.match_statement,
      $.try_statement,
      $.defer_statement,
      $.enum_definition,
      $.concept_definition,
      $.alias_definition,
      $.empty_statement,
    ),

    // Duo has no statement terminator, but `;` is a token (`semi`) and 16
    // tracked files use it to put two statements on one line.
    empty_statement: $ => ';',

    // ── Attributes ──────────────────────────────────────────────────────────

    // `@export`, `@ffi("puts")`, legacy c emit, `@comp.define.derive(…)`,
    // `@(expr)`.
    //
    // Two things were wrong here. The path was capped at TWO segments, so
    // `@comp.define.derive` and `@comp.embed.json` had no rule; and the
    // argument list was the raw regex `/[^)]*/`, which stops at the first `)`
    // it sees — so `@comp.assert(@comp.satisfies(point, "hasxy"), "…")` ended
    // mid-argument and every nested call was an error. Arguments are ordinary
    // expressions, which is what they are in the compiler too.
    attribute: $ => prec.right(choice(
      seq('@', $.attribute_path, optional(seq(
        '(',
        // A directive argument may be a whole function: 22 tracked files write
        // `@comp.define.derive("name", generate(meta) -> str … end)`, where the
        // second argument is a NAMED declaration, not an expression.
        commaSep(choice($.expression, $.bare_function_declaration, $.directive_function)),
        ')',
      ))),
      // @(expr) — compile-time evaluation
      seq('@', '(', $.expression, ')'),
    )),

    // `@comp.define.derive("printable", generate(type_info) … end)` — a
    // declaration with NO annotation anywhere, which GR-001 forbids in
    // statement position because it would make a declaration candidate out of
    // every ordinary call. Inside a directive's argument list that objection
    // does not apply: a call reading exists but cannot complete, because the
    // statements that follow are not arguments. So the rule is REACHABLE ONLY
    // HERE — it is not in `statement` and not in `expression` — and the
    // exclusion that protects 791 call sites is untouched.
    directive_function: $ => seq(
      field('name', $.function_name),
      '(',
      commaSep(choice($.parameter, $.vararg_parameter)),
      ')',
      optional(seq($._result_arrow, field('result', $.type))),
      repeat($.statement),
      'end',
    ),

    // Right-associative so the path is GREEDY: `@comp.type.name(x)` is one
    // three-segment directive, not `@comp` with a field access hanging off it.
    attribute_path: $ => prec.right(seq(
      $.identifier,
      repeat(seq('.', $.identifier)),
    )),

    // An attribute BINDS to the declaration it precedes wherever one follows;
    // where none does (legacy c emit on its own line) the same syntax is a
    // statement. Both readings exist in the corpus, so the list carries a
    // dynamic precedence and attachment wins when it is available at all.
    _attribute_list: $ => prec.dynamic(1, repeat1($.attribute)),

    // ── Local declaration ───────────────────────────────────────────────────

    local_declaration: $ => seq(
      optional($._attribute_list),
      'local',
      commaSep1($.binding_name),
      optional(seq(
        ':',
        $.type,
      )),
      optional(seq(
        '=',
        commaSep1($.expression),
      )),
    ),

    binding_name: $ => seq(
      optional($._attribute_list),
      $.identifier,
      optional(seq(':', field('type', $.type))),
    ),

    // ── Const declaration ───────────────────────────────────────────────────

    const_declaration: $ => seq(
      'const',
      $.identifier,
      optional(seq(':', $.type)),
      '=',
      $.expression,
    ),

    // ── Global declaration ──────────────────────────────────────────────────

    global_declaration: $ => seq(
      'global',
      choice(
        '*',
        commaSep1($.binding_name),
      ),
      optional(seq(
        '=',
        commaSep1($.expression),
      )),
    ),

    // ── Assignment ──────────────────────────────────────────────────────────

    assignment: $ => seq(
      commaSep1($.expression),
      '=',
      commaSep1($.expression),
    ),

    // ── Compound assignment ─────────────────────────────────────────────────
    //
    // `+= -= *= /= %= ^=` are six distinct token kinds in src/lexer.zig
    // (`plus_assign` … `caret_assign`) and this grammar had none of them, so
    // `sub -= 1` parsed as `sub -` followed by `= 1`.
    compound_assignment: $ => seq(
      $.expression,
      choice('+=', '-=', '*=', '/=', '%=', '^='),
      $.expression,
    ),

    // ── Do block ────────────────────────────────────────────────────────────

    do_block: $ => seq(
      'do',
      repeat($.statement),
      'end',
    ),

    // ── If statement ────────────────────────────────────────────────────────

    if_statement: $ => seq(
      'if',
      choice($.binding_condition, $.expression),
      optional('then'),
      repeat($.statement),
      repeat($.elseif_clause),
      optional($.else_clause),
      'end',
    ),

    elseif_clause: $ => seq(
      'elseif',
      choice($.binding_condition, $.expression),
      optional('then'),
      repeat($.statement),
    ),

    // ── Condition ───────────────────────────────────────────────────────────
    //
    // binding conditions stay projected because formatter and editor tooling
    // must recognise forms such as `found[i]` inside the value expression
    // instead of side-stepping bracketed indexing at the syntax boundary.
    binding_condition: $ => seq(
      commaSep1($.identifier),
      '=',
      $.expression,
    ),

    else_clause: $ => seq(
      'else',
      repeat($.statement),
    ),

    // ── While loop ──────────────────────────────────────────────────────────

    while_loop: $ => seq(
      'while',
      choice($.binding_condition, $.expression),
      optional('do'),
      repeat($.statement),
      'end',
    ),

    // ── Repeat loop ─────────────────────────────────────────────────────────

    repeat_loop: $ => seq(
      'repeat',
      repeat($.statement),
      'until',
      $.expression,
    ),

    // ── Numeric for ─────────────────────────────────────────────────────────

    numeric_for: $ => seq(
      'for',
      $.identifier,
      optional(seq(':', $.type)),
      '=',
      $.expression,
      ',',
      $.expression,
      optional(seq(',', $.expression)),
      optional('do'),
      repeat($.statement),
      'end',
    ),

    // ── Generic for ─────────────────────────────────────────────────────────

    generic_for: $ => seq(
      'for',
      commaSep1($.identifier),
      'in',
      commaSep1($.expression),
      optional('do'),
      repeat($.statement),
      'end',
    ),

    // ── Function declaration ────────────────────────────────────────────────

    function_declaration: $ => seq(
      optional($._attribute_list),
      optional('local'),
      choice('function', 'fun'),
      field('name', $.function_name),
      optional($.type_parameters),
      '(',
      commaSep($.parameter),
      optional(seq(',', '...')),
      ')',
      optional(seq($._result_arrow, $.type)),
      repeat($.statement),
      'end',
    ),

    type_parameters: $ => seq(
      '<',
      commaSep1($.type_parameter),
      '>',
    ),

    type_parameter: $ => seq(
      $.identifier,
      optional(seq(':', $.type, repeat(seq('+', $.type)))),
    ),

    function_name: $ => seq(
      $.identifier,
      repeat(seq('.', $.identifier)),
      optional(seq(':', $.identifier)),
    ),

    parameter: $ => seq(
      optional($._attribute_list),
      $.identifier,
      optional(seq(':', field('type', $.type))),
      optional(seq('=', $.expression)),
    ),

    // ── Bare function declaration ──────────────────────────────────────────

    bare_function_declaration: $ => prec.dynamic(3, seq(
      optional($._attribute_list),
      field('name', choice($.function_name, alias('type', $.identifier))),
      $._annotated_signature,
      repeat($.statement),
      'end',
    )),

    // ── Foreign or bodyless declaration ────────────────────────────────────

    foreign_declaration: $ => seq(
      $._attribute_list,
      field('name', $.function_name),
      $._annotated_signature,
    ),

    _annotated_signature: $ => choice(
      seq(
        '(',
        optional(seq(
          optional($._plain_parameter_prefix),
          choice(alias($._plain_parameter, $.parameter), $.vararg_parameter),
        )),
        ')',
        $._result_arrow,
        field('result', $.type),
      ),
      seq(
        '(',
        optional($._plain_parameter_prefix),
        alias($._typed_parameter, $.parameter),
        repeat(seq(',', choice($.parameter, $.vararg_parameter))),
        ')',
        optional(seq($._result_arrow, field('result', $.type))),
      ),
    ),

    _result_arrow: $ => choice(':', '->'),

    _plain_parameter_prefix: $ => repeat1(
      seq(alias($._plain_parameter, $.parameter), ','),
    ),

    _plain_parameter: $ => seq(
      optional($._attribute_list),
      $.identifier,
    ),

    _typed_parameter: $ => seq(
      optional($._attribute_list),
      $.identifier,
      ':',
      field('type', $.type),
      optional(seq('=', $.expression)),
    ),

    vararg_parameter: $ => seq(
      '...',
      optional($.identifier),
    ),

    // ── Return ──────────────────────────────────────────────────────────────

    return_statement: $ => prec.right(seq(
      'return',
      optional(commaSep1($.expression)),
    )),

    // ── Break ───────────────────────────────────────────────────────────────

    break_statement: $ => 'break',

    // ── Goto ────────────────────────────────────────────────────────────────

    goto_statement: $ => seq(
      'goto',
      $.identifier,
    ),

    label_statement: $ => seq(
      '::',
      $.identifier,
      '::',
    ),

    // ── Expression statement ────────────────────────────────────────────────

    expression_statement: $ => commaSep1($.expression),

    // ── Match statement ─────────────────────────────────────────────────────

    match_statement: $ => seq(
      'match',
      $.expression,
      repeat($.match_arm),
      'end',
    ),

    match_arm: $ => choice(
      seq(
        'case',
        $.pattern,
        optional($.guard),
        optional(choice('then', 'do')),
        repeat($.statement),
        optional('end'),
      ),
      seq('else', repeat($.statement), optional('end')),
      seq(
        $.pattern,
        optional($.guard),
        '=>',
        choice(
          $.expression,
          seq(repeat($.statement), 'end'),
        ),
      ),
    ),

    guard: $ => seq(
      'if',
      $.expression,
    ),

    // ── Pattern ─────────────────────────────────────────────────────────────

    pattern: $ => choice(
      $.literal_pattern,
      $.binding_pattern,
      $.variant_pattern,
      $.table_pattern,
      $.array_pattern,
      $.rest_pattern,
      '_',
    ),

    literal_pattern: $ => choice(
      $.number,
      $.string,
      'true',
      'false',
      'nil',
    ),

    binding_pattern: $ => seq(
      $.identifier,
      optional(seq(':', $.type)),
    ),

    variant_pattern: $ => seq(
      $.identifier,
      '(',
      commaSep($.pattern),
      ')',
    ),

    table_pattern: $ => seq(
      '{',
      commaSep($.table_pattern_entry),
      '}',
    ),

    table_pattern_entry: $ => seq(
      $.identifier,
      '=',
      $.pattern,
    ),

    array_pattern: $ => seq(
      '[',
      commaSep($.pattern),
      ']',
    ),

    rest_pattern: $ => seq(
      '...',
      $.identifier,
    ),

    // ── Try statement ───────────────────────────────────────────────────────

    try_statement: $ => seq(
      'try',
      repeat($.statement),
      repeat($.catch_clause),
      optional($.defer_statement),
      'end',
    ),

    catch_clause: $ => seq(
      'catch',
      optional($.identifier),
      repeat($.statement),
    ),

    // ── Defer statement ─────────────────────────────────────────────────────

    defer_statement: $ => seq(
      'defer',
      repeat($.statement),
      'end',
    ),

    // ── Enum definition ─────────────────────────────────────────────────────

    enum_definition: $ => seq(
      optional($._attribute_list),
      'enum',
      $.identifier,
      optional($.type_parameters),
      repeat($.enum_variant),
      'end',
    ),

    enum_variant: $ => seq(
      $.identifier,
      optional(seq(
        '(',
        commaSep1($.enum_field),
        ')',
      )),
    ),

    enum_field: $ => seq(
      optional(seq($.identifier, ':')),
      $.type,
    ),

    // ── Concept definition ──────────────────────────────────────────────────

    concept_definition: $ => seq(
      optional($._attribute_list),
      'concept',
      $.identifier,
      optional($.type_parameters),
      repeat(choice(
        $.concept_method,
        $.concept_field,
      )),
      'end',
    ),

    concept_method: $ => seq(
      $.identifier,
      '(',
      commaSep($.parameter),
      ')',
      $._result_arrow,
      $.type,
    ),

    concept_field: $ => seq(
      $.identifier,
      ':',
      $.type,
    ),

    // ── Alias definition ────────────────────────────────────────────────────

    alias_definition: $ => seq(
      optional($._attribute_list),
      'alias',
      $.identifier,
      choice(
        seq('=', $.type),
        seq(
          optional(seq('extends', $.identifier)),
          repeat($.alias_member),
          'end',
        ),
      ),
    ),

    // ── Jai-like type definition ────────────────────────────────────────────

    jai_type_definition: $ => seq(
      optional($._attribute_list),
      $.identifier,
      ':',
      $.record_type,
    ),

    type_alias_definition: $ => seq(
      optional($._attribute_list),
      choice(
        seq($.identifier, ':', $.type),
        seq('type', $.identifier, '=', $.type),
      ),
    ),

    // ── Typed binding (name: Type = expr) ───────────────────────────────────

    typed_binding: $ => seq(
      optional($._attribute_list),
      $.identifier,
      ':',
      $.type,
      '=',
      $.expression,
    ),

    // ── Struct definition (Name = struct ... end) ────────────────────────────

    struct_definition: $ => seq(
      optional($._attribute_list),
      $.identifier,
      '=',
      'struct',
      repeat($.struct_field),
      'end',
    ),

    struct_field: $ => seq(
      $.identifier,
      optional(seq(':', $.type)),
      optional(seq('=', $.expression)),
    ),

    alias_member: $ => choice(
      $.alias_field,
      $.function_declaration,
    ),

    alias_field: $ => seq(
      optional('private'),
      $.identifier,
      ':',
      $.type,
      optional(seq('=', $.expression)),
    ),

    // ── Types ───────────────────────────────────────────────────────────────

    type: $ => choice(
      $.named_type,
      $.array_type,
      $.pointer_type,
      $.optional_type,
      $.generic_type,
      $.function_type,
      $.record_type,
      $.tuple_type,
      $.pack_type,
      $.applied_type,
      $.attributed_type,
      $.attribute,
    ),

    tuple_type: $ => seq(
      '(',
      commaSep1($.type),
      ')',
    ),

    pack_type: $ => prec.left(seq(
      $.type,
      '|',
      $.type,
    )),

    applied_type: $ => seq(
      $.identifier,
      '(',
      commaSep1($.type),
      ')',
    ),

    attributed_type: $ => prec.left(seq(
      $.type,
      repeat1(seq('&', $.type_attribute)),
    )),

    type_attribute: $ => seq(
      $.identifier,
      optional(seq('(', commaSep($.expression), ')')),
    ),

    named_type: $ => $.identifier,

    array_type: $ => choice(
      seq('[', optional($.number), ']', $.type),
      seq('[', $.type, ']'),
    ),

    pointer_type: $ => seq(
      '*',
      $.type,
    ),

    optional_type: $ => seq(
      '?',
      $.type,
    ),

    generic_type: $ => choice(
      seq($.identifier, '<', commaSep1($.type), '>'),
      seq($.identifier, '[', commaSep1(choice($.type, $.number)), ']'),
    ),

    function_type: $ => seq(
      '(',
      commaSep($.type),
      ')',
      '->',
      $.type,
    ),

    record_type: $ => seq(
      optional('@'),
      '{',
      sepBy(choice($.record_slot, $.record_field, $.spread_entry)),
      '}',
    ),

    record_slot: $ => seq(
      $.identifier,
      '=',
      $.lambda_expression,
    ),

    record_field: $ => seq(
      $.identifier,
      optional(seq(':', $.type)),
    ),

    // ── Expressions ─────────────────────────────────────────────────────────

    expression: $ => choice(
      $.nil,
      $.boolean,
      $.number,
      $.string,
      $.vararg,
      $.anchor_expression,
      $.builtinname,
      $.identifier,
      $.binary_expression,
      $.unary_expression,
      $.function_expression,
      $.function_value_expression,
      $.lambda_expression,
      $.table_constructor,
      $.descriptor_constructor,
      $.attribute,
      $.field_projection,
      $.index_expression,
      $.field_expression,
      $.semantic_field_expression,
      $.call_expression,
      $.method_call_expression,
      $.try_expression,
      $.unwrap_expression,
      $.match_expression,
      $.if_expression,
      $.await_expression,
      $.contains_expression,
      $.parenthesized_expression,
    ),

    anchor_expression: $ => '@',

    // ── Function expression ─────────────────────────────────────────────────

    function_expression: $ => seq(
      choice('function', 'fun'),
      optional($.identifier),
      '(',
      commaSep($.parameter),
      optional(seq(',', '...')),
      ')',
      optional(seq($._result_arrow, $.type)),
      repeat($.statement),
      'end',
    ),

    // ── Function value ──────────────────────────────────────────────────────

    function_value_expression: $ => choice(
      seq($._annotated_signature, repeat($.statement), 'end'),
      prec.dynamic(-1, seq('(', ')', repeat($.statement), 'end')),
    ),

    // ── Expression-body function value ──────────────────────────────────────

    lambda_expression: $ => prec.dynamic(-1, seq(
      '(',
      commaSep(choice($.parameter, $.vararg_parameter)),
      ')',
      optional(seq($._result_arrow, field('result', $.type))),
      field('body', $.expression),
    )),

    // ── Table constructor ───────────────────────────────────────────────────

    table_constructor: $ => seq(
      '{',
      sepBy(choice($.table_entry, $.spread_entry)),
      '}',
    ),

    table_entry: $ => choice(
      seq(choice($.identifier, $.builtinname, $.string), '=', $.expression),
      seq($.identifier, ':', field('type', $.type), '=', $.expression),
      seq('[', $.expression, ']', '=', $.expression),
      $.expression,
    ),

    // ── Field projection / method reference ─────────────────────────────────

    field_projection: $ => prec(-1, seq('.', $.identifier)),

    // ── Descriptor constructor ──────────────────────────────────────────────

    descriptor_constructor: $ => seq(
      '@',
      '{',
      sepBy(choice($.table_entry, $.spread_entry)),
      '}',
    ),

    spread_entry: $ => seq('..', $.expression),

    // ── Postfix expressions ─────────────────────────────────────────────────

    index_expression: $ => seq(
      $.expression,
      '[',
      $.expression,
      ']',
    ),

    field_expression: $ => prec(1, seq(
      $.expression,
      '.',
      choice($.identifier, alias('type', $.identifier)),
    )),

    semantic_field_expression: $ => prec(1, seq(
      $.expression,
      '.',
      '@',
      $.identifier,
    )),

    call_expression: $ => prec.dynamic(1, seq(
      $.expression,
      choice(
        seq('(', commaSep($.expression), ')'),
        $.string,
        $.table_constructor,
      ),
    )),

    method_call_expression: $ => seq(
      $.expression,
      ':',
      $.identifier,
      '(',
      commaSep($.expression),
      ')',
    ),

    // ── Try/unwrap expressions ──────────────────────────────────────────────

    try_expression: $ => seq(
      $.expression,
      '?',
    ),

    unwrap_expression: $ => seq(
      $.expression,
      '!',
    ),

    // ── Match expression ────────────────────────────────────────────────────

    match_expression: $ => seq(
      'match',
      $.expression,
      repeat($.match_arm),
      'end',
    ),

    if_expression: $ => prec.right(seq(
      'if',
      field('condition', $.expression),
      field('consequence', $.expression),
      'else',
      field('alternative', $.expression),
      optional('end'),
    )),

    // ── Await expression ────────────────────────────────────────────────────

    await_expression: $ => seq(
      'await',
      $.expression,
    ),

    // ── Contains expression ─────────────────────────────────────────────────

    contains_expression: $ => seq(
      $.expression,
      'in',
      $.expression,
    ),

    // ── Parenthesized ───────────────────────────────────────────────────────

    parenthesized_expression: $ => seq(
      '(',
      $.expression,
      ')',
    ),

    nil: $ => 'nil',

    boolean: $ => choice('true', 'false'),

    number: $ => choice(
      $.integer,
      $.float,
    ),

    integer: $ => token(choice(
      /[0-9]+/,
      /0x[0-9a-fA-F]+/,
    )),

    float: $ => token(choice(
      /[0-9]+\.[0-9]+([eE][+-]?[0-9]+)?/,
      /[0-9]+[eE][+-]?[0-9]+/,
    )),

    string: $ => choice(
      $.double_quoted_string,
      $.single_quoted_string,
      $.long_string,
    ),

    double_quoted_string: $ => token(seq(
      '"',
      repeat(choice(
        /[^"\\]+/,
        /\\./,
      )),
      '"',
    )),

    single_quoted_string: $ => token(seq(
      "'",
      repeat(choice(
        /[^'\\]+/,
        /\\./,
      )),
      "'",
    )),

    // The body was `/[^]]*/` — "no `]` at all" — so a long string containing
    // an index expression (`a[i]`) or a C statement ended at the first `]` and
    // took the rest of the file with it. A `]` is body text unless the NEXT
    // character is also `]`, which is the closing delimiter. Stated as an
    // alternation rather than a lookahead because tree-sitter's token DFA has
    // none; it stays non-greedy across two long strings in one file precisely
    // because `]]` can never be consumed as body.
    //
    // ONE ALTERNATIVE PER LEVEL, and the GENERATOR writes them now. A single
    // token DFA cannot remember how many `=` it opened with, so each body is
    // "any character, or a `]` run shorter than MY closer" — a function of the
    // level, and previously three lines that had to be checked by eye.
    // Levels 0 and 1 are what the corpus uses (108 `[[` and 1 `[=[`); level 2
    // is here so the next one does not reopen this.
    long_string: $ => token(choice(
      seq('[[', repeat(choice(/[^\]]/, /\][^\]]/)), ']]'),
      seq('[=[', repeat(choice(/[^\]]/, /\][^=]/, /\]=[^\]]/)), ']=]'),
      seq('[==[', repeat(choice(/[^\]]/, /\][^=]/, /\]=[^=]/, /\]==[^\]]/)), ']==]'),
    )),

    vararg: $ => '...',

    builtinname: $ => alias('type', $.identifier),

    identifier: $ => /[a-zA-Z_][a-zA-Z0-9_]*/,

    // ── Binary operators ──────────────────────────────────────────────

    binary_expression: $ => choice(
      prec.left(3, seq($.expression, 'or', $.expression)),
      prec.left(4, seq($.expression, 'and', $.expression)),
      prec.left(5, seq($.expression, '<', $.expression)),
      prec.left(5, seq($.expression, '>', $.expression)),
      prec.left(5, seq($.expression, '<=', $.expression)),
      prec.left(5, seq($.expression, '>=', $.expression)),
      prec.left(5, seq($.expression, '~=', $.expression)),
      // `!=` is the SAME token as `~=` in src/lexer.zig (both lex to `.neq`),
      // and it is the spelling 271 tracked files actually use. Without it
      // `a != nil` lexed as an unwrap_expression `a!` followed by `= nil`.
      prec.left(5, seq($.expression, '!=', $.expression)),
      prec.left(5, seq($.expression, '==', $.expression)),
      prec.left(5, seq($.expression, 'in', $.expression)),
      prec.left(7, seq($.expression, '|', $.expression)),
      // `&` (amp) and binary `~` (xor) are in the lexer's token table and were
      // not in this one; `|` alone was.
      prec.left(8, seq($.expression, '&', $.expression)),
      prec.left(7, seq($.expression, '~', $.expression)),
      prec.left(9, seq($.expression, '<<', $.expression)),
      prec.left(9, seq($.expression, '>>', $.expression)),
      prec.left(2, seq($.expression, '|>', $.expression)),
      prec.left(6, seq($.expression, '..', $.expression)),
      prec.left(10, seq($.expression, '+', $.expression)),
      prec.left(10, seq($.expression, '-', $.expression)),
      prec.left(11, seq($.expression, '*', $.expression)),
      prec.left(11, seq($.expression, '/', $.expression)),
      prec.left(11, seq($.expression, '//', $.expression)),
      prec.left(11, seq($.expression, '%', $.expression)),
      prec.right(13, seq($.expression, '^', $.expression)),
    ),

    // ── Unary operators ───────────────────────────────────────────────

    // Unary binds tighter than every binary operator except `^`, which is what
    // `-a^b` meaning `-(a^b)` requires. Its level is one below `^` and one
    // above `*`, and it moves with them because it is in the same table.
    unary_expression: $ => choice(
      prec(12, seq('not', $.expression)),
      prec(12, seq('#', $.expression)),
      prec(12, seq('##', $.expression)),
      prec(12, seq('comptime', $.expression)),
      prec(12, seq('-', $.expression)),
      prec(12, seq('~', $.expression)),
    ),

    // ── Comments ───────────────────────────────────────────────────

    comment: $ => token(choice(
      seq('--', /[^\n]*/),
      seq('--', '[', repeat('='), '[',
          repeat(choice(/[^\]]/, seq(']', /[^\]]/))),
          ']', repeat('='), ']'),
    )),
  },
});

// ── Helpers ────────────────────────────────────────────────────────────────────────────

function commaSep(rule) {
  return optional(commaSep1(rule));
}

function commaSep1(rule) {
  return seq(rule, repeat(seq(',', rule)));
}

// The NEWLINE is the canonical separator inside a braced group
// and the comma is the optional one. `extras` already consumes the newline, so
// "optional comma between elements, optional trailing comma" is the whole rule.
function sepBy(rule) {
  return optional(seq(rule, repeat(seq(optional(','), rule)), optional(',')));
}
