; highlights.scm — GENERATED from the role taxonomy in
; tools/lsp/src/highlight.duo. Do not edit this file by hand.
;
;     hlmode=scm duo run tools/lsp/src/highlight.duo
;
; CLAUDE.md §0d: highlights.scm and the LSP legend are GENERATED from the
; graph service; a hand edit is an H-1 drift finding. The taxonomy is the
; source of truth and this file is a LOSSY projection of it. Three losses,
; all counted by `zig build highlight-corpus` rather than hidden here:
;
;   1. tree-sitter sees ONE node for `:` and ONE for `|`, so the four roles
;      H-1 names collapse to two captures. That is the baseline this whole
;      artifact exists to beat, and the golden corpus is what convicts it.
;   2. the fine splits of §0g have no capture vocabulary at all — a card is
;      not expressible here, so `strata`, `param` and `group` parens are
;      one capture and specificity through this front-end is lower than
;      the projection's.
;   3. there is no external scanner in ext/tree-sitter-duo/src, so there is
;      no offside layer — see scripts/treesitter_emit.duo.
;
; role -> capture -> github dark (Primer) colour:
;   keyword @keyword #ff7b72
;   copula @keyword.operator #ff7b72
;   operator @operator #ff7b72
;   layout @punctuation.bracket #8b949e
;   descriptor @type #ffa657
;   union @punctuation.special #ffa657
;   anchor @attribute #ffa657
;   retrieve @punctuation.bracket #ffa657
;   invoke @function.method #d2a8ff
;   callable @function #d2a8ff
;   world @function.builtin #d2a8ff
;   foreign @string.special #d2a8ff
;   place @variable #79c0ff
;   number @number #79c0ff
;   literal @string #79c0ff
;   case @constant.builtin #79c0ff
;   comment @comment #8b949e
;   walk @property #7ee787
;   pipe @operator #7ee787

[
  "if"
  "then"
  "else"
  "elseif"
  "while"
  "for"
  "in"
  "do"
  "end"
  "and"
  "or"
  "not"
  "return"
  "break"
  "repeat"
  "until"
  "use"
  "local"
  "global"
  "const"
  "function"
  "fun"
  "goto"
  "match"
  "case"
  "catch"
  "try"
  "defer"
  "await"
  "enum"
  "concept"
  "alias"
  "extends"
  "private"
  "comptime"
] @keyword

[
  "nil"
  "true"
  "false"
] @constant.builtin

(identifier) @variable
(named_type) @type
(generic_type) @type
(array_type) @type
(pointer_type) @type
(optional_type) @type
(function_type) @type
(record_type) @type
(binding_name type: (type) @type)
(parameter type: (type) @type)
(type_parameter (identifier) @type)
(enum_definition (identifier) @type)
(concept_definition (identifier) @type)
(alias_definition (identifier) @type)
(integer) @number
(float) @number
(nil) @constant.builtin
(boolean) @constant.builtin
(enum_variant (identifier) @constant.builtin)
(double_quoted_string) @string
(single_quoted_string) @string
(long_string) @string
(function_declaration name: (function_name) @function)
(bare_function_declaration name: (function_name) @function)
(foreign_declaration name: (function_name) @function)
(function_expression) @function
(function_value_expression) @function
(parameter (identifier) @variable)
(binding_pattern (identifier) @variable)
(rest_pattern (identifier) @variable)
(label_statement (identifier) @variable)
(goto_statement (identifier) @variable)
(field_expression (identifier) @property)
(field_projection (identifier) @property)
(table_entry . (identifier) @property)
(table_pattern_entry (identifier) @property)
(descriptor_constructor) @attribute
(attribute) @attribute
(vararg) @punctuation.bracket
(empty_statement) @punctuation.bracket
(shebang) @comment
(break_statement) @keyword
(compound_assignment) @operator
(unary_expression) @operator
(binary_expression) @operator

(comment) @comment @spell

[
  "(" ")"
] @punctuation.bracket

[
  "," "."
] @punctuation.bracket

[
  "[" "]"
] @punctuation.bracket

; THE H-1 HOLE, stated where an editor author will read it. `:` is ONE
; node to this grammar and so is `|`, so the four roles H-1 names —
; copula/invoke and union/pipe — cannot be separated by any query written
; here. The projection separates them and the golden corpus proves it;
; this front-end cannot carry the answer. That gap IS the measurement.
":" @keyword.operator
"|" @punctuation.special

[
  "+" "-" "*" "/" "%" "^" "#"
  "==" "<" ">" "<=" ">=" "~=" "!="
  "<<" ">>" "&" "~" "=" ".."
] @operator

[
  "and" "or" "not" "in"
] @keyword

