#!/usr/bin/env bash
set -euo pipefail

echo "[Property 12] Testing bitwise correctness..."

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TMP_DIR="$(mktemp -d /tmp/duo-prop12.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

DUO_SRC="$TMP_DIR/prop12.duo"
C_SRC="$TMP_DIR/prop12.c"
C_BIN="$TMP_DIR/prop12_c"
DUO_OUT="$TMP_DIR/duo.out"
C_OUT="$TMP_DIR/c.out"

cat > "$DUO_SRC" <<'DUO'
-- Generated by scripts/test_property_12.sh.
DUO

cat > "$C_SRC" <<'C'
#include <stdint.h>
#include <stdio.h>

int main(void) {
C

seed=305419896
next_rand() {
    seed=$(( (seed * 1103515245 + 12345) & 0x7fffffff ))
    printf '%d' "$seed"
}

for i in $(seq 0 63); do
    ra=$(next_rand)
    rb=$(next_rand)
    a=$(( ra - 1073741824 ))
    b=$(( rb - 1073741824 ))
    shift=$(( rb & 31 ))
    positive=$(( ra & 1048575 ))

    cat >> "$DUO_SRC" <<DUO
local a${i}: i64 = ${a}
local b${i}: i64 = ${b}
local s${i}: i64 = ${shift}
local p${i}: i64 = ${positive}
print(a${i} & b${i})
print(a${i} | b${i})
print(a${i} ~ b${i})
print(~a${i})
print(p${i} << s${i})
print(p${i} >> s${i})
DUO

    cat >> "$C_SRC" <<C
    int64_t a${i} = ${a}LL;
    int64_t b${i} = ${b}LL;
    int64_t s${i} = ${shift}LL;
    int64_t p${i} = ${positive}LL;
    printf("%lld\n", (long long)(a${i} & b${i}));
    printf("%lld\n", (long long)(a${i} | b${i}));
    printf("%lld\n", (long long)(a${i} ^ b${i}));
    printf("%lld\n", (long long)(~a${i}));
    printf("%lld\n", (long long)(p${i} << s${i}));
    printf("%lld\n", (long long)(p${i} >> s${i}));
C
done

cat >> "$C_SRC" <<'C'
    return 0;
}
C

"$ROOT/zig-out/bin/duo" run "$DUO_SRC" > "$DUO_OUT"
if [[ "$(uname)" == "Darwin" ]]; then
    xcrun clang -Wall -Wextra -pedantic -std=c11 "$C_SRC" -o "$C_BIN"
else
    clang -Wall -Wextra -pedantic -std=c11 "$C_SRC" -o "$C_BIN"
fi
"$C_BIN" > "$C_OUT"

diff -u "$C_OUT" "$DUO_OUT"
echo "[Property 12] SUCCESS"
