[book]
description = "A Lua-like language that compiles to native C with optional static typing"
authors = ["Chris Pecunies"]
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"

[output.html.search]
enable = true
