/// C code generator.
///
/// Strategy:
///   • Fully-typed functions (FuncBody.is_typed == true) → pure C functions.
///   • Everything else    → calls routed through the duo Lua runtime shim.
///   • `print(x)` with a typed x is mapped to printf/puts directly.
///   • `math.*` for typed numerics maps to <math.h>.
///
/// The emitted file is a valid, self-contained C99 program ready for
///   clang -O3 -o <out> <file>.c -lm
const std = @import("std");
const Allocator = std.mem.Allocator;
const ast = @import("ast.zig");
const types = @import("types.zig");
const RT = types.ResolvedType;
const sema = @import("sema.zig");

pub const CodeGenError = error{
    Unsupported,
    InternalError,
} || Allocator.Error || std.Io.Writer.Error;

const E = Allocator.Error || std.Io.Writer.Error;

const W = *std.Io.Writer;

pub const CodeGen = struct {
    alloc: Allocator,
    type_map: *sema.TypeMap,
    indent: u32,
    w: W,
    current_ret: RT = .void,

    pub fn init(alloc: Allocator, type_map: *sema.TypeMap, w: W) CodeGen {
        return .{ .alloc = alloc, .type_map = type_map, .indent = 0, .w = w, .current_ret = .void };
    }

    fn ind(self: *CodeGen) void {
        var i: u32 = 0;
        while (i < self.indent) : (i += 1) self.w.writeAll("    ") catch {};
    }

    fn p(self: *CodeGen, comptime fmt: []const u8, args: anytype) void {
        self.w.print(fmt, args) catch {};
    }

    fn pl(self: *CodeGen, comptime fmt: []const u8, args: anytype) void {
        self.ind();
        self.w.print(fmt ++ "\n", args) catch {};
    }

    fn nl(self: *CodeGen) void { self.w.writeByte('\n') catch {}; }

    fn typ(self: *CodeGen, rt: RT) void {
        var buf: [128]u8 = undefined;
        self.p("{s}", .{rt.c_type(&buf)});
    }

    fn expr_type(self: *CodeGen, e: *const ast.Expr) RT {
        return self.type_map.get(e) orelse .any;
    }

    // ── Module entry ──────────────────────────────────────────────────────────

    pub fn emit_module(self: *CodeGen, mod: *ast.Module) E!void {
        // File header
        self.p("/* Generated by duo compiler — do not edit */\n", .{});
        self.p("#define _XOPEN_SOURCE 600\n", .{});
        self.p("#include <stdint.h>\n", .{});
        self.p("#include <stdbool.h>\n", .{});
        self.p("#include <stdio.h>\n", .{});
        self.p("#include <stdlib.h>\n", .{});
        self.p("#include <string.h>\n", .{});
        self.p("#include <math.h>\n", .{});
        self.p("#include <time.h>\n", .{});
        self.p("#include <ctype.h>\n", .{});
        self.p("#include <ucontext.h>\n", .{});
        self.nl();
        self.p("{s}", .{duo_runtime});
        self.nl();

        // Emit top-level constants
        for (mod.body.stmts) |*stmt| {
            if (stmt.* == .const_decl) {
                const cd = &stmt.const_decl;
                const rt = if (cd.typ != .inferred)
                    types.resolve(cd.typ, self.alloc) catch .any
                else
                    self.expr_type(cd.val);
                self.p("static const ", .{});
                self.typ(rt);
                self.p(" {s} = ", .{cd.ident});
                try self.emit_expr(cd.val);
                self.p(";\n", .{});
            }
        }
        self.nl();

        // Forward-declare top-level functions
        for (mod.body.stmts) |*stmt| {
            if (stmt.* == .func_decl) {
                const fd = &stmt.func_decl;
                if (fd.path.len == 1 and !fd.method) {
                    try self.emit_func_decl_forward(fd);
                }
            }
        }
        self.nl();

        // Emit struct definitions
        for (mod.body.stmts) |*stmt| {
            if (stmt.* == .struct_def) try self.emit_struct_def(&stmt.struct_def);
        }

        // Emit function definitions
        for (mod.body.stmts) |*stmt| {
            if (stmt.* == .func_decl) {
                const fd = &stmt.func_decl;
                try self.emit_func_def(fd);
            }
        }

        // Emit main()
        self.p("int main(void) {{\n", .{});
        self.indent = 1;
        self.pl("package = lua_package_init();", .{});
        self.pl("math = lua_math_init();", .{});
        self.pl("utf8 = lua_utf8_init();", .{});
        self.pl("debug = lua_debug_init();", .{});

        // Emit top-level statements (except function/struct/const definitions)
        for (mod.body.stmts) |*stmt| {
            switch (stmt.*) {
                .func_decl, .struct_def, .const_decl => {},
                else => try self.emit_stmt(stmt),
            }
        }

        self.pl("return 0;", .{});
        self.indent = 0;
        self.p("}}\n", .{});
    }

    // ── Struct ────────────────────────────────────────────────────────────────

    fn emit_struct_def(self: *CodeGen, sd: *const ast.StructDefPayload) E!void {
        self.p("typedef struct {{\n", .{});
        for (sd.fields) |f| {
            self.p("    ", .{});
            const rt = types.resolve(f.typ, self.alloc) catch .any;
            self.typ(rt);
            self.p(" {s};\n", .{f.name});
        }
        self.p("}} duo_{s};\n\n", .{sd.name});
    }

    // ── Functions ─────────────────────────────────────────────────────────────

    fn emit_func_decl_forward(self: *CodeGen, fd: *const ast.FuncDecl) E!void {
        const fb = &fd.func;
        const ret = types.resolve(fb.ret_type, self.alloc) catch .any;
        self.p("static ", .{});
        self.typ(ret);
        self.p(" {s}(", .{fd.path[0]});
        for (fb.params, 0..) |*par, i| {
            if (i > 0) self.p(", ", .{});
            const pt = types.resolve(par.typ, self.alloc) catch .any;
            self.typ(pt);
            self.p(" {s}", .{par.name});
        }
        self.p(");\n", .{});
    }

    fn emit_func_def(self: *CodeGen, fd: *const ast.FuncDecl) E!void {
        const fb = &fd.func;
        const ret = types.resolve(fb.ret_type, self.alloc) catch .any;
        const prev_ret = self.current_ret;
        self.current_ret = ret;
        defer self.current_ret = prev_ret;
        self.p("static ", .{});
        self.typ(ret);
        // Build full name from path
        for (fd.path, 0..) |part, i| {
            if (i == 0) self.p(" {s}", .{part})
            else self.p("__{s}", .{part});
        }
        self.p("(", .{});
        for (fb.params, 0..) |*par, i| {
            if (i > 0) self.p(", ", .{});
            const pt = types.resolve(par.typ, self.alloc) catch .any;
            self.typ(pt);
            self.p(" {s}", .{par.name});
        }
        self.p(") {{\n", .{});
        self.indent = 1;
        try self.emit_block(&fb.body);
        self.indent = 0;
        self.p("}}\n\n", .{});
    }

    // ── Block / statements ────────────────────────────────────────────────────

    fn emit_block(self: *CodeGen, blk: *const ast.Block) E!void {
        for (blk.stmts) |*stmt| try self.emit_stmt(stmt);
    }

    fn emit_stmt(self: *CodeGen, stmt: *const ast.Stmt) E!void {
        switch (stmt.*) {
            .local_decl => |*ld| {
                for (ld.names, 0..) |*lname, i| {
                    self.ind();
                    // Determine type
                    const rt: RT = blk: {
                        if (lname.typ != .inferred) {
                            break :blk types.resolve(lname.typ, self.alloc) catch .any;
                        }
                        if (i < ld.inits.len) {
                            break :blk self.expr_type(ld.inits[i]);
                        }
                        break :blk .any;
                    };
                    if (rt == .any) {
                        self.p("lua_Value {s}", .{lname.ident});
                        if (i < ld.inits.len) {
                            self.p(" = ", .{});
                            try self.emit_as_lua_value(ld.inits[i]);
                        }
                    } else {
                        self.typ(rt);
                        self.p(" {s}", .{lname.ident});
                        if (i < ld.inits.len) {
                            self.p(" = ", .{});
                            try self.emit_expr(ld.inits[i]);
                        }
                    }
                    self.p(";\n", .{});
                }
            },
            .const_decl => |*cd| {
                self.ind();
                const rt = if (cd.typ != .inferred)
                    types.resolve(cd.typ, self.alloc) catch .any
                else
                    self.expr_type(cd.val);
                self.p("const ", .{});
                self.typ(rt);
                self.p(" {s} = ", .{cd.ident});
                try self.emit_expr(cd.val);
                self.p(";\n", .{});
            },
            .assign => |*as| {
                for (as.targets, 0..) |tgt, i| {
                    self.ind();
                    const tt = self.expr_type(tgt);
                    
                    var is_table_assign = false;
                    if (tgt.* == .field) {
                        const f = &tgt.field;
                        if (self.expr_type(f.obj) == .any) {
                            is_table_assign = true;
                            self.p("lua_table_set(", .{});
                            try self.emit_expr(f.obj);
                            self.p(", lua_val_from_str(\"{s}\"), ", .{f.field});
                            if (i < as.values.len) try self.emit_as_lua_value(as.values[i])
                            else self.p("lua_val_nil()", .{});
                            self.p(");\n", .{});
                        }
                    } else if (tgt.* == .index) {
                        const idx = &tgt.index;
                        if (self.expr_type(idx.obj) == .any) {
                            is_table_assign = true;
                            self.p("lua_table_set(", .{});
                            try self.emit_expr(idx.obj);
                            self.p(", ", .{});
                            try self.emit_as_lua_value(idx.key);
                            self.p(", ", .{});
                            if (i < as.values.len) try self.emit_as_lua_value(as.values[i])
                            else self.p("lua_val_nil()", .{});
                            self.p(");\n", .{});
                        }
                    }

                    if (!is_table_assign) {
                        try self.emit_expr(tgt);
                        self.p(" = ", .{});
                        if (i < as.values.len) {
                            if (tt == .any) {
                                try self.emit_as_lua_value(as.values[i]);
                            } else {
                                try self.emit_expr(as.values[i]);
                            }
                        } else {
                            self.p("0", .{});
                        }
                        self.p(";\n", .{});
                    }
                }
            },
            .call_stmt => |*cs| {
                self.ind();
                // Special-case print(...)
                if (cs.expr.* == .call) {
                    const c = &cs.expr.call;
                    if (c.func.* == .name and std.mem.eql(u8, c.func.name.ident, "print")) {
                        try self.emit_print_call(c.args);
                        return;
                    }
                }
                try self.emit_expr(cs.expr);
                self.p(";\n", .{});
            },
            .ret => |*r| {
                self.ind();
                if (r.vals.len == 0) {
                    self.p("return;\n", .{});
                } else {
                    self.p("return ", .{});
                    if (self.current_ret == .any) {
                        try self.emit_as_lua_value(r.vals[0]);
                    } else {
                        try self.emit_expr(r.vals[0]);
                    }
                    self.p(";\n", .{});
                }
            },
            .if_stmt => |*is| {
                self.ind();
                self.p("if (", .{});
                if (self.expr_type(is.cond) == .any) {
                    self.p("lua_to_bool(", .{});
                    try self.emit_expr(is.cond);
                    self.p(")", .{});
                } else {
                    try self.emit_expr(is.cond);
                }
                self.p(") {{\n", .{});
                self.indent += 1;
                try self.emit_block(&is.then);
                self.indent -= 1;
                for (is.elseifs) |*ei| {
                    self.ind();
                    self.p("}} else if (", .{});
                    if (self.expr_type(ei.cond) == .any) {
                        self.p("lua_to_bool(", .{});
                        try self.emit_expr(ei.cond);
                        self.p(")", .{});
                    } else {
                        try self.emit_expr(ei.cond);
                    }
                    self.p(") {{\n", .{});
                    self.indent += 1;
                    try self.emit_block(&ei.body);
                    self.indent -= 1;
                }
                if (is.else_body) |*eb| {
                    self.ind();
                    self.p("}} else {{\n", .{});
                    self.indent += 1;
                    try self.emit_block(eb);
                    self.indent -= 1;
                }
                self.pl("}}", .{});
            },
            .while_loop => |*wl| {
                self.ind();
                self.p("while (", .{});
                if (self.expr_type(wl.cond) == .any) {
                    self.p("lua_to_bool(", .{});
                    try self.emit_expr(wl.cond);
                    self.p(")", .{});
                } else {
                    try self.emit_expr(wl.cond);
                }
                self.p(") {{\n", .{});
                self.indent += 1;
                try self.emit_block(&wl.body);
                self.indent -= 1;
                self.pl("}}", .{});
            },
            .repeat_loop => |*rl| {
                self.pl("do {{", .{});
                self.indent += 1;
                try self.emit_block(&rl.body);
                self.indent -= 1;
                self.ind();
                self.p("}} while (!(", .{});
                if (self.expr_type(rl.cond) == .any) {
                    self.p("lua_to_bool(", .{});
                    try self.emit_expr(rl.cond);
                    self.p(")", .{});
                } else {
                    try self.emit_expr(rl.cond);
                }
                self.p("));\n", .{});
            },
            .num_for => |*nf| {
                self.ind();
                const vt: RT = if (nf.var_typ != .inferred)
                    types.resolve(nf.var_typ, self.alloc) catch .i64
                else
                    self.expr_type(nf.start);
                const vt2 = if (vt == .any) RT.i64 else vt;
                self.p("for (", .{});
                self.typ(vt2);
                self.p(" {s} = ", .{nf.var_name});
                try self.emit_expr(nf.start);
                self.p("; {s} <= ", .{nf.var_name});
                try self.emit_expr(nf.stop);
                self.p("; {s} += ", .{nf.var_name});
                if (nf.step) |s| try self.emit_expr(s)
                else self.p("1", .{});
                self.p(") {{\n", .{});
                self.indent += 1;
                try self.emit_block(&nf.body);
                self.indent -= 1;
                self.pl("}}", .{});
            },
            .gen_for => |*gf| {
                // We support pairs(t) and ipairs(t) specifically
                var is_pairs = true;
                var table_expr: ?*ast.Expr = null;
                if (gf.iters.len > 0 and gf.iters[0].* == .call) {
                    const c = &gf.iters[0].call;
                    if (c.func.* == .name) {
                        const name = c.func.name.ident;
                        if (std.mem.eql(u8, name, "pairs") or std.mem.eql(u8, name, "ipairs")) {
                            is_pairs = std.mem.eql(u8, name, "pairs");
                            if (c.args.len > 0) table_expr = c.args[0];
                        }
                    }
                }

                if (table_expr) |tbl| {
                    self.pl("{{", .{});
                    self.indent += 1;
                    self.ind();
                    self.p("lua_Value tbl = ", .{});
                    try self.emit_expr(tbl);
                    self.p(";\n", .{});
                    self.pl("if (tbl.type == VAL_TABLE) {{", .{});
                    self.indent += 1;
                    self.pl("lua_Table* t_ptr = (lua_Table*)tbl.as.tval;", .{});
                    
                    if (is_pairs) {
                        self.pl("for (int idx = 0; idx < t_ptr->count; idx++) {{", .{});
                        self.indent += 1;
                        if (gf.vars.len > 0) self.pl("lua_Value {s} = t_ptr->entries[idx].key;", .{gf.vars[0]});
                        if (gf.vars.len > 1) self.pl("lua_Value {s} = t_ptr->entries[idx].val;", .{gf.vars[1]});
                        try self.emit_block(&gf.body);
                        self.indent -= 1;
                        self.pl("}}", .{});
                    } else {
                        // ipairs
                        self.pl("double idx = 1.0;", .{});
                        self.pl("while (true) {{", .{});
                        self.indent += 1;
                        self.pl("lua_Value k = lua_val_from_num(idx);", .{});
                        self.pl("lua_Value _v_val = lua_table_get(tbl, k);", .{});
                        self.pl("if (_v_val.type == VAL_NIL) break;", .{});
                        if (gf.vars.len > 0) self.pl("lua_Value {s} = k;", .{gf.vars[0]});
                        if (gf.vars.len > 1) self.pl("lua_Value {s} = _v_val;", .{gf.vars[1]});
                        try self.emit_block(&gf.body);
                        self.pl("idx += 1.0;", .{});
                        self.indent -= 1;
                        self.pl("}}", .{});
                    }
                    self.indent -= 1;
                    self.pl("}}", .{});
                    self.indent -= 1;
                    self.pl("}}", .{});
                } else {
                    self.pl("/* unsupported generic for loop shape */", .{});
                }
            },
            .do_block => |*db| {
                self.pl("{{", .{});
                self.indent += 1;
                try self.emit_block(&db.body);
                self.indent -= 1;
                self.pl("}}", .{});
            },
            .func_decl => {}, // handled at module level
            .struct_def => {}, // handled at module level
            .brk => self.pl("break;", .{}),
            .goto_stmt => |g| self.pl("goto {s};", .{g.label}),
            .label_stmt => |l| self.pl("{s}:;", .{l.label}),
        }
    }

    // ── print() special case ──────────────────────────────────────────────────

    fn emit_print_call(self: *CodeGen, args: []*ast.Expr) E!void {
        if (args.len == 0) {
            self.p("puts(\"\");\n", .{});
            return;
        }
        // Build format string based on arg types
        var fmt_buf: std.ArrayList(u8) = .empty;
        defer fmt_buf.deinit(self.alloc);
        var has_sep = false;
        for (args) |arg| {
            if (has_sep) try fmt_buf.appendSlice(self.alloc, "\\t");
            has_sep = true;
            const t = self.expr_type(arg);
            const spec: []const u8 = switch (t) {
                .i8, .i16, .i32 => "%d",
                .i64             => "%lld",
                .u8, .u16, .u32  => "%u",
                .u64             => "%llu",
                .f32, .f64       => "%g",
                .bool            => "%s",
                .str             => "%s",
                else             => "%s",
            };
            try fmt_buf.appendSlice(self.alloc, spec);
        }
        try fmt_buf.appendSlice(self.alloc, "\\n");
        self.p("printf(\"{s}\"", .{fmt_buf.items});
        for (args) |arg| {
            self.p(", ", .{});
            const t = self.expr_type(arg);
            if (t == .bool) {
                self.p("(", .{});
                try self.emit_expr(arg);
                self.p(") ? \"true\" : \"false\"", .{});
            } else if (t == .any) {
                self.p("lua_to_str(", .{});
                try self.emit_expr(arg);
                self.p(")", .{});
            } else {
                try self.emit_expr(arg);
            }
        }
        self.p(");\n", .{});
    }

    fn emit_as_lua_value(self: *CodeGen, expr: *const ast.Expr) E!void {
        const t = self.expr_type(expr);
        switch (t) {
            .str => {
                self.p("lua_val_from_str(", .{});
                try self.emit_expr(expr);
                self.p(")", .{});
            },
            .i8, .i16, .i32, .i64, .u8, .u16, .u32, .u64, .f32, .f64 => {
                self.p("lua_val_from_num((double)(", .{});
                try self.emit_expr(expr);
                self.p("))", .{});
            },
            .bool => {
                self.p("lua_val_from_bool(", .{});
                try self.emit_expr(expr);
                self.p(")", .{});
            },
            .func => {
                self.p("lua_val_from_func((lua_Value (*)(lua_Value))", .{});
                try self.emit_expr(expr);
                self.p(")", .{});
            },
            .any => {
                try self.emit_expr(expr);
            },
            else => {
                self.p("lua_val_nil()", .{});
            },
        }
    }

    // ── Expressions ───────────────────────────────────────────────────────────

    fn emit_expr(self: *CodeGen, expr: *const ast.Expr) E!void {
        switch (expr.*) {
            .nil        => self.p("NULL", .{}),
            .true_lit   => self.p("true", .{}),
            .false_lit  => self.p("false", .{}),
            .int_lit    => |v| self.p("{d}", .{v.val}),
            .float_lit  => |v| self.p("{d}", .{v.val}),
            .string_lit => |v| {
                self.p("\"", .{});
                try self.emit_string_escaped(v.val);
                self.p("\"", .{});
            },
            .vararg => self.p("/* ... */", .{}),
            .name   => |n| self.p("{s}", .{n.ident}),
            .field  => |f| {
                if (self.expr_type(f.obj) == .any) {
                    self.p("lua_table_get(", .{});
                    try self.emit_expr(f.obj);
                    self.p(", lua_val_from_str(\"{s}\"))", .{f.field});
                } else {
                    try self.emit_expr(f.obj);
                    self.p(".{s}", .{f.field});
                }
            },
            .index => |idx| {
                if (self.expr_type(idx.obj) == .any) {
                    self.p("lua_table_get(", .{});
                    try self.emit_expr(idx.obj);
                    self.p(", ", .{});
                    try self.emit_as_lua_value(idx.key);
                    self.p(")", .{});
                } else {
                    try self.emit_expr(idx.obj);
                    self.p("[", .{});
                    try self.emit_expr(idx.key);
                    self.p("]", .{});
                }
            },
            .call => |c| {
                if (try self.maybe_emit_math_call(c.func, c.args)) return;
                if (try self.maybe_emit_stdlib_call(c.func, c.args)) return;
                if (try self.maybe_emit_stdlib_module_call(c.func, c.args)) return;
                const ft = self.expr_type(c.func);
                try self.emit_expr(c.func);
                self.p("(", .{});
                for (c.args, 0..) |arg, i| {
                    if (i > 0) self.p(", ", .{});
                    switch (ft) {
                        .func => |f| {
                            if (i < f.params.len and f.params[i] == .any) {
                                try self.emit_as_lua_value(arg);
                            } else {
                                try self.emit_expr(arg);
                            }
                        },
                        else => {
                            try self.emit_as_lua_value(arg);
                        }
                    }
                }
                self.p(")", .{});
            },
            .method_call => |mc| {
                const ot = self.expr_type(mc.obj);
                if (ot == .any) {
                    if (std.mem.eql(u8, mc.method, "put") or std.mem.eql(u8, mc.method, "write")) {
                        self.p("lua_file_write_method(", .{});
                        try self.emit_expr(mc.obj);
                        self.p(", ", .{});
                        if (mc.args.len > 0) {
                            try self.emit_as_lua_value(mc.args[0]);
                        } else {
                            self.p("lua_val_nil()", .{});
                        }
                        self.p(")", .{});
                    } else if (std.mem.eql(u8, mc.method, "get") or std.mem.eql(u8, mc.method, "tostring") or std.mem.eql(u8, mc.method, "read")) {
                        self.p("lua_file_read_method(", .{});
                        try self.emit_expr(mc.obj);
                        self.p(")", .{});
                    } else if (std.mem.eql(u8, mc.method, "close")) {
                        self.p("lua_io_close(", .{});
                        try self.emit_expr(mc.obj);
                        self.p(")", .{});
                    } else {
                        try self.emit_expr(mc.obj);
                        self.p("__{s}(", .{mc.method});
                        for (mc.args, 0..) |arg, i| {
                            if (i > 0) self.p(", ", .{});
                            try self.emit_expr(arg);
                        }
                        self.p(")", .{});
                    }
                } else {
                    try self.emit_expr(mc.obj);
                    self.p("__{s}(", .{mc.method});
                    for (mc.args, 0..) |arg, i| {
                        if (i > 0) self.p(", ", .{});
                        try self.emit_expr(arg);
                    }
                    self.p(")", .{});
                }
            },
            .binop => |b| {
                const lt = self.expr_type(b.lhs);
                const rt = self.expr_type(b.rhs);
                if (b.op == .concat) {
                    self.p("lua_concat(", .{});
                    try self.emit_as_lua_value(b.lhs);
                    self.p(", ", .{});
                    try self.emit_as_lua_value(b.rhs);
                    self.p(")", .{});
                } else if (b.op == .pow) {
                    if (lt == .any or rt == .any) {
                        self.p("lua_pow(", .{});
                        try self.emit_as_lua_value(b.lhs);
                        self.p(", ", .{});
                        try self.emit_as_lua_value(b.rhs);
                        self.p(")", .{});
                    } else {
                        self.p("pow((double)(", .{});
                        try self.emit_expr(b.lhs);
                        self.p("), (double)(", .{});
                        try self.emit_expr(b.rhs);
                        self.p("))", .{});
                    }
                } else if (lt == .any or rt == .any) {
                    const func = switch (b.op) {
                        .add => "lua_add",
                        .sub => "lua_sub",
                        .mul => "lua_mul",
                        .div => "lua_div",
                        .idiv => "lua_idiv",
                        .mod => "lua_mod",
                        .band => "lua_band",
                        .bor => "lua_bor",
                        .bxor => "lua_bxor",
                        .lshift => "lua_lshift",
                        .rshift => "lua_rshift",
                        .eq  => "lua_eq",
                        .neq => "lua_neq",
                        .lt  => "lua_lt",
                        .gt  => "lua_gt",
                        .leq => "lua_leq",
                        .geq => "lua_geq",
                        else => null,
                    };
                    if (func) |f| {
                        self.p("{s}(", .{f});
                        try self.emit_as_lua_value(b.lhs);
                        self.p(", ", .{});
                        try self.emit_as_lua_value(b.rhs);
                        self.p(")", .{});
                    } else {
                        self.p("(", .{});
                        try self.emit_expr(b.lhs);
                        self.p(" {s} ", .{binop_str(b.op)});
                        try self.emit_expr(b.rhs);
                        self.p(")", .{});
                    }
                } else {
                    switch (b.op) {
                        .div => {
                            self.p("((double)(", .{});
                            try self.emit_expr(b.lhs);
                            self.p(") / (double)(", .{});
                            try self.emit_expr(b.rhs);
                            self.p("))", .{});
                        },
                        .idiv => {
                            var buf: [128]u8 = undefined;
                            const t = self.expr_type(expr);
                            self.p("(({s})floor((double)(", .{t.c_type(&buf)});
                            try self.emit_expr(b.lhs);
                            self.p(") / (double)(", .{});
                            try self.emit_expr(b.rhs);
                            self.p(")))", .{});
                        },
                        .mod => {
                            var buf: [128]u8 = undefined;
                            const t = self.expr_type(expr);
                            self.p("(({s})((double)(", .{t.c_type(&buf)});
                            try self.emit_expr(b.lhs);
                            self.p(") - (double)(", .{});
                            try self.emit_expr(b.rhs);
                            self.p(") * floor((double)(", .{});
                            try self.emit_expr(b.lhs);
                            self.p(") / (double)(", .{});
                            try self.emit_expr(b.rhs);
                            self.p("))))", .{});
                        },
                        .band, .bor, .bxor, .lshift, .rshift => {
                            var buf: [128]u8 = undefined;
                            const t = self.expr_type(expr);
                            self.p("(({s})((", .{t.c_type(&buf)});
                            try self.emit_expr(b.lhs);
                            self.p(") {s} (", .{binop_str(b.op)});
                            try self.emit_expr(b.rhs);
                            self.p(")))", .{});
                        },
                        else => {
                            self.p("(", .{});
                            try self.emit_expr(b.lhs);
                            self.p(" {s} ", .{binop_str(b.op)});
                            try self.emit_expr(b.rhs);
                            self.p(")", .{});
                        },
                    }
                }
            },
            .unop => |u| {
                const ot = self.expr_type(u.operand);
                if (ot == .any) {
                    switch (u.op) {
                        .neg  => { self.p("lua_val_from_num(-lua_to_num(", .{}); try self.emit_expr(u.operand); self.p("))", .{}); },
                        .not  => { self.p("(!lua_to_bool(", .{}); try self.emit_expr(u.operand); self.p("))", .{}); },
                        .len  => { self.p("lua_len(", .{}); try self.emit_expr(u.operand); self.p(")", .{}); },
                        .bnot => { self.p("lua_val_from_num((double)(~((int64_t)lua_to_num(", .{}); try self.emit_expr(u.operand); self.p("))))", .{}); },
                    }
                } else {
                    switch (u.op) {
                        .neg  => { self.p("(-", .{}); try self.emit_expr(u.operand); self.p(")", .{}); },
                        .not  => { self.p("(!", .{}); try self.emit_expr(u.operand); self.p(")", .{}); },
                        .len  => { self.p("strlen(", .{}); try self.emit_expr(u.operand); self.p(")", .{}); },
                        .bnot => { self.p("(~", .{}); try self.emit_expr(u.operand); self.p(")", .{}); },
                    }
                }
            },
            .func_expr => |fb| {
                // Inline lambda — emit as named static and reference it
                _ = fb;
                self.p("/* lambda */NULL", .{});
            },
            .table => |t| {
                self.p("({{\n", .{});
                self.indent += 1;
                self.ind();
                self.p("lua_Value tmp = lua_table_new();\n", .{});
                var pos_idx: f64 = 1.0;
                for (t.fields) |fld| {
                    self.ind();
                    switch (fld) {
                        .indexed => |idx| {
                            self.p("lua_table_set(tmp, ", .{});
                            try self.emit_as_lua_value(idx.key);
                            self.p(", ", .{});
                            try self.emit_as_lua_value(idx.val);
                            self.p(");\n", .{});
                        },
                        .named => |nmd| {
                            self.p("lua_table_set(tmp, lua_val_from_str(\"{s}\"), ", .{nmd.key});
                            try self.emit_as_lua_value(nmd.val);
                            self.p(");\n", .{});
                        },
                        .positional => |pos_expr| {
                            self.p("lua_table_set(tmp, lua_val_from_num({d}), ", .{pos_idx});
                            try self.emit_as_lua_value(pos_expr);
                            self.p(");\n", .{});
                            pos_idx += 1.0;
                        },
                    }
                }
                self.ind();
                self.p("tmp;\n", .{});
                self.indent -= 1;
                self.ind();
                self.p("}})", .{});
            },
        }
    }

    fn emit_string_escaped(self: *CodeGen, s: []const u8) E!void {
        var i: usize = 0;
        while (i < s.len) {
            const c = s[i];
            i += 1;
            if (c == '\\' and i < s.len) {
                // Pass escape sequences through as-is
                self.p("\\{c}", .{s[i]});
                i += 1;
            } else if (c == '"') {
                self.p("\\\"", .{});
            } else {
                self.p("{c}", .{c});
            }
        }
    }

    fn maybe_emit_math_call(self: *CodeGen, func: *const ast.Expr, args: []*ast.Expr) E!bool {
        if (func.* != .field) return false;
        const f = &func.field;
        if (f.obj.* != .name) return false;
        if (!std.mem.eql(u8, f.obj.name.ident, "math")) return false;

        const fname = f.field;
        const lua_names = [_][]const u8{
            "sqrt", "abs", "floor", "ceil", "sin", "cos", "tan",
            "asin", "acos", "atan", "sinh", "cosh", "tanh",
            "exp", "log", "pow", "fmod", "max", "min",
        };
        const c_names = [_][]const u8{
            "sqrt", "fabs", "floor", "ceil", "sin", "cos", "tan",
            "asin", "acos", "atan", "sinh", "cosh", "tanh",
            "exp", "log", "pow", "fmod", "fmax", "fmin",
        };
        for (lua_names, c_names) |ln, cn| {
            if (std.mem.eql(u8, fname, ln)) {
                self.p("{s}(", .{cn});
                for (args, 0..) |arg, i| {
                    if (i > 0) self.p(", ", .{});
                    try self.emit_expr(arg);
                }
                self.p(")", .{});
                return true;
            }
        }
        return false;
    }

    fn maybe_emit_stdlib_call(self: *CodeGen, func: *const ast.Expr, args: []*ast.Expr) E!bool {
        if (func.* != .name) return false;
        const name = func.name.ident;
        if (std.mem.eql(u8, name, "assert")) {
            self.p("lua_assert(", .{});
            if (args.len > 0) {
                try self.emit_as_lua_value(args[0]);
            } else {
                self.p("lua_val_nil()", .{});
            }
            self.p(", ", .{});
            if (args.len > 1) {
                self.p("lua_to_str(", .{});
                try self.emit_as_lua_value(args[1]);
                self.p(")", .{});
            } else {
                self.p("NULL", .{});
            }
            self.p(")", .{});
            return true;
        } else if (std.mem.eql(u8, name, "require")) {
            self.p("lua_require(", .{});
            if (args.len > 0) {
                try self.emit_as_lua_value(args[0]);
            } else {
                self.p("lua_val_nil()", .{});
            }
            self.p(")", .{});
            return true;
        }
        return false;
    }

    fn maybe_emit_stdlib_module_call(self: *CodeGen, func: *const ast.Expr, args: []*ast.Expr) E!bool {
        if (func.* != .field) return false;
        const f = &func.field;

        // 1. Handle nested string.buffer.new()
        if (f.obj.* == .field) {
            const inner = &f.obj.field;
            if (inner.obj.* == .name and std.mem.eql(u8, inner.obj.name.ident, "string") and std.mem.eql(u8, inner.field, "buffer")) {
                if (std.mem.eql(u8, f.field, "new")) {
                    self.p("lua_str_buf_new()", .{});
                    return true;
                }
            }
        }

        if (f.obj.* != .name) return false;
        const mod = f.obj.name.ident;
        const fname = f.field;

        if (std.mem.eql(u8, mod, "string")) {
            const mapped = if (std.mem.eql(u8, fname, "len")) "lua_str_len"
            else if (std.mem.eql(u8, fname, "lower")) "lua_str_lower"
            else if (std.mem.eql(u8, fname, "upper")) "lua_str_upper"
            else if (std.mem.eql(u8, fname, "sub")) "lua_str_sub"
            else if (std.mem.eql(u8, fname, "char")) "lua_str_char"
            else if (std.mem.eql(u8, fname, "format")) "lua_str_format"
            else if (std.mem.eql(u8, fname, "rep")) "lua_str_rep"
            else if (std.mem.eql(u8, fname, "reverse")) "lua_str_reverse"
            else if (std.mem.eql(u8, fname, "byte")) "lua_str_byte"
            else if (std.mem.eql(u8, fname, "find")) "lua_str_find"
            else return false;

            const expected: usize = if (std.mem.eql(u8, fname, "len") or std.mem.eql(u8, fname, "lower") or std.mem.eql(u8, fname, "upper") or std.mem.eql(u8, fname, "reverse")) 1
            else if (std.mem.eql(u8, fname, "find")) 2
            else if (std.mem.eql(u8, fname, "sub") or std.mem.eql(u8, fname, "rep") or std.mem.eql(u8, fname, "byte")) 3
            else 4;

            self.p("{s}(", .{mapped});
            var i: usize = 0;
            while (i < expected) : (i += 1) {
                if (i > 0) self.p(", ", .{});
                if (i < args.len) {
                    try self.emit_as_lua_value(args[i]);
                } else {
                    self.p("lua_val_nil()", .{});
                }
            }
            self.p(")", .{});
            return true;
        } else if (std.mem.eql(u8, mod, "table")) {
            const mapped = if (std.mem.eql(u8, fname, "insert")) "lua_tbl_insert"
            else if (std.mem.eql(u8, fname, "remove")) "lua_tbl_remove"
            else if (std.mem.eql(u8, fname, "concat")) "lua_tbl_concat"
            else if (std.mem.eql(u8, fname, "sort")) "lua_tbl_sort"
            else if (std.mem.eql(u8, fname, "new")) "lua_tbl_new"
            else if (std.mem.eql(u8, fname, "clear")) "lua_tbl_clear"
            else if (std.mem.eql(u8, fname, "move")) "lua_tbl_move"
            else if (std.mem.eql(u8, fname, "unpack")) "lua_tbl_unpack"
            else return false;

            const expected: usize = if (std.mem.eql(u8, fname, "sort") or std.mem.eql(u8, fname, "clear")) @as(usize, 1)
            else if (std.mem.eql(u8, fname, "remove") or std.mem.eql(u8, fname, "new")) @as(usize, 2)
            else if (std.mem.eql(u8, fname, "insert") or std.mem.eql(u8, fname, "unpack")) @as(usize, 3)
            else if (std.mem.eql(u8, fname, "concat")) @as(usize, 4)
            else if (std.mem.eql(u8, fname, "move")) @as(usize, 5)
            else 0;

            self.p("{s}(", .{mapped});
            var i: usize = 0;
            while (i < expected) : (i += 1) {
                if (i > 0) self.p(", ", .{});
                if (i < args.len) {
                    try self.emit_as_lua_value(args[i]);
                } else {
                    self.p("lua_val_nil()", .{});
                }
            }
            self.p(")", .{});
            return true;
        } else if (std.mem.eql(u8, mod, "io")) {
            const mapped = if (std.mem.eql(u8, fname, "write")) "lua_io_write"
            else if (std.mem.eql(u8, fname, "read")) "lua_io_read"
            else if (std.mem.eql(u8, fname, "flush")) "lua_io_flush"
            else if (std.mem.eql(u8, fname, "open")) "lua_io_open"
            else if (std.mem.eql(u8, fname, "close")) "lua_io_close"
            else return false;

            const expected: usize = if (std.mem.eql(u8, fname, "flush")) @as(usize, 0)
            else if (std.mem.eql(u8, fname, "read") or std.mem.eql(u8, fname, "close")) @as(usize, 1)
            else if (std.mem.eql(u8, fname, "open")) @as(usize, 2)
            else if (std.mem.eql(u8, fname, "write")) @as(usize, 4)
            else 0;

            self.p("{s}(", .{mapped});
            var i: usize = 0;
            while (i < expected) : (i += 1) {
                if (i > 0) self.p(", ", .{});
                if (i < args.len) {
                    try self.emit_as_lua_value(args[i]);
                } else {
                    self.p("lua_val_nil()", .{});
                }
            }
            self.p(")", .{});
            return true;
        } else if (std.mem.eql(u8, mod, "os")) {
            const mapped = if (std.mem.eql(u8, fname, "clock")) "lua_os_clock"
            else if (std.mem.eql(u8, fname, "time")) "lua_os_time"
            else if (std.mem.eql(u8, fname, "difftime")) "lua_os_difftime"
            else if (std.mem.eql(u8, fname, "exit")) "lua_os_exit"
            else if (std.mem.eql(u8, fname, "getenv")) "lua_os_getenv"
            else if (std.mem.eql(u8, fname, "remove")) "lua_os_remove"
            else if (std.mem.eql(u8, fname, "rename")) "lua_os_rename"
            else if (std.mem.eql(u8, fname, "date")) "lua_os_date"
            else if (std.mem.eql(u8, fname, "execute")) "lua_os_execute"
            else return false;

            const expected: usize = if (std.mem.eql(u8, fname, "clock")) @as(usize, 0)
            else if (std.mem.eql(u8, fname, "time") or std.mem.eql(u8, fname, "exit") or std.mem.eql(u8, fname, "getenv") or std.mem.eql(u8, fname, "remove") or std.mem.eql(u8, fname, "execute")) @as(usize, 1)
            else if (std.mem.eql(u8, fname, "difftime") or std.mem.eql(u8, fname, "rename") or std.mem.eql(u8, fname, "date")) @as(usize, 2)
            else 0;

            self.p("{s}(", .{mapped});
            var i: usize = 0;
            while (i < expected) : (i += 1) {
                if (i > 0) self.p(", ", .{});
                if (i < args.len) {
                    try self.emit_as_lua_value(args[i]);
                } else {
                    self.p("lua_val_nil()", .{});
                }
            }
            self.p(")", .{});
            return true;
        } else if (std.mem.eql(u8, mod, "coroutine")) {
            const mapped = if (std.mem.eql(u8, fname, "create")) "lua_co_create"
            else if (std.mem.eql(u8, fname, "resume")) "lua_co_resume"
            else if (std.mem.eql(u8, fname, "yield")) "lua_co_yield"
            else if (std.mem.eql(u8, fname, "status")) "lua_co_status"
            else if (std.mem.eql(u8, fname, "running")) "lua_co_running"
            else return false;

            const expected: usize = if (std.mem.eql(u8, fname, "running")) @as(usize, 0)
            else if (std.mem.eql(u8, fname, "create") or std.mem.eql(u8, fname, "yield") or std.mem.eql(u8, fname, "status")) @as(usize, 1)
            else if (std.mem.eql(u8, fname, "resume")) @as(usize, 2)
            else 0;

            self.p("{s}(", .{mapped});
            var i: usize = 0;
            while (i < expected) : (i += 1) {
                if (i > 0) self.p(", ", .{});
                if (i < args.len) {
                    try self.emit_as_lua_value(args[i]);
                } else {
                    self.p("lua_val_nil()", .{});
                }
            }
            self.p(")", .{});
            return true;
        } else if (std.mem.eql(u8, mod, "math")) {
            const mapped = if (std.mem.eql(u8, fname, "random")) "lua_math_random"
            else if (std.mem.eql(u8, fname, "randomseed")) "lua_math_randomseed"
            else if (std.mem.eql(u8, fname, "deg")) "lua_math_deg"
            else if (std.mem.eql(u8, fname, "rad")) "lua_math_rad"
            else if (std.mem.eql(u8, fname, "type")) "lua_math_type"
            else return false;

            const expected: usize = if (std.mem.eql(u8, fname, "randomseed") or std.mem.eql(u8, fname, "deg") or std.mem.eql(u8, fname, "rad") or std.mem.eql(u8, fname, "type")) @as(usize, 1)
            else if (std.mem.eql(u8, fname, "random")) @as(usize, 2)
            else 0;

            self.p("{s}(", .{mapped});
            var i: usize = 0;
            while (i < expected) : (i += 1) {
                if (i > 0) self.p(", ", .{});
                if (i < args.len) {
                    try self.emit_as_lua_value(args[i]);
                } else {
                    self.p("lua_val_nil()", .{});
                }
            }
            self.p(")", .{});
            return true;
        } else if (std.mem.eql(u8, mod, "utf8")) {
            const mapped = if (std.mem.eql(u8, fname, "char")) "lua_str_char"
            else if (std.mem.eql(u8, fname, "len")) "lua_utf8_len"
            else return false;

            const expected: usize = if (std.mem.eql(u8, fname, "len")) @as(usize, 1)
            else if (std.mem.eql(u8, fname, "char")) @as(usize, 4)
            else 0;

            self.p("{s}(", .{mapped});
            var i: usize = 0;
            while (i < expected) : (i += 1) {
                if (i > 0) self.p(", ", .{});
                if (i < args.len) {
                    try self.emit_as_lua_value(args[i]);
                } else {
                    self.p("lua_val_nil()", .{});
                }
            }
            self.p(")", .{});
            return true;
        } else if (std.mem.eql(u8, mod, "debug")) {
            const mapped = if (std.mem.eql(u8, fname, "traceback")) "lua_debug_traceback"
            else return false;

            const expected: usize = if (std.mem.eql(u8, fname, "traceback")) @as(usize, 0)
            else 0;

            self.p("{s}(", .{mapped});
            var i: usize = 0;
            while (i < expected) : (i += 1) {
                if (i > 0) self.p(", ", .{});
                if (i < args.len) {
                    try self.emit_as_lua_value(args[i]);
                } else {
                    self.p("lua_val_nil()", .{});
                }
            }
            self.p(")", .{});
            return true;
        }

        return false;
    }

    fn binop_str(op: ast.BinOp) []const u8 {
        return switch (op) {
            .add    => "+",
            .sub    => "-",
            .mul    => "*",
            .div    => "/",
            .idiv   => "/",   // integer division — both operands should be integer
            .mod    => "%",
            .pow    => "/* ^ */", // handled via pow()
            .band   => "&",
            .bor    => "|",
            .bxor   => "^",
            .lshift => "<<",
            .rshift => ">>",
            .concat => "/* .. */",
            .eq     => "==",
            .neq    => "!=",
            .lt     => "<",
            .gt     => ">",
            .leq    => "<=",
            .geq    => ">=",
            .@"and" => "&&",
            .@"or"  => "||",
        };
    }
};

const duo_runtime =
    \\/* --- Duo Runtime Support --- */
    \\#include <stdbool.h>
    \\#include <stdio.h>
    \\#include <stdlib.h>
    \\#include <string.h>
    \\
    \\#define LUA_LIKELY(x)   __builtin_expect(!!(x), 1)
    \\#define LUA_UNLIKELY(x) __builtin_expect(!!(x), 0)
    \\
    \\typedef enum {
    \\    VAL_NIL,
    \\    VAL_BOOL,
    \\    VAL_NUMBER,
    \\    VAL_STRING,
    \\    VAL_TABLE,
    \\    VAL_BUFFER,
    \\    VAL_THREAD,
    \\    VAL_FUNC,
    \\    VAL_FILE,
    \\} lua_ValType;
    \\
    \\typedef struct {
    \\    lua_ValType type;
    \\    union {
    \\        bool bval;
    \\        double nval;
    \\        const char* sval;
    \\        void* tval;
    \\        void* fval; // Cast to function pointer when needed
    \\    } as;
    \\} lua_Value;
    \\
    \\static lua_Value package;
    \\static lua_Value math;
    \\static lua_Value utf8;
    \\static lua_Value debug;
    \\static inline bool lua_eq(lua_Value a, lua_Value b);
    \\static inline lua_Value lua_package_init(void);
    \\static inline lua_Value lua_math_init(void);
    \\static inline lua_Value lua_utf8_init(void);
    \\static inline lua_Value lua_debug_init(void);
    \\static inline lua_Value lua_require(lua_Value name_val);
    \\
    \\static inline lua_Value lua_val_nil(void) {
    \\    lua_Value v;
    \\    v.type = VAL_NIL;
    \\    return v;
    \\}
    \\
    \\static inline lua_Value lua_val_from_bool(bool b) {
    \\    lua_Value v;
    \\    v.type = VAL_BOOL;
    \\    v.as.bval = b;
    \\    return v;
    \\}
    \\
    \\static inline lua_Value lua_val_from_num(double n) {
    \\    lua_Value v;
    \\    v.type = VAL_NUMBER;
    \\    v.as.nval = n;
    \\    return v;
    \\}
    \\
    \\static inline lua_Value lua_val_from_str(const char* s) {
    \\    lua_Value v;
    \\    v.type = VAL_STRING;
    \\    v.as.sval = s;
    \\    return v;
    \\}
    \\
    \\static inline lua_Value lua_val_from_table(void* t) {
    \\    lua_Value v;
    \\    v.type = VAL_TABLE;
    \\    v.as.tval = t;
    \\    return v;
    \\}
    \\
    \\static inline lua_Value lua_val_from_func(lua_Value (*f)(lua_Value)) {
    \\    lua_Value v;
    \\    v.type = VAL_FUNC;
    \\    v.as.fval = (void*)f;
    \\    return v;
    \\}
    \\
    \\static inline const char* lua_to_str(lua_Value v) {
    \\    if (LUA_LIKELY(v.type == VAL_STRING)) return v.as.sval;
    \\    if (v.type == VAL_TABLE) return "table";
    \\    if (v.type == VAL_BUFFER) return "string.buffer";
    \\    if (v.type == VAL_THREAD) return "thread";
    \\    if (v.type == VAL_FUNC) return "function";
    \\    if (v.type == VAL_FILE) return "file";
    \\    if (v.type == VAL_NUMBER) {
    \\        char* buf = malloc(32);
    \\        sprintf(buf, "%g", v.as.nval);
    \\        return buf;
    \\    }
    \\    if (v.type == VAL_BOOL) return v.as.bval ? "true" : "false";
    \\    return "nil";
    \\}
    \\
    \\static inline double lua_to_num(lua_Value v) {
    \\    if (LUA_LIKELY(v.type == VAL_NUMBER)) return v.as.nval;
    \\    if (v.type == VAL_BOOL) return v.as.bval ? 1.0 : 0.0;
    \\    if (v.type == VAL_STRING) return atof(v.as.sval);
    \\    return 0.0;
    \\}
    \\
    \\static inline bool lua_to_bool(lua_Value v) {
    \\    if (LUA_LIKELY(v.type == VAL_BOOL)) return v.as.bval;
    \\    if (v.type == VAL_NIL) return false;
    \\    return true;
    \\}
    \\
    \\typedef struct {
    \\    lua_Value key;
    \\    lua_Value val;
    \\} lua_TableEntry;
    \\
    \\typedef struct {
    \\    lua_TableEntry* entries;
    \\    int capacity;
    \\    int count;
    \\} lua_Table;
    \\
    \\static inline lua_Value lua_table_new(void) {
    \\    lua_Table* t = malloc(sizeof(lua_Table));
    \\    t->entries = NULL;
    \\    t->capacity = 0;
    \\    t->count = 0;
    \\    return lua_val_from_table(t);
    \\}
    \\
    \\static inline lua_Value lua_table_get(lua_Value table, lua_Value key) {
    \\    if (table.type != VAL_TABLE) return lua_val_nil();
    \\    lua_Table* t = (lua_Table*)table.as.tval;
    \\    if (!t) return lua_val_nil();
    \\    for (int i = 0; i < t->count; i++) {
    \\        if (lua_eq(t->entries[i].key, key)) {
    \\            return t->entries[i].val;
    \\        }
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline void lua_table_set(lua_Value table, lua_Value key, lua_Value val) {
    \\    if (table.type != VAL_TABLE) return;
    \\    lua_Table* t = (lua_Table*)table.as.tval;
    \\    if (!t) return;
    \\    for (int i = 0; i < t->count; i++) {
    \\        if (lua_eq(t->entries[i].key, key)) {
    \\            if (val.type == VAL_NIL) {
    \\                for (int j = i; j < t->count - 1; j++) {
    \\                    t->entries[j] = t->entries[j + 1];
    \\                }
    \\                t->count--;
    \\            } else {
    \\                t->entries[i].val = val;
    \\            }
    \\            return;
    \\        }
    \\    }
    \\    if (val.type == VAL_NIL) return;
    \\    if (t->count >= t->capacity) {
    \\        t->capacity = t->capacity == 0 ? 4 : t->capacity * 2;
    \\        t->entries = realloc(t->entries, t->capacity * sizeof(lua_TableEntry));
    \\    }
    \\    t->entries[t->count].key = key;
    \\    t->entries[t->count].val = val;
    \\    t->count++;
    \\}
    \\
    \\static inline const char* lua_concat(lua_Value a, lua_Value b) {
    \\    const char* sa = lua_to_str(a);
    \\    const char* sb = lua_to_str(b);
    \\    char* res = malloc(strlen(sa) + strlen(sb) + 1);
    \\    strcpy(res, sa);
    \\    strcat(res, sb);
    \\    return res;
    \\}
    \\
    \\static inline lua_Value lua_add(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return lua_val_from_num(a.as.nval + b.as.nval);
    \\    }
    \\    return lua_val_from_num(lua_to_num(a) + lua_to_num(b));
    \\}
    \\
    \\static inline lua_Value lua_sub(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return lua_val_from_num(a.as.nval - b.as.nval);
    \\    }
    \\    return lua_val_from_num(lua_to_num(a) - lua_to_num(b));
    \\}
    \\
    \\static inline lua_Value lua_mul(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return lua_val_from_num(a.as.nval * b.as.nval);
    \\    }
    \\    return lua_val_from_num(lua_to_num(a) * lua_to_num(b));
    \\}
    \\
    \\static inline lua_Value lua_div(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return lua_val_from_num(a.as.nval / b.as.nval);
    \\    }
    \\    return lua_val_from_num(lua_to_num(a) / lua_to_num(b));
    \\}
    \\
    \\static inline lua_Value lua_idiv(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return lua_val_from_num(floor(a.as.nval / b.as.nval));
    \\    }
    \\    return lua_val_from_num(floor(lua_to_num(a) / lua_to_num(b)));
    \\}
    \\
    \\static inline lua_Value lua_mod(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        double na = a.as.nval;
    \\        double nb = b.as.nval;
    \\        return lua_val_from_num(na - nb * floor(na / nb));
    \\    }
    \\    double na = lua_to_num(a);
    \\    double nb = lua_to_num(b);
    \\    return lua_val_from_num(na - nb * floor(na / nb));
    \\}
    \\
    \\static inline lua_Value lua_pow(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return lua_val_from_num(pow(a.as.nval, b.as.nval));
    \\    }
    \\    return lua_val_from_num(pow(lua_to_num(a), lua_to_num(b)));
    \\}
    \\
    \\static inline lua_Value lua_band(lua_Value a, lua_Value b) {
    \\    return lua_val_from_num((double)((int64_t)lua_to_num(a) & (int64_t)lua_to_num(b)));
    \\}
    \\
    \\static inline lua_Value lua_bor(lua_Value a, lua_Value b) {
    \\    return lua_val_from_num((double)((int64_t)lua_to_num(a) | (int64_t)lua_to_num(b)));
    \\}
    \\
    \\static inline lua_Value lua_bxor(lua_Value a, lua_Value b) {
    \\    return lua_val_from_num((double)((int64_t)lua_to_num(a) ^ (int64_t)lua_to_num(b)));
    \\}
    \\
    \\static inline lua_Value lua_lshift(lua_Value a, lua_Value b) {
    \\    return lua_val_from_num((double)((int64_t)lua_to_num(a) << (int64_t)lua_to_num(b)));
    \\}
    \\
    \\static inline lua_Value lua_rshift(lua_Value a, lua_Value b) {
    \\    return lua_val_from_num((double)((int64_t)lua_to_num(a) >> (int64_t)lua_to_num(b)));
    \\}
    \\
    \\static inline bool lua_eq(lua_Value a, lua_Value b) {
    \\    if (a.type != b.type) return false;
    \\    switch (a.type) {
    \\        case VAL_NIL: return true;
    \\        case VAL_BOOL: return a.as.bval == b.as.bval;
    \\        case VAL_NUMBER: return a.as.nval == b.as.nval;
    \\        case VAL_STRING: return strcmp(a.as.sval, b.as.sval) == 0;
    \\        case VAL_TABLE: return a.as.tval == b.as.tval;
    \\        case VAL_BUFFER: return a.as.tval == b.as.tval;
    \\        case VAL_THREAD: return a.as.tval == b.as.tval;
    \\        case VAL_FUNC: return a.as.fval == b.as.fval;
    \\        case VAL_FILE: return a.as.tval == b.as.tval;
    \\    }
    \\    return false;
    \\}
    \\
    \\static inline bool lua_neq(lua_Value a, lua_Value b) {
    \\    return !lua_eq(a, b);
    \\}
    \\
    \\static inline bool lua_lt(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return a.as.nval < b.as.nval;
    \\    }
    \\    return lua_to_num(a) < lua_to_num(b);
    \\}
    \\
    \\static inline bool lua_gt(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return a.as.nval > b.as.nval;
    \\    }
    \\    return lua_to_num(a) > lua_to_num(b);
    \\}
    \\
    \\static inline bool lua_leq(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return a.as.nval <= b.as.nval;
    \\    }
    \\    return lua_to_num(a) <= lua_to_num(b);
    \\}
    \\
    \\static inline bool lua_geq(lua_Value a, lua_Value b) {
    \\    if (LUA_LIKELY(a.type == VAL_NUMBER && b.type == VAL_NUMBER)) {
    \\        return a.as.nval >= b.as.nval;
    \\    }
    \\    return lua_to_num(a) >= lua_to_num(b);
    \\}
    \\
    \\static inline lua_Value tostring(lua_Value v) {
    \\    return lua_val_from_str(lua_to_str(v));
    \\}
    \\
    \\static inline lua_Value tonumber(lua_Value v) {
    \\    return lua_val_from_num(lua_to_num(v));
    \\}
    \\
    \\static inline lua_Value type(lua_Value v) {
    \\    switch (v.type) {
    \\        case VAL_NIL: return lua_val_from_str("nil");
    \\        case VAL_BOOL: return lua_val_from_str("boolean");
    \\        case VAL_NUMBER: return lua_val_from_str("number");
    \\        case VAL_STRING: return lua_val_from_str("string");
    \\        case VAL_TABLE: return lua_val_from_str("table");
    \\        case VAL_BUFFER: return lua_val_from_str("string.buffer");
    \\        case VAL_THREAD: return lua_val_from_str("thread");
    \\        case VAL_FUNC: return lua_val_from_str("function");
    \\        case VAL_FILE: return lua_val_from_str("file");
    \\    }
    \\    return lua_val_from_str("unknown");
    \\}
    \\
    \\static inline lua_Value lua_assert(lua_Value v, const char* msg) {
    \\    if (!lua_to_bool(v)) {
    \\        fprintf(stderr, "assertion failed: %s\n", msg ? msg : "");
    \\        exit(1);
    \\    }
    \\    return v;
    \\}
    \\
    \\static inline int lua_table_len(lua_Value table) {
    \\    if (table.type != VAL_TABLE) return 0;
    \\    int len = 0;
    \\    while (1) {
    \\        lua_Value key = lua_val_from_num((double)(len + 1));
    \\        lua_Value v = lua_table_get(table, key);
    \\        if (v.type == VAL_NIL) break;
    \\        len++;
    \\    }
    \\    return len;
    \\}
    \\
    \\/* --- String Library --- */
    \\static inline lua_Value lua_str_len(lua_Value s) {
    \\    return lua_val_from_num((double)strlen(lua_to_str(s)));
    \\}
    \\
    \\static inline lua_Value lua_str_lower(lua_Value s) {
    \\    const char* str = lua_to_str(s);
    \\    char* res = malloc(strlen(str) + 1);
    \\    for (size_t i = 0; str[i]; i++) {
    \\        res[i] = tolower((unsigned char)str[i]);
    \\    }
    \\    res[strlen(str)] = '\0';
    \\    return lua_val_from_str(res);
    \\}
    \\
    \\static inline lua_Value lua_str_upper(lua_Value s) {
    \\    const char* str = lua_to_str(s);
    \\    char* res = malloc(strlen(str) + 1);
    \\    for (size_t i = 0; str[i]; i++) {
    \\        res[i] = toupper((unsigned char)str[i]);
    \\    }
    \\    res[strlen(str)] = '\0';
    \\    return lua_val_from_str(res);
    \\}
    \\
    \\static inline lua_Value lua_str_sub(lua_Value s, lua_Value start_val, lua_Value end_val) {
    \\    const char* str = lua_to_str(s);
    \\    int len = (int)strlen(str);
    \\    int start = start_val.type == VAL_NIL ? 1 : (int)lua_to_num(start_val);
    \\    int end = end_val.type == VAL_NIL ? len : (int)lua_to_num(end_val);
    \\    if (start < 0) start = len + start + 1;
    \\    if (end < 0) end = len + end + 1;
    \\    if (start < 1) start = 1;
    \\    if (end > len) end = len;
    \\    if (start > end || start > len || end < 1) {
    \\        return lua_val_from_str("");
    \\    }
    \\    int sublen = end - start + 1;
    \\    char* res = malloc(sublen + 1);
    \\    memcpy(res, str + start - 1, sublen);
    \\    res[sublen] = '\0';
    \\    return lua_val_from_str(res);
    \\}
    \\
    \\static inline lua_Value lua_str_char(lua_Value a1, lua_Value a2, lua_Value a3, lua_Value a4) {
    \\    int len = 0;
    \\    char buf[5] = {0};
    \\    if (a1.type != VAL_NIL) buf[len++] = (char)lua_to_num(a1);
    \\    if (a2.type != VAL_NIL) buf[len++] = (char)lua_to_num(a2);
    \\    if (a3.type != VAL_NIL) buf[len++] = (char)lua_to_num(a3);
    \\    if (a4.type != VAL_NIL) buf[len++] = (char)lua_to_num(a4);
    \\    char* res = malloc(len + 1);
    \\    memcpy(res, buf, len);
    \\    res[len] = '\0';
    \\    return lua_val_from_str(res);
    \\}
    \\
    \\static inline lua_Value lua_str_rep(lua_Value s, lua_Value n_val, lua_Value sep_val) {
    \\    const char* str = lua_to_str(s);
    \\    int n = (int)lua_to_num(n_val);
    \\    if (n <= 0) return lua_val_from_str("");
    \\    const char* sep = sep_val.type == VAL_NIL ? "" : lua_to_str(sep_val);
    \\    size_t slen = strlen(str);
    \\    size_t seplen = strlen(sep);
    \\    size_t total_len = slen * n + seplen * (n - 1);
    \\    char* res = malloc(total_len + 1);
    \\    char* p = res;
    \\    for (int i = 0; i < n; i++) {
    \\        if (i > 0 && seplen > 0) {
    \\            memcpy(p, sep, seplen);
    \\            p += seplen;
    \\        }
    \\        memcpy(p, str, slen);
    \\        p += slen;
    \\    }
    \\    res[total_len] = '\0';
    \\    return lua_val_from_str(res);
    \\}
    \\
    \\static inline lua_Value lua_str_reverse(lua_Value s) {
    \\    const char* str = lua_to_str(s);
    \\    size_t len = strlen(str);
    \\    char* res = malloc(len + 1);
    \\    for (size_t i = 0; i < len; i++) {
    \\        res[i] = str[len - 1 - i];
    \\    }
    \\    res[len] = '\0';
    \\    return lua_val_from_str(res);
    \\}
    \\
    \\static inline lua_Value lua_str_format(lua_Value fmt_val, lua_Value a1, lua_Value a2, lua_Value a3) {
    \\    const char* fmt = lua_to_str(fmt_val);
    \\    char* out = malloc(8192);
    \\    char* p = out;
    \\    const char* f = fmt;
    \\    int arg_idx = 0;
    \\    while (*f) {
    \\        if (*f == '%' && *(f+1)) {
    \\            f++;
    \\            char spec = *f;
    \\            lua_Value arg = lua_val_nil();
    \\            if (arg_idx == 0) arg = a1;
    \\            else if (arg_idx == 1) arg = a2;
    \\            else if (arg_idx == 2) arg = a3;
    \\            arg_idx++;
    \\            if (spec == 's') {
    \\                const char* s = lua_to_str(arg);
    \\                strcpy(p, s);
    \\                p += strlen(s);
    \\            } else if (spec == 'd' || spec == 'i') {
    \\                p += sprintf(p, "%lld", (long long)lua_to_num(arg));
    \\            } else if (spec == 'f' || spec == 'g') {
    \\                p += sprintf(p, "%g", lua_to_num(arg));
    \\            } else if (spec == '%') {
    \\                *p++ = '%';
    \\            } else {
    \\                *p++ = spec;
    \\            }
    \\            f++;
    \\        } else {
    \\            *p++ = *f++;
    \\        }
    \\    }
    \\    *p = '\0';
    \\    return lua_val_from_str(out);
    \\}
    \\
    \\/* --- Table Library --- */
    \\static inline lua_Value lua_tbl_insert(lua_Value table, lua_Value arg1, lua_Value arg2) {
    \\    int len = lua_table_len(table);
    \\    if (arg2.type == VAL_NIL) {
    \\        lua_table_set(table, lua_val_from_num((double)(len + 1)), arg1);
    \\    } else {
    \\        int pos = (int)lua_to_num(arg1);
    \\        for (int i = len; i >= pos; i--) {
    \\            lua_Value v = lua_table_get(table, lua_val_from_num((double)i));
    \\            lua_table_set(table, lua_val_from_num((double)(i + 1)), v);
    \\        }
    \\        lua_table_set(table, lua_val_from_num((double)pos), arg2);
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_tbl_remove(lua_Value table, lua_Value pos_val) {
    \\    int len = lua_table_len(table);
    \\    if (len == 0) return lua_val_nil();
    \\    int pos = pos_val.type == VAL_NIL ? len : (int)lua_to_num(pos_val);
    \\    lua_Value removed = lua_table_get(table, lua_val_from_num((double)pos));
    \\    for (int i = pos; i < len; i++) {
    \\        lua_Value next_val = lua_table_get(table, lua_val_from_num((double)(i + 1)));
    \\        lua_table_set(table, lua_val_from_num((double)i), next_val);
    \\    }
    \\    lua_table_set(table, lua_val_from_num((double)len), lua_val_nil());
    \\    return removed;
    \\}
    \\
    \\static inline lua_Value lua_tbl_concat(lua_Value table, lua_Value sep_val, lua_Value start_val, lua_Value end_val) {
    \\    int len = lua_table_len(table);
    \\    const char* sep = sep_val.type == VAL_NIL ? "" : lua_to_str(sep_val);
    \\    int start = start_val.type == VAL_NIL ? 1 : (int)lua_to_num(start_val);
    \\    int end = end_val.type == VAL_NIL ? len : (int)lua_to_num(end_val);
    \\    if (start > end) return lua_val_from_str("");
    \\    size_t total_size = 0;
    \\    for (int i = start; i <= end; i++) {
    \\        lua_Value v = lua_table_get(table, lua_val_from_num((double)i));
    \\        total_size += strlen(lua_to_str(v));
    \\    }
    \\    total_size += strlen(sep) * (end - start);
    \\    char* res = malloc(total_size + 1);
    \\    char* p = res;
    \\    for (int i = start; i <= end; i++) {
    \\        if (i > start) {
    \\            strcpy(p, sep);
    \\            p += strlen(sep);
    \\        }
    \\        lua_Value v = lua_table_get(table, lua_val_from_num((double)i));
    \\        const char* s = lua_to_str(v);
    \\        strcpy(p, s);
    \\        p += strlen(s);
    \\    }
    \\    *p = '\0';
    \\    return lua_val_from_str(res);
    \\}
    \\
    \\static inline lua_Value lua_tbl_sort(lua_Value table) {
    \\    int len = lua_table_len(table);
    \\    if (len <= 1) return lua_val_nil();
    \\    for (int i = 1; i < len; i++) {
    \\        for (int j = i; j > 0; j--) {
    \\            lua_Value v1 = lua_table_get(table, lua_val_from_num((double)j));
    \\            lua_Value v2 = lua_table_get(table, lua_val_from_num((double)(j + 1)));
    \\            if (lua_to_num(v1) > lua_to_num(v2) || (v1.type == VAL_STRING && strcmp(lua_to_str(v1), lua_to_str(v2)) > 0)) {
    \\                lua_table_set(table, lua_val_from_num((double)j), v2);
    \\                lua_table_set(table, lua_val_from_num((double)(j + 1)), v1);
    \\            }
    \\        }
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\/* --- IO Library --- */
    \\static inline lua_Value lua_io_write(lua_Value a1, lua_Value a2, lua_Value a3, lua_Value a4) {
    \\    if (a1.type != VAL_NIL) printf("%s", lua_to_str(a1));
    \\    if (a2.type != VAL_NIL) printf("%s", lua_to_str(a2));
    \\    if (a3.type != VAL_NIL) printf("%s", lua_to_str(a3));
    \\    if (a4.type != VAL_NIL) printf("%s", lua_to_str(a4));
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_io_read(lua_Value fmt_val) {
    \\    (void)fmt_val;
    \\    char buf[4096];
    \\    if (fgets(buf, sizeof(buf), stdin)) {
    \\        size_t l = strlen(buf);
    \\        if (l > 0 && buf[l - 1] == '\n') buf[l - 1] = '\0';
    \\        return lua_val_from_str(strdup(buf));
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_io_flush(void) {
    \\    fflush(stdout);
    \\    return lua_val_nil();
    \\}
    \\
    \\/* --- OS Library --- */
    \\static inline lua_Value lua_os_clock(void) {
    \\    return lua_val_from_num((double)clock() / CLOCKS_PER_SEC);
    \\}
    \\
    \\static inline lua_Value lua_os_time(lua_Value t_val) {
    \\    (void)t_val;
    \\    return lua_val_from_num((double)time(NULL));
    \\}
    \\
    \\static inline lua_Value lua_os_difftime(lua_Value t2, lua_Value t1) {
    \\    return lua_val_from_num(difftime((time_t)lua_to_num(t2), (time_t)lua_to_num(t1)));
    \\}
    \\
    \\static inline lua_Value lua_os_exit(lua_Value code_val) {
    \\    int code = code_val.type == VAL_NIL ? 0 : (int)lua_to_num(code_val);
    \\    exit(code);
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_os_getenv(lua_Value var) {
    \\    const char* name = lua_to_str(var);
    \\    const char* val = getenv(name);
    \\    if (val) return lua_val_from_str(val);
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_os_remove(lua_Value var) {
    \\    return lua_val_from_bool(remove(lua_to_str(var)) == 0);
    \\}
    \\
    \\static inline lua_Value lua_os_rename(lua_Value oldn, lua_Value newn) {
    \\    return lua_val_from_bool(rename(lua_to_str(oldn), lua_to_str(newn)) == 0);
    \\}
    \\
    \\static inline int64_t lua_len(lua_Value v) {
    \\    if (v.type == VAL_TABLE) {
    \\        return (int64_t)lua_table_len(v);
    \\    }
    \\    if (v.type == VAL_STRING) {
    \\        return (int64_t)strlen(v.as.sval);
    \\    }
    \\    return 0;
    \\}
    \\
    \\static inline lua_Value lua_tbl_new(lua_Value narray, lua_Value nhash) {
    \\    (void)narray; (void)nhash;
    \\    return lua_table_new();
    \\}
    \\
    \\static inline lua_Value lua_tbl_clear(lua_Value table) {
    \\    if (table.type == VAL_TABLE) {
    \\        lua_Table* t = (lua_Table*)table.as.tval;
    \\        if (t) {
    \\            t->count = 0;
    \\        }
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\typedef struct {
    \\    char* data;
    \\    size_t capacity;
    \\    size_t len;
    \\} lua_Buffer;
    \\
    \\static inline lua_Value lua_str_buf_new(void) {
    \\    lua_Buffer* b = malloc(sizeof(lua_Buffer));
    \\    b->data = malloc(32);
    \\    b->data[0] = '\0';
    \\    b->capacity = 32;
    \\    b->len = 0;
    \\    lua_Value v;
    \\    v.type = VAL_BUFFER;
    \\    v.as.tval = b;
    \\    return v;
    \\}
    \\
    \\static inline lua_Value lua_str_buf_put(lua_Value buf, lua_Value s) {
    \\    if (buf.type != VAL_BUFFER) return lua_val_nil();
    \\    lua_Buffer* b = (lua_Buffer*)buf.as.tval;
    \\    const char* str = lua_to_str(s);
    \\    size_t slen = strlen(str);
    \\    if (b->len + slen >= b->capacity) {
    \\        b->capacity = (b->len + slen) * 2;
    \\        b->data = realloc(b->data, b->capacity);
    \\    }
    \\    memcpy(b->data + b->len, str, slen);
    \\    b->len += slen;
    \\    b->data[b->len] = '\0';
    \\    return buf;
    \\}
    \\
    \\static inline lua_Value lua_str_buf_get(lua_Value buf) {
    \\    if (buf.type != VAL_BUFFER) return lua_val_from_str("");
    \\    lua_Buffer* b = (lua_Buffer*)buf.as.tval;
    \\    return lua_val_from_str(strdup(b->data));
    \\}
    \\
    \\typedef enum {
    \\    CO_SUSPENDED,
    \\    CO_RUNNING,
    \\    CO_DEAD,
    \\} lua_CoStatus;
    \\
    \\typedef struct {
    \\    ucontext_t context;
    \\    ucontext_t caller_context;
    \\    char* stack;
    \\    lua_CoStatus status;
    \\    lua_Value func;
    \\    lua_Value yield_value;
    \\    lua_Value resume_value;
    \\} lua_Thread;
    \\
    \\static lua_Thread* active_thread = NULL;
    \\
    \\static void lua_coroutine_runner(void) {
    \\    lua_Thread* co = active_thread;
    \\    if (co && co->func.type == VAL_FUNC) {
    \\        lua_Value (*f)(lua_Value) = (lua_Value (*)(lua_Value))co->func.as.fval;
    \\        lua_Value ret = f(co->resume_value);
    \\        co->status = CO_DEAD;
    \\        co->yield_value = ret;
    \\        swapcontext(&co->context, &co->caller_context);
    \\    }
    \\}
    \\
    \\static inline lua_Value lua_co_create(lua_Value f) {
    \\    lua_Thread* co = malloc(sizeof(lua_Thread));
    \\    co->status = CO_SUSPENDED;
    \\    co->func = f;
    \\    co->yield_value = lua_val_nil();
    \\    co->resume_value = lua_val_nil();
    \\    co->stack = malloc(16384 * 4);
    \\    
    \\    getcontext(&co->context);
    \\    co->context.uc_stack.ss_sp = co->stack;
    \\    co->context.uc_stack.ss_size = 16384 * 4;
    \\    co->context.uc_link = NULL;
    \\    makecontext(&co->context, lua_coroutine_runner, 0);
    \\    
    \\    lua_Value v;
    \\    v.type = VAL_THREAD;
    \\    v.as.tval = co;
    \\    return v;
    \\}
    \\
    \\static inline lua_Value lua_co_resume(lua_Value thread_val, lua_Value arg) {
    \\    if (thread_val.type != VAL_THREAD) return lua_val_nil();
    \\    lua_Thread* co = (lua_Thread*)thread_val.as.tval;
    \\    if (co->status == CO_DEAD) return lua_val_nil();
    \\    
    \\    co->resume_value = arg;
    \\    co->status = CO_RUNNING;
    \\    
    \\    lua_Thread* prev = active_thread;
    \\    active_thread = co;
    \\    swapcontext(&co->caller_context, &co->context);
    \\    active_thread = prev;
    \\    
    \\    return co->yield_value;
    \\}
    \\
    \\static inline lua_Value lua_co_yield(lua_Value val) {
    \\    lua_Thread* co = active_thread;
    \\    if (!co) return lua_val_nil();
    \\    co->yield_value = val;
    \\    co->status = CO_SUSPENDED;
    \\    swapcontext(&co->context, &co->caller_context);
    \\    return co->resume_value;
    \\}
    \\
    \\static inline lua_Value lua_co_status(lua_Value thread_val) {
    \\    if (thread_val.type != VAL_THREAD) return lua_val_from_str("dead");
    \\    lua_Thread* co = (lua_Thread*)thread_val.as.tval;
    \\    if (co->status == CO_SUSPENDED) return lua_val_from_str("suspended");
    \\    if (co->status == CO_RUNNING) return lua_val_from_str("running");
    \\    return lua_val_from_str("dead");
    \\}
    \\
    \\static inline lua_Value lua_package_init(void) {
    \\    lua_Value pkg = lua_table_new();
    \\    lua_table_set(pkg, lua_val_from_str("path"), lua_val_from_str("./?.lua"));
    \\    lua_table_set(pkg, lua_val_from_str("loaded"), lua_table_new());
    \\    return pkg;
    \\}
    \\
    \\static inline lua_Value lua_require(lua_Value name_val) {
    \\    const char* name = lua_to_str(name_val);
    \\    if (strcmp(name, "math") == 0) return math;
    \\    if (strcmp(name, "package") == 0) return package;
    \\    if (strcmp(name, "utf8") == 0) return utf8;
    \\    if (strcmp(name, "debug") == 0) return debug;
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_math_random(lua_Value arg1, lua_Value arg2) {
    \\    if (arg1.type == VAL_NIL && arg2.type == VAL_NIL) {
    \\        double r = (double)rand() / (double)RAND_MAX;
    \\        return lua_val_from_num(r);
    \\    } else if (arg2.type == VAL_NIL) {
    \\        int m = (int)lua_to_num(arg1);
    \\        if (m < 1) return lua_val_from_num(0);
    \\        int r = 1 + (rand() % m);
    \\        return lua_val_from_num((double)r);
    \\    } else {
    \\        int m = (int)lua_to_num(arg1);
    \\        int n = (int)lua_to_num(arg2);
    \\        if (m > n) return lua_val_from_num(0);
    \\        int r = m + (rand() % (n - m + 1));
    \\        return lua_val_from_num((double)r);
    \\    }
    \\}
    \\
    \\static inline lua_Value lua_math_randomseed(lua_Value seed) {
    \\    srand((unsigned int)lua_to_num(seed));
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_math_deg(lua_Value rad) {
    \\    return lua_val_from_num(lua_to_num(rad) * (180.0 / 3.14159265358979323846));
    \\}
    \\
    \\static inline lua_Value lua_math_rad(lua_Value deg) {
    \\    return lua_val_from_num(lua_to_num(deg) * (3.14159265358979323846 / 180.0));
    \\}
    \\
    \\static inline lua_Value lua_math_type(lua_Value v) {
    \\    if (v.type != VAL_NUMBER) return lua_val_nil();
    \\    double d = v.as.nval;
    \\    if (d == (double)(int64_t)d) {
    \\        return lua_val_from_str("integer");
    \\    } else {
    \\        return lua_val_from_str("float");
    \\    }
    \\}
    \\
    \\static inline lua_Value lua_math_init(void) {
    \\    lua_Value m = lua_table_new();
    \\    lua_table_set(m, lua_val_from_str("pi"), lua_val_from_num(3.14159265358979323846));
    \\    lua_table_set(m, lua_val_from_str("maxinteger"), lua_val_from_num(9223372036854775807.0));
    \\    lua_table_set(m, lua_val_from_str("mininteger"), lua_val_from_num(-9223372036854775808.0));
    \\    return m;
    \\}
    \\
    \\static inline lua_Value lua_str_byte(lua_Value s, lua_Value i_val, lua_Value j_val) {
    \\    (void)j_val;
    \\    const char* str = lua_to_str(s);
    \\    int len = (int)strlen(str);
    \\    int idx = i_val.type == VAL_NIL ? 1 : (int)lua_to_num(i_val);
    \\    if (idx < 0) idx = len + idx + 1;
    \\    if (idx < 1 || idx > len) return lua_val_nil();
    \\    return lua_val_from_num((double)(unsigned char)str[idx - 1]);
    \\}
    \\
    \\static inline lua_Value lua_str_find(lua_Value s, lua_Value pat_val) {
    \\    const char* str = lua_to_str(s);
    \\    const char* pat = lua_to_str(pat_val);
    \\    const char* found = strstr(str, pat);
    \\    if (found) {
    \\        int pos = (int)(found - str) + 1;
    \\        return lua_val_from_num((double)pos);
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_tbl_move(lua_Value a1, lua_Value f_val, lua_Value e_val, lua_Value t_val, lua_Value a2) {
    \\    lua_Value dest = a2.type == VAL_NIL ? a1 : a2;
    \\    int f = (int)lua_to_num(f_val);
    \\    int e = (int)lua_to_num(e_val);
    \\    int t = (int)lua_to_num(t_val);
    \\    if (f > e) return dest;
    \\    int count = e - f + 1;
    \\    lua_Value* temp = malloc(count * sizeof(lua_Value));
    \\    for (int i = 0; i < count; i++) {
    \\        temp[i] = lua_table_get(a1, lua_val_from_num((double)(f + i)));
    \\    }
    \\    for (int i = 0; i < count; i++) {
    \\        lua_table_set(dest, lua_val_from_num((double)(t + i)), temp[i]);
    \\    }
    \\    free(temp);
    \\    return dest;
    \\}
    \\
    \\static inline lua_Value lua_tbl_unpack(lua_Value list, lua_Value i_val, lua_Value j_val) {
    \\    (void)j_val;
    \\    int i = i_val.type == VAL_NIL ? 1 : (int)lua_to_num(i_val);
    \\    return lua_table_get(list, lua_val_from_num((double)i));
    \\}
    \\
    \\static inline lua_Value lua_io_open(lua_Value filename_val, lua_Value mode_val) {
    \\    const char* filename = lua_to_str(filename_val);
    \\    const char* mode = mode_val.type == VAL_NIL ? "r" : lua_to_str(mode_val);
    \\    FILE* f = fopen(filename, mode);
    \\    if (!f) return lua_val_nil();
    \\    lua_Value v;
    \\    v.type = VAL_FILE;
    \\    v.as.tval = (void*)f;
    \\    return v;
    \\}
    \\
    \\static inline lua_Value lua_io_close(lua_Value file_val) {
    \\    if (file_val.type == VAL_FILE && file_val.as.tval) {
    \\        fclose((FILE*)file_val.as.tval);
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_file_write_method(lua_Value file_val, lua_Value s) {
    \\    if (file_val.type == VAL_FILE) {
    \\        FILE* f = (FILE*)file_val.as.tval;
    \\        if (f) {
    \\            fprintf(f, "%s", lua_to_str(s));
    \\        }
    \\    } else if (file_val.type == VAL_BUFFER) {
    \\        lua_str_buf_put(file_val, s);
    \\    }
    \\    return file_val;
    \\}
    \\
    \\static inline lua_Value lua_file_read_method(lua_Value file_val) {
    \\    if (file_val.type == VAL_FILE) {
    \\        FILE* f = (FILE*)file_val.as.tval;
    \\        if (f) {
    \\            char buf[4096];
    \\            if (fgets(buf, sizeof(buf), f)) {
    \\                size_t l = strlen(buf);
    \\                if (l > 0 && buf[l - 1] == '\n') buf[l - 1] = '\0';
    \\                return lua_val_from_str(strdup(buf));
    \\            }
    \\        }
    \\        return lua_val_nil();
    \\    } else if (file_val.type == VAL_BUFFER) {
    \\        return lua_str_buf_get(file_val);
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_os_date(lua_Value fmt_val, lua_Value t_val) {
    \\    time_t t = t_val.type == VAL_NIL ? time(NULL) : (time_t)lua_to_num(t_val);
    \\    const char* fmt = fmt_val.type == VAL_NIL ? "%c" : lua_to_str(fmt_val);
    \\    struct tm* ltime = localtime(&t);
    \\    if (!ltime) return lua_val_nil();
    \\    char buf[1024];
    \\    if (strftime(buf, sizeof(buf), fmt, ltime) > 0) {
    \\        return lua_val_from_str(strdup(buf));
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_os_execute(lua_Value cmd_val) {
    \\    if (cmd_val.type == VAL_NIL) {
    \\        return lua_val_from_bool(system(NULL) != 0);
    \\    }
    \\    int res = system(lua_to_str(cmd_val));
    \\    return lua_val_from_bool(res == 0);
    \\}
    \\
    \\static inline lua_Value lua_co_running(void) {
    \\    if (active_thread) {
    \\        lua_Value v;
    \\        v.type = VAL_THREAD;
    \\        v.as.tval = active_thread;
    \\        return v;
    \\    }
    \\    return lua_val_nil();
    \\}
    \\
    \\static inline lua_Value lua_utf8_len(lua_Value s) {
    \\    const char* str = lua_to_str(s);
    \\    int len = 0;
    \\    while (*str) {
    \\        if ((*str & 0xC0) != 0x80) {
    \\            len++;
    \\        }
    \\        str++;
    \\    }
    \\    return lua_val_from_num((double)len);
    \\}
    \\
    \\static inline lua_Value lua_utf8_init(void) {
    \\    return lua_table_new();
    \\}
    \\
    \\static inline lua_Value lua_debug_init(void) {
    \\    return lua_table_new();
    \\}
    \\
    \\static inline lua_Value lua_debug_traceback(void) {
    \\    return lua_val_from_str("stack traceback:\n  [C]: in function 'debug.traceback'");
    \\}
    \\/* --------------------------- */
    \\
;
