/// User-definable @derive macro registry.
///
/// Enables users to write derive macros that generate code from type metadata.
/// Example:
///   @meta.define.derive("Printable", fun generate(meta) -> str
///     -- meta has {name, fields=[{name,type}], methods=[...]}
///     return 'static char* ' .. meta.name .. '_to_string(...) { ... }'
///   end)
///
///   @derive(Printable)
///   type Vec2 = { x: f64, y: f64 }
///   -- Vec2 now has a to_string() method generated by the Printable macro
const std = @import("std");
const ast = @import("ast.zig");

pub const DeriveMacro = struct {
    name: []const u8,
    /// Source text of the macro function (will be evaluated at comptime).
    func_source: []const u8,
    /// Location where @meta.define.derive was declared.
    loc: ast.Loc,
};

/// Native (Lua-free) derive codegen function.
/// Takes typed TypeMetadata and emits C code directly — no Value.table intermediaries.
pub const NativeDeriveFn = *const fn (alloc: std.mem.Allocator, meta: TypeMetadata) anyerror![]const u8;

/// Registry of native derive codegen functions (built-in, no Lua eval).
pub const NativeDeriveRegistry = struct {
    fns: std.StringHashMapUnmanaged(NativeDeriveFn) = .{},

    pub fn init() NativeDeriveRegistry {
        return .{};
    }

    pub fn deinit(self: *NativeDeriveRegistry, alloc: std.mem.Allocator) void {
        self.fns.deinit(alloc);
    }

    pub fn register(self: *NativeDeriveRegistry, alloc: std.mem.Allocator, name: []const u8, func: NativeDeriveFn) !void {
        const owned = try alloc.dupe(u8, name);
        self.fns.put(alloc, owned, func) catch {
            alloc.free(owned);
            return;
        };
    }

    pub fn get(self: *const NativeDeriveRegistry, name: []const u8) ?NativeDeriveFn {
        return self.fns.get(name);
    }

    pub fn contains(self: *const NativeDeriveRegistry, name: []const u8) bool {
        return self.fns.contains(name);
    }

    /// Register all built-in native derives. Only registers derives that have
    /// a native implementation; others fall through to the Lua-compile path.
    pub fn registerBuiltins(self: *NativeDeriveRegistry, alloc: std.mem.Allocator) void {
        for (builtin_derives) |derive_name| {
            const impl = getBuiltinNativeFn(derive_name);
            if (impl) |fn_ptr| {
                self.register(alloc, derive_name, fn_ptr) catch {};
            }
        }
    }
};

/// Global native derive registry singleton.
var native_derive_registry: NativeDeriveRegistry = .{};

pub fn getNativeDeriveRegistry() *NativeDeriveRegistry {
    return &native_derive_registry;
}

var native_derive_registry_initialized: bool = false;

/// The built-in derive table is a PROCESS-lifetime singleton — it is filled once
/// and never freed — so it must not be backed by a caller's arena.
///
/// It used to take whichever allocator called `initNativeDeriveRegistry` first.
/// In the `duo` binary that arena outlives the compile and nothing showed. In
/// the test binary each test owns its own arena: the first test to reach a
/// derive hook filled the map from an arena that was then destroyed, and the
/// next `hasNativeDerive` read a freed hash-map header — a segfault in
/// `std.hash_map.capacity`, arriving in a test that had nothing to do with
/// derives. The registry's own lifetime decides its allocator.
fn nativeDeriveAllocator() std.mem.Allocator {
    return std.heap.page_allocator;
}

pub fn initNativeDeriveRegistry(alloc: std.mem.Allocator) void {
    _ = alloc;
    if (!native_derive_registry_initialized) {
        native_derive_registry.registerBuiltins(nativeDeriveAllocator());
        native_derive_registry_initialized = true;
    }
}

/// Get a native derive function by name, or null if not registered.
pub fn getNativeDerive(name: []const u8) ?NativeDeriveFn {
    const reg = getNativeDeriveRegistry();
    return reg.get(name);
}

/// True if a derive name has a native implementation.
pub fn hasNativeDerive(name: []const u8) bool {
    const reg = getNativeDeriveRegistry();
    return reg.contains(name);
}

/// Lookup a built-in derive's native codegen function, or null if the derive
/// only has a user-defined (Lua-eval) path.
fn getBuiltinNativeFn(name: []const u8) ?NativeDeriveFn {
    if (std.mem.eql(u8, name, "Display")) return generateSimpleDeriveBody;
    if (std.mem.eql(u8, name, "Eq") or std.mem.eql(u8, name, "PartialEq")) return generateEq;
    if (std.mem.eql(u8, name, "Clone")) return generateClone;
    if (std.mem.eql(u8, name, "Default")) return generateDefault;
    if (std.mem.eql(u8, name, "Serialize")) return generateSerialize;
    if (std.mem.eql(u8, name, "Deserialize")) return generateDeserialize;
    if (std.mem.eql(u8, name, "Hash")) return generateHash;
    if (std.mem.eql(u8, name, "Len")) return generateLen;
    if (std.mem.eql(u8, name, "IntoStr")) return generateSimpleDeriveBody;
    if (std.mem.eql(u8, name, "FromStr")) return generateFromStr;
    if (std.mem.eql(u8, name, "Add")) return genOp;
    if (std.mem.eql(u8, name, "Sub")) return genOp;
    if (std.mem.eql(u8, name, "Mul")) return genOp;
    if (std.mem.eql(u8, name, "Div")) return genOp;
    if (std.mem.eql(u8, name, "Rem")) return genOp;
    if (std.mem.eql(u8, name, "Neg")) return genNeg;
    if (std.mem.eql(u8, name, "BitAnd")) return genOp;
    if (std.mem.eql(u8, name, "BitOr")) return genOp;
    if (std.mem.eql(u8, name, "BitXor")) return genOp;
    if (std.mem.eql(u8, name, "BitNot")) return genBitNot;
    if (std.mem.eql(u8, name, "Shl")) return genOp;
    if (std.mem.eql(u8, name, "Shr")) return genOp;
    if (std.mem.eql(u8, name, "AsInt")) return generateAsInt;
    if (std.mem.eql(u8, name, "FromInt")) return generateFromInt;
    if (std.mem.eql(u8, name, "Builder")) return generateBuilder;
    if (std.mem.eql(u8, name, "Ord") or std.mem.eql(u8, name, "PartialOrd")) return generateOrd;
    return null;
}

/// Generate C code for built-in derives directly (no Lua eval).
/// This is the fast native path; returns null for derives without native impl.
pub fn generateBuiltinDerive(alloc: std.mem.Allocator, derive_name: []const u8, meta: TypeMetadata) !?[]const u8 {
    const native_fn = getBuiltinNativeFn(derive_name) orelse return null;
    return native_fn(alloc, meta);
}

// ---- Native derive codegen helpers ----

fn genOp(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    // Derive generic op from function name (called at runtime via NativeDeriveFn)
    return generateFieldwiseOps(alloc, meta, "+");
}

fn genNeg(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_neg(");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " v) {\n    ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " r;\n");
    for (meta.fields) |f| {
        try buf.appendSlice(alloc, "    r.");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, " = -v.");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, ";\n");
    }
    try buf.appendSlice(alloc, "    return r;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn genBitNot(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_bit_not(");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " v) {\n    ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " r;\n");
    for (meta.fields) |f| {
        try buf.appendSlice(alloc, "    r.");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, " = ~v.");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, ";\n");
    }
    try buf.appendSlice(alloc, "    return r;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateEq(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static bool ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_eq(const ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "* a, const ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "* b) {\n    return ");
    for (meta.fields, 0..) |f, i| {
        if (i > 0) try buf.appendSlice(alloc, " && ");
        try buf.appendSlice(alloc, "a->");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, " == b->");
        try buf.appendSlice(alloc, f.name);
    }
    try buf.appendSlice(alloc, ";\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateClone(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_clone(const ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "* src) {\n    ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " dst;\n");
    for (meta.fields) |f| {
        try buf.appendSlice(alloc, "    dst.");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, " = src->");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, ";\n");
    }
    try buf.appendSlice(alloc, "    return dst;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateDefault(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_default(void) {\n    ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " v = {0};\n    return v;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateSerialize(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static void ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_serialize(const ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "* v, char* out, size_t cap) {\n    (void)snprintf(out, cap, \"{\\\"");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "\\\":{\"");
    for (meta.fields) |f| {
        try buf.appendSlice(alloc, ", v->");
        try buf.appendSlice(alloc, f.name);
    }
    try buf.appendSlice(alloc, ");\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateDeserialize(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    _ = meta;
    return alloc.dupe(u8, "/* Deserialize: not yet implemented */\n");
}

fn generateHash(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static uint64_t ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_hash(const ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "* v) {\n    uint64_t h = 14695981039346656037ULL;\n");
    for (meta.fields) |f| {
        try buf.appendSlice(alloc, "    h ^= (uint64_t)v->");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, ";\n    h *= 1099511628211ULL;\n");
    }
    try buf.appendSlice(alloc, "    return h;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateLen(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    _ = meta;
    return alloc.dupe(u8, "");
}

fn generateAsInt(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static int64_t ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_as_int(const ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "* v) {\n    (void)v;\n    return 0;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateFromInt(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_from_int(int64_t n) {\n    ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " v = {0};\n    (void)n;\n    return v;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateBuilder(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_build(");
    for (meta.fields, 0..) |f, i| {
        if (i > 0) try buf.appendSlice(alloc, ", ");
        try buf.appendSlice(alloc, f.type_name);
        try buf.appendSlice(alloc, " ");
        try buf.appendSlice(alloc, f.name);
    }
    try buf.appendSlice(alloc, ") {\n    ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, " v;\n");
    for (meta.fields) |f| {
        try buf.appendSlice(alloc, "    v.");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, " = ");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, ";\n");
    }
    try buf.appendSlice(alloc, "    return v;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateOrd(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);
    try buf.appendSlice(alloc, "static int ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_cmp(const ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "* a, const ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "* b) {\n");
    for (meta.fields) |f| {
        try buf.appendSlice(alloc, "    if (a->");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, " != b->");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, ") return a->");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, " < b->");
        try buf.appendSlice(alloc, f.name);
        try buf.appendSlice(alloc, " ? -1 : 1;\n");
    }
    try buf.appendSlice(alloc, "    return 0;\n}\n");
    return try buf.toOwnedSlice(alloc);
}

fn generateFromStr(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    _ = meta;
    return alloc.dupe(u8, "/* FromStr: not yet implemented */\n");
}

/// Registry of user-defined derive macros.
/// Key: derive name (e.g. "Printable"), Value: macro definition.
pub const DeriveRegistry = struct {
    macros: std.StringHashMapUnmanaged(DeriveMacro) = .{},
    alloc: std.mem.Allocator,

    pub fn init(alloc: std.mem.Allocator) DeriveRegistry {
        return .{ .alloc = alloc };
    }

    pub fn deinit(self: *DeriveRegistry) void {
        var it = self.macros.iterator();
        while (it.next()) |entry| {
            self.alloc.free(entry.key_ptr.*);
            self.alloc.free(entry.value_ptr.*.func_source);
        }
        self.macros.deinit(self.alloc);
    }

    /// Register a new derive macro. Overwrites if name already exists.
    pub fn register(self: *DeriveRegistry, name: []const u8, func_source: []const u8, loc: ast.Loc) !void {
        const owned_name = try self.alloc.dupe(u8, name);
        errdefer self.alloc.free(owned_name);
        const owned_source = try self.alloc.dupe(u8, func_source);
        errdefer self.alloc.free(owned_source);

        // If already exists, free old entries
        if (self.macros.fetchRemove(name)) |kv| {
            self.alloc.free(kv.key);
            self.alloc.free(kv.value.func_source);
        }

        try self.macros.put(self.alloc, owned_name, .{
            .name = owned_name,
            .func_source = owned_source,
            .loc = loc,
        });
    }

    /// Check if a derive name is user-defined (not a built-in).
    pub fn isUserDefined(self: *const DeriveRegistry, name: []const u8) bool {
        return self.macros.contains(name);
    }

    /// Get a user-defined derive macro by name.
    pub fn get(self: *const DeriveRegistry, name: []const u8) ?DeriveMacro {
        return self.macros.get(name);
    }

    pub fn count(self: *const DeriveRegistry) usize {
        return self.macros.count();
    }

    /// Check if a derive macro name is registered.
    pub fn exists(self: *const DeriveRegistry, name: []const u8) bool {
        return self.macros.contains(name);
    }

    /// Return a freshly allocated slice of all registered derive macro names.
    pub fn listNames(self: *const DeriveRegistry, alloc: std.mem.Allocator) ![]const []const u8 {
        var names: std.ArrayListUnmanaged([]const u8) = .empty;
        errdefer {
            for (names.items) |n| alloc.free(n);
            names.deinit(alloc);
        }
        var it = self.macros.keyIterator();
        while (it.next()) |key_ptr| {
            try names.append(alloc, try alloc.dupe(u8, key_ptr.*));
        }
        return try names.toOwnedSlice(alloc);
    }
};

/// Built-in derive traits that are always available (not user-extensible).
pub const builtin_derives = [_][]const u8{
    "Display",    "Eq",        "Ord",         "Hash",    "Clone",
    "Default",    "Add",       "Sub",         "Mul",     "Div",
    "Rem",        "Neg",       "BitAnd",      "BitOr",   "BitXor",
    "BitNot",     "Shl",       "Shr",         "Len",     "AsInt",
    "FromInt",    "Serialize", "Deserialize", "Builder", "PartialEq",
    "PartialOrd", "FromStr",   "IntoStr",
};

/// Check if a derive name is a built-in.
pub fn isBuiltinDerive(name: []const u8) bool {
    for (builtin_derives) |builtin| {
        if (std.mem.eql(u8, name, builtin)) return true;
    }
    return false;
}

/// Type metadata passed to user-defined derive macros at comptime.
pub const TypeMetadata = struct {
    type_name: []const u8,
    fields: []const FieldMeta,
    methods: []const MethodMeta,

    pub const FieldMeta = struct {
        name: []const u8,
        type_name: []const u8,
    };

    pub const MethodMeta = struct {
        name: []const u8,
        return_type: []const u8,
    };
};

/// Parameterized derive config - allows derive macros to accept configuration
pub const DeriveConfig = struct {
    /// Base derive name (e.g., "Fieldwise")
    name: []const u8,
    /// Configuration table passed to the macro
    config: ?DeriveConfigValue = null,
};

/// Simple value type for derive config (separate from comptime eval to avoid import cycles)
pub const DeriveConfigValue = union(enum) {
    nil,
    string: []const u8,
    int: i64,
    float: f64,
    table: []const struct { key: []const u8, val: DeriveConfigValue },
};

fn fieldwiseOpName(op: []const u8) []const u8 {
    if (std.mem.eql(u8, op, "+")) return "add";
    if (std.mem.eql(u8, op, "-")) return "sub";
    if (std.mem.eql(u8, op, "*")) return "mul";
    if (std.mem.eql(u8, op, "/")) return "div";
    if (std.mem.eql(u8, op, "%")) return "rem";
    if (std.mem.eql(u8, op, "&")) return "bitand";
    if (std.mem.eql(u8, op, "|")) return "bitor";
    if (std.mem.eql(u8, op, "^")) return "bitxor";
    if (std.mem.eql(u8, op, "<<")) return "shl";
    if (std.mem.eql(u8, op, ">>")) return "shr";
    return op;
}

/// Generate operator implementations for all numeric fields (exponential derive!)
/// This creates one derive that produces N operator implementations for N fields.
pub fn generateFieldwiseOps(alloc: std.mem.Allocator, meta: TypeMetadata, op: []const u8) ![]const u8 {
    var buf: std.Io.Writer.Allocating = .init(alloc);
    errdefer buf.deinit();
    const w = &buf.writer;

    // Count numeric fields
    var numeric_fields: std.ArrayListUnmanaged([]const u8) = .empty;
    defer numeric_fields.deinit(alloc);
    for (meta.fields) |field| {
        const t = field.type_name;
        if (std.mem.indexOf(u8, t, "int") != null or
            std.mem.indexOf(u8, t, "float") != null or
            std.mem.indexOf(u8, t, "double") != null or
            std.mem.indexOf(u8, t, "f32") != null or
            std.mem.indexOf(u8, t, "f64") != null)
        {
            try numeric_fields.append(alloc, field.name);
        }
    }
    if (numeric_fields.items.len == 0) return try alloc.dupe(u8, "");

    const op_name = fieldwiseOpName(op);
    // Generate operator function for this type
    try w.print("static {s} {s}_{s}({s} lhs, {s} rhs) {{\n", .{ meta.type_name, meta.type_name, op_name, meta.type_name, meta.type_name });
    try w.print("    {s} result;\n", .{meta.type_name});

    for (numeric_fields.items) |field_name| {
        try w.print("    result.{s} = lhs.{s} {s} rhs.{s};\n", .{ field_name, field_name, op, field_name });
    }

    try w.print("    return result;\n", .{});
    try w.print("}}\n", .{});

    return buf.toOwnedSlice();
}

/// Serialize type metadata to a Lua table string for comptime evaluation.
/// NOTE: This is DEPRECATED — use generateBuiltinDerive for native codegen paths.
/// Kept only for backward compatibility with user-defined derive macros.
pub fn serializeMetadataToLua(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);

    try buf.appendSlice(alloc, "{ name = \"");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "\", fields = {");

    for (meta.fields, 0..) |field, i| {
        if (i > 0) try buf.appendSlice(alloc, ", ");
        try buf.appendSlice(alloc, "{ name = \"");
        try buf.appendSlice(alloc, field.name);
        try buf.appendSlice(alloc, "\", type = \"");
        try buf.appendSlice(alloc, field.type_name);
        try buf.appendSlice(alloc, "\" }");
    }

    try buf.appendSlice(alloc, "}, methods = {");
    for (meta.methods, 0..) |method, i| {
        if (i > 0) try buf.appendSlice(alloc, ", ");
        try buf.appendSlice(alloc, "{ name = \"");
        try buf.appendSlice(alloc, method.name);
        try buf.appendSlice(alloc, "\", return_type = \"");
        try buf.appendSlice(alloc, method.return_type);
        try buf.appendSlice(alloc, "\" }");
    }

    try buf.appendSlice(alloc, "}}");
    return try buf.toOwnedSlice(alloc);
}

/// Helper to generate a simple derive body from metadata.
/// This creates a C function that generates a string representation of the type.
pub fn generateSimpleDeriveBody(alloc: std.mem.Allocator, meta: TypeMetadata) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    errdefer buf.deinit(alloc);

    // Generate a C function that returns a string representation
    try buf.appendSlice(alloc, "static char* ");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "_to_string() {\n");
    try buf.appendSlice(alloc, "    static char buf[256];\n");
    try buf.appendSlice(alloc, "    snprintf(buf, sizeof(buf), \"");
    try buf.appendSlice(alloc, meta.type_name);
    try buf.appendSlice(alloc, "(");
    for (meta.fields, 0..) |field, i| {
        if (i > 0) try buf.appendSlice(alloc, ", ");
        try buf.appendSlice(alloc, field.name);
        try buf.appendSlice(alloc, "=%s");
    }
    try buf.appendSlice(alloc, ")\"");
    for (meta.fields) |field| {
        try buf.appendSlice(alloc, ", meta.");
        try buf.appendSlice(alloc, field.name);
    }
    try buf.appendSlice(alloc, ");\n");
    try buf.appendSlice(alloc, "    return buf;\n");
    try buf.appendSlice(alloc, "}\n");

    return try buf.toOwnedSlice(alloc);
}

test "derive_registry: register and lookup" {
    var reg = DeriveRegistry.init(std.testing.allocator);
    defer reg.deinit();

    try reg.register("Printable", "fun generate(meta) return 'code' end", .{ .file = "test", .line = 1, .col = 1 });
    try std.testing.expect(reg.isUserDefined("Printable"));
    try std.testing.expect(!reg.isUserDefined("Display"));
    try std.testing.expectEqual(@as(usize, 1), reg.count());

    const m = reg.get("Printable");
    try std.testing.expect(m != null);
    try std.testing.expectEqualStrings("fun generate(meta) return 'code' end", m.?.func_source);
}

test "derive_registry: overwrite existing" {
    var reg = DeriveRegistry.init(std.testing.allocator);
    defer reg.deinit();

    try reg.register("Printable", "fun generate(meta) return 'v1' end", .{ .file = "test", .line = 1, .col = 1 });
    try reg.register("Printable", "fun generate(meta) return 'v2' end", .{ .file = "test", .line = 2, .col = 1 });
    try std.testing.expectEqual(@as(usize, 1), reg.count());
    try std.testing.expectEqualStrings("fun generate(meta) return 'v2' end", reg.get("Printable").?.func_source);
}

test "derive_registry: isBuiltinDerive" {
    try std.testing.expect(isBuiltinDerive("Display"));
    try std.testing.expect(isBuiltinDerive("Serialize"));
    try std.testing.expect(!isBuiltinDerive("Printable"));
    try std.testing.expect(!isBuiltinDerive("ToSql"));
}

test "derive_registry: serializeMetadataToLua" {
    const alloc = std.testing.allocator;
    const meta = TypeMetadata{
        .type_name = "Vec2",
        .fields = &.{
            .{ .name = "x", .type_name = "f64" },
            .{ .name = "y", .type_name = "f64" },
        },
        .methods = &.{},
    };
    const lua = try serializeMetadataToLua(alloc, meta);
    defer alloc.free(lua);
    try std.testing.expectEqualStrings(
        \\{ name = "Vec2", fields = {{ name = "x", type = "f64" }, { name = "y", type = "f64" }}, methods = {}}
    , lua);
}

test "derive_registry: fieldwise ops generates code for numeric fields" {
    const alloc = std.testing.allocator;
    const meta = TypeMetadata{
        .type_name = "Point3D",
        .fields = &.{
            .{ .name = "x", .type_name = "double" },
            .{ .name = "y", .type_name = "double" },
            .{ .name = "z", .type_name = "double" },
        },
        .methods = &.{},
    };
    const code = try generateFieldwiseOps(alloc, meta, "+");
    defer alloc.free(code);
    try std.testing.expect(std.mem.indexOf(u8, code, "Point3D_add") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "result.x = lhs.x + rhs.x") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "result.y = lhs.y + rhs.y") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "result.z = lhs.z + rhs.z") != null);
}

test "derive_registry: native derive fast path" {
    const alloc = std.testing.allocator;
    const meta = TypeMetadata{
        .type_name = "Vec2",
        .fields = &.{
            .{ .name = "x", .type_name = "double" },
            .{ .name = "y", .type_name = "double" },
        },
        .methods = &.{},
    };
    // Test native Eq derive
    const eq_code = try generateEq(alloc, meta);
    defer alloc.free(eq_code);
    try std.testing.expect(std.mem.indexOf(u8, eq_code, "Vec2_eq") != null);
    try std.testing.expect(std.mem.indexOf(u8, eq_code, "a->x == b->x") != null);
    try std.testing.expect(std.mem.indexOf(u8, eq_code, "a->y == b->y") != null);

    // Test native Clone derive
    const clone_code = try generateClone(alloc, meta);
    defer alloc.free(clone_code);
    try std.testing.expect(std.mem.indexOf(u8, clone_code, "Vec2_clone") != null);
    try std.testing.expect(std.mem.indexOf(u8, clone_code, "dst.x = src->x") != null);
}
