//! GAP-134 — grammar-role ACCESSORS over the one Idol grammar-fact owner.
//! The facts live in `lib/compiler/token.id` (`law.grammar.one`); this file
//! holds no role of its own. `src/grammar_role_table.zig` is the generated
//! bridge (`law.bridge.death`) that carries them into the host parser.
//! Damaging a role in the Idol owner and regenerating changes what this
//! compiler accepts — that counterfactual is the point of the split.
const std = @import("std");
const lexer = @import("lexer.zig");
const table = @import("grammar_role_table.zig");

pub const SCHEMA_VERSION = "grammar-role-v1";

/// Re-exported from the generated table. Every one of these is a projection
/// of the Idol owner; nothing here may be edited to change a grammar fact.
pub const Associativity = table.Associativity;
pub const RoleRow = table.RoleRow;
/// The relation ontology, generated by the same owner as the roles.
pub const Relation = table.Relation;
pub const Prefix = table.Prefix;
pub const slot_count = table.slot_count;
pub const rows = table.rows;

test "grammar roles: token identity is generated by the owner projection" {
    try std.testing.expect(@hasDecl(table, "TokenKind"));
    try std.testing.expect(lexer.TokenKind == table.TokenKind);
}

pub fn lookup(kind: lexer.TokenKind) RoleRow {
    return rows[@backingInt(kind)];
}

pub fn canBeginExpression(kind: lexer.TokenKind) bool {
    return lookup(kind).begin_expr;
}

/// Literal tokens that may appear as call operands but never in a parameter list.
pub fn isLiteralKind(kind: lexer.TokenKind) bool {
    return lookup(kind).literal_kind;
}

/// Quoted payload identities (text/bytes/compat). Slot 3 is unpublished.
pub fn isQuotedKind(kind: lexer.TokenKind) bool {
    return lookup(kind).quoted;
}

/// Binary/assignment operators that disqualify a paren group from being a param list.
/// Infix operator identity — associativity is the fact, not token text.
pub fn isInfix(kind: lexer.TokenKind) bool {
    return lookup(kind).assoc != .none;
}

pub fn canStartBody(kind: lexer.TokenKind) bool {
    return lookup(kind).body_start;
}

/// MAY CANONICAL TOOLING WRITE THIS SPELLING? (HPLS §94.)
///
/// The parser still ACCEPTS every compat-only spelling — acceptance and
/// emission are different questions, and collapsing them is how "the current
/// compiler cannot do X" turns into "Idol should not permit X". This answers
/// only the second: a formatter, an LSP code action, a doc generator or an MCP
/// surface that writes a token this returns `false` for is generating retired
/// syntax from canonical tooling, which §94 forbids.
///
/// It exists because `compat_only` had ZERO consumers while three separate
/// enforcers each held a private copy of the same fact.
pub fn admits(kind: lexer.TokenKind) bool {
    return !lookup(kind).compat_only;
}

/// Primitive descriptor identities (`i64`, `str`, …) — not a spelling list.
pub fn isDescriptor(kind: lexer.TokenKind) bool {
    return lookup(kind).descriptor;
}

/// Match-pattern start — generated fact, not a parser kind list.
pub fn canStartPattern(kind: lexer.TokenKind) bool {
    return lookup(kind).pattern;
}

/// ONE OPERATION ONTOLOGY.
///
/// `a + b`, `a += b` and `a >>= b` are three SOURCE FACES of one relation, so
/// they read one fact — `relation` — and differ only in which face the owner
/// admits for that identity. The parser used to hold three private
/// `TokenKind => Relation` switches (24 + 6 + 5 arms) that had to agree with
/// each other and with the precedence table; `Relation` is now the physical
/// encoding of the owner's relation identity, not a second naming of it.
///
/// The infix face: which relation this identity applies between two operands.
pub fn infixRelation(kind: lexer.TokenKind) ?Relation {
    const r = lookup(kind);
    if (!r.infix) return null;
    return r.relation;
}

/// The single-token compound-update face (`+=`): the relation it updates by.
/// `plus_assign` carries the SAME relation as `plus`; the face is the only
/// thing that differs, which is why it is a separate fact and not a
/// separate operation.
pub fn updateRelation(kind: lexer.TokenKind) ?Relation {
    const r = lookup(kind);
    if (!r.update) return null;
    return r.relation;
}

/// The adjacency-glued compound-update face (`>>=` is `>>` then a glued `=`).
/// The lexer mints no token for it, so which identities admit the face is a
/// grammar fact. Adjacency itself stays a parser observation over spans.
pub fn gluedRelation(kind: lexer.TokenKind) ?Relation {
    const r = lookup(kind);
    if (!r.glue) return null;
    return r.relation;
}

/// The prefix face. `-` and `~` carry BOTH a prefix and an infix relation;
/// `unary` and `relation` are therefore two facts on one row, never one map
/// consulted twice.
pub fn unaryRelation(kind: lexer.TokenKind) ?Prefix {
    return lookup(kind).unary;
}

test "grammar roles: identity not spelling drives prefix on dot" {
    try std.testing.expect(lookup(.dot).postfix);
    try std.testing.expect(!lookup(.dot).prefix);
}

test "grammar roles: backtick is compat-only and not expression-start" {
    const r = lookup(.backtick);
    try std.testing.expect(r.compat_only);
    try std.testing.expect(!r.begin_expr);
}

test "grammar roles: text and bytes both begin expressions" {
    try std.testing.expect(canBeginExpression(.text_lit));
    try std.testing.expect(canBeginExpression(.bytes_lit));
    try std.testing.expect(canBeginExpression(.compat_text_lit));
    try std.testing.expect(isQuotedKind(.text_lit));
    try std.testing.expect(isQuotedKind(.bytes_lit));
    try std.testing.expect(!isQuotedKind(.int_lit));
}

test "grammar roles: expression start and compatibility are independent facts" {
    try std.testing.expect(canBeginExpression(.kw_function));
    try std.testing.expect(lookup(.kw_function).compat_only);
    try std.testing.expect(canBeginExpression(.kw_if));
    try std.testing.expect(!lookup(.kw_if).compat_only);
    try std.testing.expect(canBeginExpression(.pipe));
    try std.testing.expect(canBeginExpression(.dot));
    try std.testing.expect(canBeginExpression(.colon));
    try std.testing.expect(canBeginExpression(.kw_i64));
    try std.testing.expect(!canBeginExpression(.lbracket));
    try std.testing.expect(!canBeginExpression(.comma));
}

test "grammar roles: shebang and comments are trivia not expression-start" {
    try std.testing.expect(!canBeginExpression(.shebang));
    try std.testing.expect(!canBeginExpression(.comment));
    try std.testing.expect(!canBeginExpression(.compat_comment));
    try std.testing.expect(!canBeginExpression(.compat_long_comment));
    try std.testing.expect(lookup(.compat_comment).compat_only);
    try std.testing.expect(!lookup(.shebang).compat_only);
}

test "grammar roles: long text is a literal body start by identity" {
    try std.testing.expect(isLiteralKind(.compat_long_text_lit));
    try std.testing.expect(canStartBody(.compat_long_text_lit));
    try std.testing.expect(canStartBody(.text_lit));
    try std.testing.expect(canStartBody(.bytes_lit));
}

test "grammar roles: prefix operators begin expressions by identity" {
    try std.testing.expect(lookup(.hash).prefix);
    try std.testing.expect(lookup(.minus).prefix);
    try std.testing.expect(lookup(.bang).prefix);
    try std.testing.expect(!lookup(.plus).prefix);
}

test "grammar roles: infix is identity not spelling" {
    try std.testing.expect(isInfix(.amp));
    try std.testing.expect(isInfix(.kw_and));
    try std.testing.expect(isInfix(.lt));
    try std.testing.expectEqual(Associativity.nonassoc, lookup(.lt).assoc);
    try std.testing.expect(!isInfix(.bang));
    try std.testing.expect(!isInfix(.dot));
    try std.testing.expectEqualStrings("&", lexer.TokenKind.amp.spelling());
}

test "grammar roles: quoted is identity not spelling" {
    try std.testing.expect(isQuotedKind(.text_lit));
    try std.testing.expect(isQuotedKind(.bytes_lit));
    try std.testing.expect(isQuotedKind(.compat_long_text_lit));
    try std.testing.expect(!isQuotedKind(.int_lit));
    try std.testing.expect(!isQuotedKind(.name));
}

test "grammar roles: descriptor is identity not spelling" {
    try std.testing.expect(isDescriptor(.kw_i64));
    try std.testing.expect(isDescriptor(.kw_str));
    try std.testing.expect(!isDescriptor(.name));
    try std.testing.expect(!isDescriptor(.kw_fun));
}

test "grammar roles: pattern start is identity not a parser list" {
    try std.testing.expect(canStartPattern(.name));
    try std.testing.expect(canStartPattern(.text_lit));
    try std.testing.expect(canStartPattern(.bytes_lit));
    try std.testing.expect(canStartPattern(.lbrace));
    try std.testing.expect(canStartPattern(.minus));
    try std.testing.expect(!canStartPattern(.kw_if));
    try std.testing.expect(!canStartPattern(.lparen));
    try std.testing.expect(!canStartPattern(.plus));
}

test "grammar roles: plus is infix not postfix" {
    try std.testing.expect(isInfix(.plus));
    try std.testing.expect(!isInfix(.dot));
    try std.testing.expect(!isInfix(.bang));
}

test "grammar roles: distinct spellings collapse to one identity and one role" {
    // `!=` is the one inequality spelling; it lexes to the identity `.neq`
    // (src/lexer.zig). Role lookup keys on that identity rather than on the
    // characters, so the role is one row: a nonassoc comparison sharing the
    // `.eq` role class. Holding identity fixed fixes the role — spelling never
    // reaches this table. (`~=` used to be a second spelling of this identity
    // and is now xor-assign, which is exactly the kind of change this
    // separation absorbs without touching the role table.)
    const r = lookup(.neq);
    try std.testing.expect(isInfix(.neq));
    try std.testing.expectEqual(Associativity.nonassoc, r.assoc);
    try std.testing.expectEqual(lookup(.eq).precedence, r.precedence);
    try std.testing.expectEqual(lookup(.eq).assoc, r.assoc);
    try std.testing.expectEqualStrings("!=", lexer.TokenKind.neq.spelling());
}

test "grammar roles: one spelling splits into identities with different roles" {
    // The single character `#` leads three distinct token identities: `.hash`
    // (compatibility length prefix), `.comment` (canonical trivia), and
    // `.shebang` (`#!` at byte zero). Same spelling, different identity,
    // different role — recognition follows identity, never the `#` text.
    try std.testing.expectEqualStrings("#", lexer.TokenKind.hash.spelling());
    try std.testing.expectEqualStrings("#", lexer.TokenKind.comment.spelling());
    try std.testing.expect(canBeginExpression(.hash));
    try std.testing.expect(lookup(.hash).prefix);
    try std.testing.expect(!canBeginExpression(.comment));
    try std.testing.expect(!canBeginExpression(.shebang));
    try std.testing.expect(!lookup(.comment).prefix);
}

test "grammar roles: canonical and compatibility faces stay distinct" {
    // Shared structural role (literal, comment trivia, infix), distinct
    // canonical vs compatibility identity via the compat_only fact.
    try std.testing.expect(!lookup(.text_lit).compat_only);
    try std.testing.expect(lookup(.compat_text_lit).compat_only);
    try std.testing.expect(lookup(.text_lit).quoted and lookup(.compat_text_lit).quoted);

    try std.testing.expect(!lookup(.comment).compat_only);
    try std.testing.expect(lookup(.compat_comment).compat_only);

    try std.testing.expect(isInfix(.pipe) and !lookup(.pipe).compat_only);
    try std.testing.expect(isInfix(.kw_or) and lookup(.kw_or).compat_only);
    try std.testing.expect(isInfix(.amp) and !lookup(.amp).compat_only);
    try std.testing.expect(isInfix(.kw_and) and lookup(.kw_and).compat_only);
}

test "grammar roles: every token identity has one ordinal row" {
    const enum_info = @typeInfo(lexer.TokenKind).@"enum";
    try std.testing.expectEqual(enum_info.field_names.len + 1, rows.len);
    inline for (enum_info.field_values) |value| {
        const kind: lexer.TokenKind = @fromBackingInt(@intCast(value));
        try std.testing.expectEqual(kind, lookup(kind).kind.?);
    }
}

test "grammar roles: unpublished producer slot has no token identity or role" {
    try std.testing.expect(!@hasField(lexer.TokenKind, "string_lit"));
    try std.testing.expectEqual(@as(usize, 4), @backingInt(lexer.TokenKind.kw_and));
    try std.testing.expect(rows[3].kind == null);
    try std.testing.expect(!rows[3].begin_expr);
    try std.testing.expect(!rows[3].literal_kind);
    try std.testing.expect(!rows[3].quoted);
}

test "grammar roles: every relation identity is owned by exactly one infix token" {
    // The closure control for the deleted `Parser.infixBinOp`. A relation the
    // owner never names would leave the parser unable to build it; a relation
    // named twice would give one operation two binding powers. Both are
    // failures here rather than a silently wrong program.
    var seen = std.EnumMap(Relation, lexer.TokenKind){};
    for (rows) |r| {
        const kind = r.kind orelse continue;
        const rel = infixRelation(kind) orelse continue;
        try std.testing.expect(seen.get(rel) == null);
        seen.put(rel, kind);
    }
    inline for (@typeInfo(Relation).@"enum".field_names) |nm| {
        try std.testing.expect(seen.get(@field(Relation, nm)) != null);
    }
}

test "grammar roles: every prefix relation is owned by at least one identity" {
    var seen = std.EnumSet(Prefix){};
    for (rows) |r| {
        const kind = r.kind orelse continue;
        if (unaryRelation(kind)) |u| seen.insert(u);
    }
    inline for (@typeInfo(Prefix).@"enum".field_names) |nm| {
        try std.testing.expect(seen.contains(@field(Prefix, nm)));
    }
}

test "grammar roles: one identity may carry a prefix and an infix relation" {
    // `~` and `-` are the two. Holding the identity fixed, the two faces are
    // separate facts; nothing here reads the character.
    try std.testing.expectEqual(Relation.bxor, infixRelation(.tilde).?);
    try std.testing.expectEqual(Prefix.bnot, unaryRelation(.tilde).?);
    try std.testing.expectEqual(Relation.sub, infixRelation(.minus).?);
    try std.testing.expectEqual(Prefix.neg, unaryRelation(.minus).?);
    // `+` has no prefix face and `#` has no infix one.
    try std.testing.expect(unaryRelation(.plus) == null);
    try std.testing.expect(infixRelation(.hash) == null);
}

test "grammar roles: update faces share their relation and are not infix" {
    // `a += b` and `a + b` request the SAME relation. If the update face were
    // a second operation the two could drift; sharing the row makes that
    // unrepresentable.
    try std.testing.expectEqual(infixRelation(.plus).?, updateRelation(.plus_assign).?);
    try std.testing.expectEqual(infixRelation(.caret).?, updateRelation(.caret_assign).?);
    try std.testing.expect(infixRelation(.plus_assign) == null);
    try std.testing.expect(updateRelation(.plus) == null);
    // Plain `=` requests no relation at all — absent is not `add`.
    try std.testing.expect(infixRelation(.assign) == null);
    try std.testing.expect(updateRelation(.assign) == null);
    try std.testing.expect(lookup(.assign).relation == null);
}

test "grammar roles: the glued update face is the identity's own relation" {
    // `>>=` is `>>` with a glued `=`; the relation is `>>`'s, and only the
    // five identities the owner admits carry the face.
    try std.testing.expectEqual(Relation.rshift, gluedRelation(.rshift).?);
    try std.testing.expectEqual(infixRelation(.pipe).?, gluedRelation(.pipe).?);
    try std.testing.expectEqual(infixRelation(.amp).?, gluedRelation(.amp).?);
    try std.testing.expectEqual(infixRelation(.tilde).?, gluedRelation(.tilde).?);
    try std.testing.expectEqual(infixRelation(.lshift).?, gluedRelation(.lshift).?);
    try std.testing.expect(gluedRelation(.plus) == null);
    try std.testing.expect(gluedRelation(.caret) == null);
}

test "grammar roles: relation identity is held by ordinal, never by spelling" {
    // `!=` and the retired `~=` are one identity; `@` is `matmul` infix and
    // an attribute prefix elsewhere. Neither answer comes from the text.
    try std.testing.expectEqual(Relation.neq, infixRelation(.neq).?);
    try std.testing.expectEqualStrings("!=", lexer.TokenKind.neq.spelling());
    try std.testing.expectEqual(Relation.matmul, infixRelation(.at).?);
    try std.testing.expect(unaryRelation(.at) == null);
}

test "grammar roles: the demand fact is the exact dual of expression start" {
    // 48 identities that cannot END an expression. `(`, `[`, `,`, `:`, `->`,
    // `=>` and the control words demand an operand without applying any
    // relation, which is why this is its own fact and not `infix or prefix`.
    try std.testing.expect(lookup(.lparen).demands_operand);
    try std.testing.expect(lookup(.comma).demands_operand);
    try std.testing.expect(lookup(.arrow).demands_operand);
    try std.testing.expect(lookup(.kw_return).demands_operand);
    try std.testing.expect(lookup(.kw_by).demands_operand);
    try std.testing.expect(lookup(.plus_assign).demands_operand);
    // A closer, a literal and a name all END an expression.
    try std.testing.expect(!lookup(.rparen).demands_operand);
    try std.testing.expect(!lookup(.rbracket).demands_operand);
    try std.testing.expect(!lookup(.name).demands_operand);
    try std.testing.expect(!lookup(.int_lit).demands_operand);
    try std.testing.expect(!lookup(.eof).demands_operand);
    // `{` is deliberately absent: a brace opens a REGION of slots, not one
    // demanded operand.
    try std.testing.expect(!lookup(.lbrace).demands_operand);
    // `..` (dots) is absent too — it is a complete operand on its own.
    try std.testing.expect(!lookup(.dots).demands_operand);
    var n: usize = 0;
    for (rows) |r| {
        if (r.kind != null and r.demands_operand) n += 1;
    }
    try std.testing.expectEqual(@as(usize, 48), n);
}

test "grammar roles: only a two-faced identity opens a line" {
    // A line-leading `*` can only continue the line above; a line-leading `-`
    // could be either, and the wrong answer there silently deleted a tail
    // expression (see Parser.opensLineAndExpression).
    try std.testing.expect(lookup(.minus).opens_line);
    try std.testing.expect(lookup(.tilde).opens_line);
    try std.testing.expect(lookup(.at).opens_line);
    try std.testing.expect(!lookup(.star).opens_line);
    try std.testing.expect(!lookup(.plus).opens_line);
    try std.testing.expect(!lookup(.pipe).opens_line);
    // Every one of them is infix, which is what makes it ambiguous at all.
    for (rows) |r| {
        if (r.kind != null and r.opens_line) try std.testing.expect(r.infix);
    }
}

test "grammar roles: source spelling has one producer and it is the owner" {
    // `lexer.zig` answers out of the generated row now, so this pins the row
    // against the identities themselves rather than against a second switch.
    try std.testing.expectEqualStrings("+", lexer.TokenKind.plus.spelling());
    try std.testing.expectEqualStrings("!=", lexer.TokenKind.neq.spelling());
    try std.testing.expectEqualStrings("..", lexer.TokenKind.concat.spelling());
    try std.testing.expectEqualStrings("@", lexer.TokenKind.at.spelling());
    try std.testing.expectEqualStrings("and", lexer.TokenKind.kw_and.spelling());
    try std.testing.expectEqualStrings("<eof>", lexer.TokenKind.eof.spelling());
    // Slot 3 is unpublished and its spelling field is empty — not ".", which
    // is the real spelling of `dot` and would collide with a live identity.
    try std.testing.expectEqualStrings("", rows[3].spell);
}
