// GENERATED from lib/compiler/token.id — do not edit by hand.
// Regenerate: idol run lib/compiler/token.id
// One executable grammar-fact owner (law.grammar.one). This table is
// a bridge (law.bridge.death), not an authority: change a role in the
// Idol owner and regenerate. Editing this file by hand is a second
// producer of one grammar fact.
const lexer = @import("lexer.zig");

pub const Associativity = enum(u8) {
    none = 0,
    left = 1,
    right = 2,
    nonassoc = 3,
};

pub const RoleRow = struct {
    kind: ?lexer.TokenKind = null,
    begin_expr: bool = false,
    prefix: bool = false,
    postfix: bool = false,
    parameter: bool = false,
    literal_kind: bool = false,
    projection: bool = false,
    body_start: bool = false,
    quoted: bool = false,
    descriptor: bool = false,
    pattern: bool = false,
    precedence: i8 = 0,
    assoc: Associativity = .none,
    compat_only: bool = false,
};

pub const slot_count: usize = 114;
pub const identity_count: usize = 113;
pub const kind_eof: usize = 109;

pub const rows = [slot_count]RoleRow{
    .{ .kind = .name, .begin_expr = true, .body_start = true, .pattern = true },
    .{ .kind = .int_lit, .begin_expr = true, .literal_kind = true, .body_start = true, .pattern = true },
    .{ .kind = .float_lit, .begin_expr = true, .literal_kind = true, .body_start = true, .pattern = true },
    .{ .kind = null },
    .{ .kind = .kw_and, .precedence = 4, .assoc = .left, .compat_only = true },
    .{ .kind = .kw_break, .body_start = true },
    .{ .kind = .kw_continue, .body_start = true },
    .{ .kind = .kw_do, .body_start = true, .compat_only = true },
    .{ .kind = .kw_else },
    .{ .kind = .kw_elseif, .compat_only = true },
    .{ .kind = .kw_end, .compat_only = true },
    .{ .kind = .kw_false, .begin_expr = true, .body_start = true, .pattern = true, .compat_only = true },
    .{ .kind = .kw_for, .body_start = true },
    .{ .kind = .kw_function, .begin_expr = true, .body_start = true, .compat_only = true },
    .{ .kind = .kw_fun, .begin_expr = true, .body_start = true, .compat_only = true },
    .{ .kind = .kw_global },
    .{ .kind = .kw_goto },
    .{ .kind = .kw_if, .begin_expr = true, .body_start = true },
    .{ .kind = .kw_in, .precedence = 6, .assoc = .nonassoc },
    .{ .kind = .kw_local, .compat_only = true },
    .{ .kind = .kw_nil, .begin_expr = true, .body_start = true, .pattern = true, .compat_only = true },
    .{ .kind = .kw_not, .begin_expr = true, .prefix = true, .body_start = true, .precedence = 9 },
    .{ .kind = .kw_or, .precedence = 2, .assoc = .left, .compat_only = true },
    .{ .kind = .kw_repeat },
    .{ .kind = .kw_return, .body_start = true },
    .{ .kind = .kw_then, .compat_only = true },
    .{ .kind = .kw_true, .begin_expr = true, .body_start = true, .pattern = true, .compat_only = true },
    .{ .kind = .kw_until },
    .{ .kind = .kw_while, .body_start = true },
    .{ .kind = .kw_const, .compat_only = true },
    .{ .kind = .kw_enum },
    .{ .kind = .kw_i8, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_i16, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_i32, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_i64, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_u8, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_u16, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_u32, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_u64, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_f32, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_f64, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_bool, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_void, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_str, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_match, .begin_expr = true, .body_start = true },
    .{ .kind = .kw_try },
    .{ .kind = .kw_catch },
    .{ .kind = .kw_defer },
    .{ .kind = .kw_async },
    .{ .kind = .kw_await, .begin_expr = true, .prefix = true },
    .{ .kind = .kw_concept },
    .{ .kind = .kw_alias },
    .{ .kind = .kw_private },
    .{ .kind = .kw_extends },
    .{ .kind = .kw_macro },
    .{ .kind = .kw_comptime, .begin_expr = true, .prefix = true },
    .{ .kind = .kw_by },
    .{ .kind = .kw_let, .compat_only = true },
    .{ .kind = .lparen, .begin_expr = true, .prefix = true, .body_start = true },
    .{ .kind = .rparen },
    .{ .kind = .lbracket, .projection = true, .pattern = true },
    .{ .kind = .rbracket },
    .{ .kind = .lbrace, .begin_expr = true, .body_start = true, .pattern = true },
    .{ .kind = .rbrace },
    .{ .kind = .plus, .precedence = 17, .assoc = .left },
    .{ .kind = .minus, .begin_expr = true, .prefix = true, .body_start = true, .pattern = true, .precedence = 17, .assoc = .left },
    .{ .kind = .star, .precedence = 19, .assoc = .left },
    .{ .kind = .slash, .precedence = 19, .assoc = .left },
    .{ .kind = .percent, .precedence = 19, .assoc = .left },
    .{ .kind = .caret, .precedence = 23, .assoc = .right },
    .{ .kind = .hash, .begin_expr = true, .prefix = true, .body_start = true, .compat_only = true },
    .{ .kind = .amp, .precedence = 11, .assoc = .left },
    .{ .kind = .pipe, .begin_expr = true, .body_start = true, .precedence = 7, .assoc = .left },
    .{ .kind = .lt, .precedence = 6, .assoc = .nonassoc },
    .{ .kind = .gt, .precedence = 6, .assoc = .nonassoc },
    .{ .kind = .assign, .precedence = 1, .assoc = .right },
    .{ .kind = .tilde, .begin_expr = true, .prefix = true, .precedence = 9, .assoc = .left },
    .{ .kind = .semi },
    .{ .kind = .colon, .begin_expr = true, .parameter = true, .projection = true },
    .{ .kind = .comma },
    .{ .kind = .dot, .begin_expr = true, .postfix = true, .projection = true, .precedence = 10 },
    .{ .kind = .at, .begin_expr = true, .body_start = true, .precedence = 19, .assoc = .left },
    .{ .kind = .question },
    .{ .kind = .bang, .begin_expr = true, .prefix = true, .precedence = 9 },
    .{ .kind = .backtick, .compat_only = true },
    .{ .kind = .concat, .precedence = 16, .assoc = .right, .compat_only = true },
    .{ .kind = .dots, .begin_expr = true, .pattern = true },
    .{ .kind = .hash_hash, .begin_expr = true, .prefix = true, .compat_only = true },
    .{ .kind = .eq, .precedence = 6, .assoc = .nonassoc },
    .{ .kind = .neq, .precedence = 6, .assoc = .nonassoc },
    .{ .kind = .leq, .precedence = 6, .assoc = .nonassoc },
    .{ .kind = .geq, .precedence = 6, .assoc = .nonassoc },
    .{ .kind = .lshift, .precedence = 13, .assoc = .left },
    .{ .kind = .rshift, .precedence = 13, .assoc = .left },
    .{ .kind = .idiv, .precedence = 19, .assoc = .left },
    .{ .kind = .dcolon },
    .{ .kind = .arrow },
    .{ .kind = .pipe_gt, .precedence = 1, .assoc = .left },
    .{ .kind = .fat_arrow },
    .{ .kind = .plus_assign, .precedence = 1, .assoc = .right },
    .{ .kind = .minus_assign, .precedence = 1, .assoc = .right },
    .{ .kind = .star_assign, .precedence = 1, .assoc = .right },
    .{ .kind = .slash_assign, .precedence = 1, .assoc = .right },
    .{ .kind = .percent_assign, .precedence = 1, .assoc = .right },
    .{ .kind = .caret_assign, .precedence = 1, .assoc = .right },
    .{ .kind = .text_lit, .begin_expr = true, .literal_kind = true, .body_start = true, .quoted = true, .pattern = true },
    .{ .kind = .bytes_lit, .begin_expr = true, .literal_kind = true, .body_start = true, .quoted = true, .pattern = true },
    .{ .kind = .compat_text_lit, .begin_expr = true, .literal_kind = true, .body_start = true, .quoted = true, .pattern = true, .compat_only = true },
    .{ .kind = .compat_long_text_lit, .begin_expr = true, .literal_kind = true, .body_start = true, .quoted = true, .pattern = true, .compat_only = true },
    .{ .kind = .eof },
    .{ .kind = .shebang },
    .{ .kind = .comment },
    .{ .kind = .compat_comment, .compat_only = true },
    .{ .kind = .compat_long_comment, .compat_only = true },
};
