// GENERATED from lib/compiler/token.id — do not edit by hand.
// Regenerate: idol run lib/compiler/token.id
// One executable grammar-fact owner (law.grammar.one). This table is
// a bridge (law.bridge.death), not an authority: change a role in the
// Idol owner and regenerate. Editing this file by hand is a second
// producer of one grammar fact.
// Token identity lives here too: the producer slot is its physical value.
pub const TokenKind = enum(u8) {
    name = 0,
    int_lit = 1,
    float_lit = 2,
    kw_and = 4,
    kw_break = 5,
    kw_continue = 6,
    kw_do = 7,
    kw_else = 8,
    kw_elseif = 9,
    kw_end = 10,
    kw_false = 11,
    kw_for = 12,
    kw_function = 13,
    kw_fun = 14,
    kw_global = 15,
    kw_goto = 16,
    kw_if = 17,
    kw_in = 18,
    kw_local = 19,
    kw_nil = 20,
    kw_not = 21,
    kw_or = 22,
    kw_repeat = 23,
    kw_return = 24,
    kw_then = 25,
    kw_true = 26,
    kw_until = 27,
    kw_while = 28,
    kw_const = 29,
    kw_enum = 30,
    kw_i8 = 31,
    kw_i16 = 32,
    kw_i32 = 33,
    kw_i64 = 34,
    kw_u8 = 35,
    kw_u16 = 36,
    kw_u32 = 37,
    kw_u64 = 38,
    kw_f32 = 39,
    kw_f64 = 40,
    kw_bool = 41,
    kw_void = 42,
    kw_str = 43,
    kw_match = 44,
    kw_try = 45,
    kw_catch = 46,
    kw_defer = 47,
    kw_async = 48,
    kw_await = 49,
    kw_concept = 50,
    kw_alias = 51,
    kw_private = 52,
    kw_extends = 53,
    kw_macro = 54,
    kw_comptime = 55,
    kw_by = 56,
    kw_let = 57,
    lparen = 58,
    rparen = 59,
    lbracket = 60,
    rbracket = 61,
    lbrace = 62,
    rbrace = 63,
    plus = 64,
    minus = 65,
    star = 66,
    slash = 67,
    percent = 68,
    caret = 69,
    hash = 70,
    amp = 71,
    pipe = 72,
    lt = 73,
    gt = 74,
    assign = 75,
    tilde = 76,
    semi = 77,
    colon = 78,
    comma = 79,
    dot = 80,
    at = 81,
    question = 82,
    bang = 83,
    backtick = 84,
    concat = 85,
    dots = 86,
    hash_hash = 87,
    eq = 88,
    neq = 89,
    leq = 90,
    geq = 91,
    lshift = 92,
    rshift = 93,
    idiv = 94,
    dcolon = 95,
    arrow = 96,
    pipe_gt = 97,
    fat_arrow = 98,
    plus_assign = 99,
    minus_assign = 100,
    star_assign = 101,
    slash_assign = 102,
    percent_assign = 103,
    caret_assign = 104,
    text_lit = 105,
    bytes_lit = 106,
    compat_text_lit = 107,
    compat_long_text_lit = 108,
    eof = 109,
    shebang = 110,
    comment = 111,
    compat_comment = 112,
    compat_long_comment = 113,

    pub fn spelling(self: TokenKind) []const u8 {
        return rows[@backingInt(self)].spell;
    }
};

// Relation identity lives in the TOKEN layer. src/ast.zig ALIASES these
// two enums; it does not restate them. gate/layers.manifest: the AST
// layer owns shape and no semantic relation identity.
pub const Relation = enum {
    add,
    sub,
    mul,
    div,
    idiv,
    mod,
    pow,
    band,
    bor,
    bxor,
    lshift,
    rshift,
    concat,
    eq,
    neq,
    lt,
    gt,
    leq,
    geq,
    @"and",
    @"or",
    contains,
    matmul,
    pipeline,
};

pub const Prefix = enum {
    neg,
    not,
    len,
    bnot,
    compile,
};

pub const Associativity = enum(u8) {
    none = 0,
    left = 1,
    right = 2,
    nonassoc = 3,
};

pub const RoleRow = struct {
    kind: ?TokenKind = null,
    spell: []const u8 = "",
    keyword: bool = false,
    begin_expr: bool = false,
    prefix: bool = false,
    postfix: bool = false,
    parameter: bool = false,
    literal_kind: bool = false,
    projection: bool = false,
    body_start: bool = false,
    quoted: bool = false,
    descriptor: bool = false,
    pattern: bool = false,
    precedence: i8 = 0,
    assoc: Associativity = .none,
    compat_only: bool = false,
    relation: ?Relation = null,
    unary: ?Prefix = null,
    infix: bool = false,
    update: bool = false,
    glue: bool = false,
    demands_operand: bool = false,
    opens_line: bool = false,
};

pub const slot_count: usize = 114;
pub const identity_count: usize = 113;
pub const kind_eof: usize = 109;

pub const rows = [slot_count]RoleRow{
    .{ .kind = .name, .spell = "name", .begin_expr = true, .body_start = true, .pattern = true },
    .{ .kind = .int_lit, .spell = "integer", .begin_expr = true, .literal_kind = true, .body_start = true, .pattern = true },
    .{ .kind = .float_lit, .spell = "float", .begin_expr = true, .literal_kind = true, .body_start = true, .pattern = true },
    .{ .kind = null },
    .{ .kind = .kw_and, .spell = "and", .keyword = true, .precedence = 4, .assoc = .left, .compat_only = true, .relation = .@"and", .infix = true, .demands_operand = true },
    .{ .kind = .kw_break, .spell = "break", .keyword = true, .body_start = true },
    .{ .kind = .kw_continue, .spell = "continue", .keyword = true, .body_start = true },
    .{ .kind = .kw_do, .spell = "do", .keyword = true, .body_start = true, .compat_only = true },
    .{ .kind = .kw_else, .spell = "else", .keyword = true },
    .{ .kind = .kw_elseif, .spell = "elseif", .keyword = true, .compat_only = true, .demands_operand = true },
    .{ .kind = .kw_end, .spell = "end", .keyword = true, .compat_only = true },
    .{ .kind = .kw_false, .spell = "false", .keyword = true, .begin_expr = true, .body_start = true, .pattern = true, .compat_only = true },
    .{ .kind = .kw_for, .spell = "for", .keyword = true, .body_start = true },
    .{ .kind = .kw_function, .spell = "function", .keyword = true, .begin_expr = true, .body_start = true, .compat_only = true },
    .{ .kind = .kw_fun, .spell = "fun", .keyword = true, .begin_expr = true, .body_start = true, .compat_only = true },
    .{ .kind = .kw_global, .spell = "global", .keyword = true },
    .{ .kind = .kw_goto, .spell = "goto", .keyword = true },
    .{ .kind = .kw_if, .spell = "if", .keyword = true, .begin_expr = true, .body_start = true, .demands_operand = true },
    .{ .kind = .kw_in, .spell = "in", .keyword = true, .precedence = 6, .assoc = .nonassoc, .relation = .contains, .infix = true, .demands_operand = true },
    .{ .kind = .kw_local, .spell = "local", .keyword = true, .compat_only = true },
    .{ .kind = .kw_nil, .spell = "nil", .keyword = true, .begin_expr = true, .body_start = true, .pattern = true, .compat_only = true },
    .{ .kind = .kw_not, .spell = "not", .keyword = true, .begin_expr = true, .prefix = true, .body_start = true, .precedence = 9, .unary = .not, .demands_operand = true },
    .{ .kind = .kw_or, .spell = "or", .keyword = true, .precedence = 2, .assoc = .left, .compat_only = true, .relation = .@"or", .infix = true, .demands_operand = true },
    .{ .kind = .kw_repeat, .spell = "repeat", .keyword = true },
    .{ .kind = .kw_return, .spell = "return", .keyword = true, .body_start = true, .demands_operand = true },
    .{ .kind = .kw_then, .spell = "then", .keyword = true, .compat_only = true },
    .{ .kind = .kw_true, .spell = "true", .keyword = true, .begin_expr = true, .body_start = true, .pattern = true, .compat_only = true },
    .{ .kind = .kw_until, .spell = "until", .keyword = true, .demands_operand = true },
    .{ .kind = .kw_while, .spell = "while", .keyword = true, .body_start = true, .demands_operand = true },
    .{ .kind = .kw_const, .spell = "const", .keyword = true, .compat_only = true },
    .{ .kind = .kw_enum, .spell = "enum", .keyword = true },
    .{ .kind = .kw_i8, .spell = "i8", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_i16, .spell = "i16", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_i32, .spell = "i32", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_i64, .spell = "i64", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_u8, .spell = "u8", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_u16, .spell = "u16", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_u32, .spell = "u32", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_u64, .spell = "u64", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_f32, .spell = "f32", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_f64, .spell = "f64", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_bool, .spell = "bool", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_void, .spell = "void", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_str, .spell = "str", .keyword = true, .begin_expr = true, .descriptor = true },
    .{ .kind = .kw_match, .spell = "match", .keyword = true, .begin_expr = true, .body_start = true },
    .{ .kind = .kw_try, .spell = "try", .keyword = true },
    .{ .kind = .kw_catch, .spell = "catch", .keyword = true },
    .{ .kind = .kw_defer, .spell = "defer", .keyword = true },
    .{ .kind = .kw_async, .spell = "async", .keyword = true },
    .{ .kind = .kw_await, .spell = "await", .keyword = true, .begin_expr = true, .prefix = true },
    .{ .kind = .kw_concept, .spell = "concept", .keyword = true },
    .{ .kind = .kw_alias, .spell = "alias", .keyword = true },
    .{ .kind = .kw_private, .spell = "private", .keyword = true },
    .{ .kind = .kw_extends, .spell = "extends", .keyword = true },
    .{ .kind = .kw_macro, .spell = "macro", .keyword = true },
    .{ .kind = .kw_comptime, .spell = "comptime", .keyword = true, .begin_expr = true, .prefix = true, .unary = .compile },
    .{ .kind = .kw_by, .spell = "by", .keyword = true, .demands_operand = true },
    .{ .kind = .kw_let, .spell = "let", .keyword = true, .compat_only = true },
    .{ .kind = .lparen, .spell = "(", .begin_expr = true, .prefix = true, .body_start = true, .demands_operand = true },
    .{ .kind = .rparen, .spell = ")" },
    .{ .kind = .lbracket, .spell = "[", .projection = true, .pattern = true, .demands_operand = true },
    .{ .kind = .rbracket, .spell = "]" },
    .{ .kind = .lbrace, .spell = "{", .begin_expr = true, .body_start = true, .pattern = true },
    .{ .kind = .rbrace, .spell = "}" },
    .{ .kind = .plus, .spell = "+", .precedence = 17, .assoc = .left, .relation = .add, .infix = true, .demands_operand = true },
    .{ .kind = .minus, .spell = "-", .begin_expr = true, .prefix = true, .body_start = true, .pattern = true, .precedence = 17, .assoc = .left, .relation = .sub, .unary = .neg, .infix = true, .demands_operand = true, .opens_line = true },
    .{ .kind = .star, .spell = "*", .precedence = 19, .assoc = .left, .relation = .mul, .infix = true, .demands_operand = true },
    .{ .kind = .slash, .spell = "/", .precedence = 19, .assoc = .left, .relation = .div, .infix = true, .demands_operand = true },
    .{ .kind = .percent, .spell = "%", .precedence = 19, .assoc = .left, .relation = .mod, .infix = true, .demands_operand = true },
    .{ .kind = .caret, .spell = "^", .precedence = 23, .assoc = .right, .relation = .pow, .infix = true, .demands_operand = true },
    .{ .kind = .hash, .spell = "#", .begin_expr = true, .prefix = true, .body_start = true, .compat_only = true, .unary = .len, .demands_operand = true },
    .{ .kind = .amp, .spell = "&", .precedence = 11, .assoc = .left, .relation = .band, .infix = true, .glue = true, .demands_operand = true },
    .{ .kind = .pipe, .spell = "|", .begin_expr = true, .body_start = true, .precedence = 7, .assoc = .left, .relation = .bor, .infix = true, .glue = true, .demands_operand = true },
    .{ .kind = .lt, .spell = "<", .precedence = 6, .assoc = .nonassoc, .relation = .lt, .infix = true, .demands_operand = true },
    .{ .kind = .gt, .spell = ">", .precedence = 6, .assoc = .nonassoc, .relation = .gt, .infix = true, .demands_operand = true },
    .{ .kind = .assign, .spell = "=", .precedence = 1, .assoc = .right, .demands_operand = true },
    .{ .kind = .tilde, .spell = "~", .begin_expr = true, .prefix = true, .precedence = 9, .assoc = .left, .relation = .bxor, .unary = .bnot, .infix = true, .glue = true, .demands_operand = true, .opens_line = true },
    .{ .kind = .semi, .spell = ";" },
    .{ .kind = .colon, .spell = ":", .begin_expr = true, .parameter = true, .projection = true, .demands_operand = true },
    .{ .kind = .comma, .spell = ",", .demands_operand = true },
    .{ .kind = .dot, .spell = ".", .begin_expr = true, .postfix = true, .projection = true, .precedence = 10, .demands_operand = true },
    .{ .kind = .at, .spell = "@", .begin_expr = true, .body_start = true, .precedence = 19, .assoc = .left, .relation = .matmul, .infix = true, .demands_operand = true, .opens_line = true },
    .{ .kind = .question, .spell = "?" },
    .{ .kind = .bang, .spell = "!", .begin_expr = true, .prefix = true, .precedence = 9, .unary = .not, .demands_operand = true },
    .{ .kind = .backtick, .spell = "`", .compat_only = true },
    .{ .kind = .concat, .spell = "..", .precedence = 16, .assoc = .right, .compat_only = true, .relation = .concat, .infix = true, .demands_operand = true },
    .{ .kind = .dots, .spell = "...", .begin_expr = true, .pattern = true },
    .{ .kind = .hash_hash, .spell = "##", .begin_expr = true, .prefix = true, .compat_only = true, .unary = .compile, .demands_operand = true },
    .{ .kind = .eq, .spell = "==", .precedence = 6, .assoc = .nonassoc, .relation = .eq, .infix = true, .demands_operand = true },
    .{ .kind = .neq, .spell = "!=", .precedence = 6, .assoc = .nonassoc, .relation = .neq, .infix = true, .demands_operand = true },
    .{ .kind = .leq, .spell = "<=", .precedence = 6, .assoc = .nonassoc, .relation = .leq, .infix = true, .demands_operand = true },
    .{ .kind = .geq, .spell = ">=", .precedence = 6, .assoc = .nonassoc, .relation = .geq, .infix = true, .demands_operand = true },
    .{ .kind = .lshift, .spell = "<<", .precedence = 13, .assoc = .left, .relation = .lshift, .infix = true, .glue = true, .demands_operand = true },
    .{ .kind = .rshift, .spell = ">>", .precedence = 13, .assoc = .left, .relation = .rshift, .infix = true, .glue = true, .demands_operand = true },
    .{ .kind = .idiv, .spell = "//", .precedence = 19, .assoc = .left, .relation = .idiv, .infix = true, .demands_operand = true },
    .{ .kind = .dcolon, .spell = "::" },
    .{ .kind = .arrow, .spell = "->", .demands_operand = true },
    .{ .kind = .pipe_gt, .spell = "|>", .precedence = 1, .assoc = .left, .relation = .pipeline, .infix = true, .demands_operand = true },
    .{ .kind = .fat_arrow, .spell = "=>", .demands_operand = true },
    .{ .kind = .plus_assign, .spell = "+=", .precedence = 1, .assoc = .right, .relation = .add, .update = true, .demands_operand = true },
    .{ .kind = .minus_assign, .spell = "-=", .precedence = 1, .assoc = .right, .relation = .sub, .update = true, .demands_operand = true },
    .{ .kind = .star_assign, .spell = "*=", .precedence = 1, .assoc = .right, .relation = .mul, .update = true, .demands_operand = true },
    .{ .kind = .slash_assign, .spell = "/=", .precedence = 1, .assoc = .right, .relation = .div, .update = true, .demands_operand = true },
    .{ .kind = .percent_assign, .spell = "%=", .precedence = 1, .assoc = .right, .relation = .mod, .update = true, .demands_operand = true },
    .{ .kind = .caret_assign, .spell = "^=", .precedence = 1, .assoc = .right, .relation = .pow, .update = true, .demands_operand = true },
    .{ .kind = .text_lit, .spell = "text", .begin_expr = true, .literal_kind = true, .body_start = true, .quoted = true, .pattern = true },
    .{ .kind = .bytes_lit, .spell = "bytes", .begin_expr = true, .literal_kind = true, .body_start = true, .quoted = true, .pattern = true },
    .{ .kind = .compat_text_lit, .spell = "compat_text", .begin_expr = true, .literal_kind = true, .body_start = true, .quoted = true, .pattern = true, .compat_only = true },
    .{ .kind = .compat_long_text_lit, .spell = "compat_long_text", .begin_expr = true, .literal_kind = true, .body_start = true, .quoted = true, .pattern = true, .compat_only = true },
    .{ .kind = .eof, .spell = "<eof>" },
    .{ .kind = .shebang, .spell = "#!" },
    .{ .kind = .comment, .spell = "#" },
    .{ .kind = .compat_comment, .spell = "--", .compat_only = true },
    .{ .kind = .compat_long_comment, .spell = "--[[", .compat_only = true },
};
