/* Generated by duo compiler — do not edit */
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <time.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
static inline char* duo_str_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* out = (char*)malloc(la + lb + 1);
    if (!out) return (char*)a;
    memcpy(out, a, la); memcpy(out + la, b, lb); out[la + lb] = '\0';
    return out;
}
static inline char* duo_str_from_i64(int64_t v) {
    char b[32];
    int n = snprintf(b, sizeof(b), "%lld", (long long)v);
    char* out = (char*)malloc((size_t)n + 1);
    if (!out) return (char*)"";
    memcpy(out, b, (size_t)n + 1);
    return out;
}
static inline char* duo_str_from_f64(double v) {
    char b[48];
    int n = snprintf(b, sizeof(b), "%.17g", v);
    char* out = (char*)malloc((size_t)n + 1);
    if (!out) return (char*)"";
    memcpy(out, b, (size_t)n + 1);
    return out;
}
static inline char* duo_str_from_bool(int v) { return (char*)(v ? "true" : "false"); }
static inline char* duo_str_rep(const char* s, int64_t n) {
    if (n <= 0) { char* e = (char*)malloc(1); if (e) e[0] = '\0'; return e; }
    size_t len = strlen(s);
    size_t total = len * (size_t)n;
    char* out = (char*)malloc(total + 1);
    if (!out) return (char*)s;
    char* p = out;
    for (int64_t i = 0; i < n; ++i) { memcpy(p, s, len); p += len; }
    *p = '\0';
    return out;
}
static inline char* duo_str_char_cstr(int64_t code) {
    char* out = (char*)malloc(2);
    if (!out) return (char*)"";
    out[0] = (char)(unsigned char)(code & 0xFF); out[1] = '\0';
    return out;
}
static inline char* duo_str_sub_cstr(const char* str, int64_t start, int64_t end) {
    if (!str) str = "";
    int64_t len = (int64_t)strlen(str);
    if (start < 0) start = len + start + 1;
    if (end < 0) end = len + end + 1;
    if (start < 1) start = 1;
    if (end > len) end = len;
    if (start > end || start > len || end < 1) {
        char* e = (char*)malloc(1); if (e) e[0] = '\0'; return e;
    }
    int64_t sublen = end - start + 1;
    char* out = (char*)malloc((size_t)sublen + 1);
    if (!out) return (char*)str;
    memcpy(out, str + start - 1, (size_t)sublen); out[sublen] = '\0';
    return out;
}
static inline char* duo_str_lower_cstr(const char* s) {
    if (!s) s = "";
    size_t len = strlen(s);
    char* res = (char*)malloc(len + 1);
    if (!res) return (char*)s;
    for (size_t i = 0; i < len; i++) res[i] = (char)tolower((unsigned char)s[i]);
    res[len] = '\0'; return res;
}
static inline char* duo_str_upper_cstr(const char* s) {
    if (!s) s = "";
    size_t len = strlen(s);
    char* res = (char*)malloc(len + 1);
    if (!res) return (char*)s;
    for (size_t i = 0; i < len; i++) res[i] = (char)toupper((unsigned char)s[i]);
    res[len] = '\0'; return res;
}
static inline char* duo_str_reverse_cstr(const char* s) {
    if (!s) s = "";
    size_t len = strlen(s);
    char* res = (char*)malloc(len + 1);
    if (!res) return (char*)s;
    for (size_t i = 0; i < len; i++) res[i] = s[len - 1 - i];
    res[len] = '\0'; return res;
}
static inline char* duo_str_trim_cstr(const char* s) {
    if (!s) s = "";
    const char* b = s;
    while (*b && isspace((unsigned char)*b)) b++;
    const char* e = b + strlen(b);
    while (e > b && isspace((unsigned char)e[-1])) e--;
    size_t len = (size_t)(e - b);
    char* res = (char*)malloc(len + 1);
    if (!res) return (char*)s;
    memcpy(res, b, len); res[len] = '\0'; return res;
}
static inline __attribute__((noreturn)) void duo_fatal(const char* msg) {
    fprintf(stderr, "%s\n", msg);
    abort();
}
static inline int64_t duo_str_to_i64(const char* s) {
    if (!s) duo_fatal("to(i64): no string");
    const char* p = s;
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    char* endp = NULL;
    errno = 0;
    long long v = strtoll(p, &endp, 10);
    if (endp == p) duo_fatal("to(i64): not a number");
    while (*endp == ' ' || *endp == '\t' || *endp == '\n' || *endp == '\r') endp++;
    if (*endp != '\0') duo_fatal("to(i64): trailing text after number");
    if (errno == ERANGE) duo_fatal("to(i64): out of range");
    return (int64_t)v;
}
static inline char* duo_io_read_stdin(void) {
    size_t cap = 65536, len = 0;
    char* buf = (char*)malloc(cap);
    if (!buf) duo_fatal("read: out of memory");
    for (;;) {
        if (len + 4097 > cap) {
            cap *= 2;
            char* next = (char*)realloc(buf, cap);
            if (!next) { free(buf); duo_fatal("read: out of memory"); }
            buf = next;
        }
        size_t got = fread(buf + len, 1, 4096, stdin);
        len += got;
        if (got < 4096) break;
    }
    buf[len] = '\0';
    return buf;
}
static inline char* duo_io_read_path(const char* path) {
    if (path == NULL || path[0] == '\0') return duo_io_read_stdin();
    FILE* f = fopen(path, "rb");
    if (!f) duo_fatal("read: cannot open path");
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); duo_fatal("read: cannot size path"); }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); duo_fatal("read: cannot size path"); }
    rewind(f);
    char* buf = (char*)malloc((size_t)sz + 1);
    if (!buf) { fclose(f); duo_fatal("read: out of memory"); }
    size_t got = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    buf[got] = '\0';
    return buf;
}
/* --- Duo loop-versioning bound helpers --- */
#ifndef DUO_LVB_DEFINED
#define DUO_LVB_DEFINED
#include <stdint.h>
#include <stdbool.h>
/* Largest counter value a `while i < e` / `i <= e` loop can reach, for a    */
/* native integer bound. INT64_MIN means "no usable bound" and declines.     */
static inline int64_t duo_dt_hi_int(int64_t e, bool strict) {
    if (!strict) return e;
    return e == INT64_MIN ? INT64_MIN : e - 1;
}
/* The same, for the boxed bound the hoisted `while` compares as a double.   */
/* Outside [0, 1e15] this declines: below 2^53 every int64 converts to double */
/* exactly, so within that window `(double)i <= d` really does imply         */
/* `i <= (int64_t)d`. NaN takes the same exit as a negative bound.           */
static inline int64_t duo_dt_hi_num(bool ok, double d, bool strict) {
    int64_t t;
    if (!ok || !(d >= 0.0) || d > 1e15) return INT64_MIN;
    t = (int64_t)d;
    if (strict && (double)t == d) t -= 1;
    return t;
}
#endif

typedef struct {
    const char* file;
    int64_t line;
    int64_t col;
} duo_rec_ddce63158070fd68;

typedef duo_rec_ddce63158070fd68 duo_loc;
typedef struct {
    int64_t kind;
    duo_rec_ddce63158070fd68 loc;
    const char* text;
    int64_t off;
    int64_t len;
    int64_t int_val;
    int64_t int_class;
    double float_val;
} duo_rec_735fa21981531a8e;

typedef duo_rec_735fa21981531a8e duo_token;
typedef struct {
    const char* src;
    int64_t extent;
    int64_t pos;
    int64_t start;
    int64_t line;
    int64_t col;
    const char* file;
    int64_t family;
    bool has_peeked;
    duo_rec_735fa21981531a8e peeked_token;
    bool has_error;
    duo_rec_ddce63158070fd68 error_loc;
    int64_t error_code;
    int64_t stmt_col;
} duo_rec_ae78087612f938ba;

typedef duo_rec_ae78087612f938ba duo_lexer;
typedef struct {
    int64_t pos;
    int64_t start;
    int64_t line;
    int64_t col;
    bool has_peeked;
    duo_rec_735fa21981531a8e peeked_token;
} duo_rec_8126e0d62b0fd79;

typedef duo_rec_8126e0d62b0fd79 duo_state;



__attribute__((visibility("default"))) duo_rec_ae78087612f938ba new(const char* src, const char* file, int64_t family);
__attribute__((visibility("default"))) duo_rec_ddce63158070fd68 cur_loc(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) int64_t peek_char(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) int64_t peek_char2(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) void adv(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) bool is_digit(int64_t c);
__attribute__((visibility("default"))) bool is_alpha(int64_t c);
__attribute__((visibility("default"))) bool is_alnum(int64_t c);
__attribute__((visibility("default"))) bool is_hex(int64_t c);
__attribute__((visibility("default"))) bool word(duo_rec_ae78087612f938ba *self, int64_t start, int64_t n, const char* pattern);
__attribute__((visibility("default"))) int64_t lookup(duo_rec_ae78087612f938ba *self, int64_t start, int64_t stop);
__attribute__((visibility("default"))) int64_t classify_quote(int64_t family, int64_t quote);
__attribute__((visibility("default"))) int64_t long_bracket_level(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) void _fail(duo_rec_ae78087612f938ba *self, int64_t code);
__attribute__((visibility("default"))) void skip_long(duo_rec_ae78087612f938ba *self, int64_t level);
__attribute__((visibility("default"))) void skip_ws(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) void read_long_str(duo_rec_ae78087612f938ba *self, int64_t level);
__attribute__((visibility("default"))) void read_str(duo_rec_ae78087612f938ba *self, int64_t quote);
__attribute__((visibility("default"))) duo_rec_735fa21981531a8e _spanfull(int64_t kind, duo_rec_ddce63158070fd68 *loc, const char* text, int64_t off, int64_t len, int64_t integer, int64_t intclass, double decimal);
__attribute__((visibility("default"))) duo_rec_735fa21981531a8e _span(int64_t kind, duo_rec_ddce63158070fd68 *loc, const char* text, int64_t off, int64_t len, int64_t integer, double decimal);
__attribute__((visibility("default"))) int64_t _decimal_class(duo_rec_ae78087612f938ba *self, int64_t start, int64_t stop);
__attribute__((visibility("default"))) int64_t _int_of(duo_rec_ae78087612f938ba *self, int64_t start, int64_t stop);
__attribute__((visibility("default"))) duo_rec_735fa21981531a8e read_num(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) duo_rec_735fa21981531a8e next_tok(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) duo_rec_735fa21981531a8e next(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) duo_rec_735fa21981531a8e peek(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) duo_rec_8126e0d62b0fd79 save_state(duo_rec_ae78087612f938ba *self);
__attribute__((visibility("default"))) void restore_state(duo_rec_ae78087612f938ba *self, duo_rec_8126e0d62b0fd79 *state);
__attribute__((visibility("default"))) int64_t duo_lexer_error_line(const char* src, const char* file, int64_t family);
__attribute__((visibility("default"))) int64_t duo_lexer_tokenize_full(const char* src, const char* file, int64_t family, int64_t out, int64_t cap, int64_t txt, int64_t txtcap);
__attribute__((visibility("default"))) int64_t duo_lexer_tokenize_all(const char* src, const char* file, int64_t family, int64_t out, int64_t cap);
__attribute__((visibility("default"))) int64_t duo_lexer_step(const char* src, const char* file, int64_t family, int64_t pos);
__attribute__((visibility("default"))) uint64_t duo_lexer_text_fingerprint(const char* src, const char* file, int64_t family);
__attribute__((visibility("default"))) uint64_t duo_lexer_kind_fingerprint(const char* src, const char* file, int64_t family);
__attribute__((visibility("default"))) int64_t sourceformcount(void);
__attribute__((visibility("default"))) const char* sourceformlaw(int64_t i);
__attribute__((visibility("default"))) const char* sourceformsuffix(int64_t i);
__attribute__((visibility("default"))) bool sourceformcanonical(int64_t i);
__attribute__((visibility("default"))) int64_t sourceentrycount(void);
__attribute__((visibility("default"))) const char* sourceentryrole(int64_t i);
__attribute__((visibility("default"))) const char* sourceentrypattern(int64_t i);
__attribute__((visibility("default"))) bool sourceequal(const char* left, const char* right);
__attribute__((visibility("default"))) bool sourcerangeequal(const char* text, int64_t start, const char* pattern);
__attribute__((visibility("default"))) bool sourceends(const char* text, const char* suffix);
__attribute__((visibility("default"))) bool sourcepathmatches(const char* path, const char* pattern);
__attribute__((visibility("default"))) const char* sourcepathrole(const char* path);
__attribute__((visibility("default"))) const char* sourcepathformlaw(const char* path);
__attribute__((visibility("default"))) const char* sourcepathformprovenance(const char* path);
__attribute__((visibility("default"))) const char* sourcefactlaw(const char* path, const char* role);
__attribute__((visibility("default"))) const char* sourcefactprovenance(const char* path, const char* role);
__attribute__((visibility("default"))) int64_t recordslots(void);
__attribute__((visibility("default"))) int64_t fieldkind(void);
__attribute__((visibility("default"))) int64_t fieldline(void);
__attribute__((visibility("default"))) int64_t fieldcol(void);
__attribute__((visibility("default"))) int64_t fieldint(void);
__attribute__((visibility("default"))) int64_t fieldoff(void);
__attribute__((visibility("default"))) int64_t fieldlen(void);
__attribute__((visibility("default"))) int64_t fieldfloat(void);
__attribute__((visibility("default"))) int64_t _fieldintclass(void);
__attribute__((visibility("default"))) int64_t rejectioncount(void);
__attribute__((visibility("default"))) int64_t rejectioncode(int64_t i);
__attribute__((visibility("default"))) const char* rejectionname(int64_t code);
__attribute__((visibility("default"))) int64_t kindcount(void);
__attribute__((visibility("default"))) const char* kindname(int64_t i);
__attribute__((visibility("default"))) duo_rec_ae78087612f938ba new(const char* src, const char* file, int64_t family) {
    duo_rec_ddce63158070fd68 dummy_loc = {
        .file = "",
        .line = 0,
        .col = 0
    };
    duo_rec_735fa21981531a8e dummy_tok = {
        .kind = 0,
        .loc = dummy_loc,
        .text = "",
        .off = 0,
        .len = 0,
        .int_val = 0,
        .int_class = 0,
        .float_val = 0e0
    };
    return (duo_rec_ae78087612f938ba){
        .src = src,
        .extent = ((int64_t)strlen(src)),
        .pos = 1,
        .start = 1,
        .line = 1,
        .col = 1,
        .file = file,
        .family = family,
        .has_peeked = false,
        .peeked_token = dummy_tok,
        .has_error = false,
        .error_loc = dummy_loc,
        .error_code = 0,
        .stmt_col = 0
    };
}

__attribute__((visibility("default"))) duo_rec_ddce63158070fd68 cur_loc(duo_rec_ae78087612f938ba *self) {
    return (duo_rec_ddce63158070fd68){
        .file = self->file,
        .line = self->line,
        .col = self->col
    };
}

__attribute__((visibility("default"))) int64_t peek_char(duo_rec_ae78087612f938ba *self) {
    if ((self->pos > self->extent)) {
        return 0;
    }
    return ((int64_t)(unsigned char)(self->src[self->pos - 1]));
}

__attribute__((visibility("default"))) int64_t peek_char2(duo_rec_ae78087612f938ba *self) {
    if (((self->pos + 1) > self->extent)) {
        return 0;
    }
    return ((int64_t)(unsigned char)(self->src[(self->pos + 1) - 1]));
}

__attribute__((visibility("default"))) void adv(duo_rec_ae78087612f938ba *self) {
    if ((self->pos > self->extent)) {
        return;
    }
    int64_t c = ((int64_t)(unsigned char)(self->src[self->pos - 1]));
    self->pos = (self->pos + 1);
    if ((c == 10)) {
        self->line = (self->line + 1);
        self->col = 1;
        self->col;
    } else {
        self->col = (self->col + 1);
        self->col;
    }
}

__attribute__((visibility("default"))) bool is_digit(int64_t c) {
    return ((c >= 48) && (c <= 57));
}

__attribute__((visibility("default"))) bool is_alpha(int64_t c) {
    return (((c >= 65) && (c <= 90)) || ((c >= 97) && (c <= 122)));
}

__attribute__((visibility("default"))) bool is_alnum(int64_t c) {
    return (is_alpha(c) || is_digit(c));
}

__attribute__((visibility("default"))) bool is_hex(int64_t c) {
    return ((is_digit(c) || ((c >= 65) && (c <= 70))) || ((c >= 97) && (c <= 102)));
}

__attribute__((visibility("default"))) bool word(duo_rec_ae78087612f938ba *self, int64_t start, int64_t n, const char* pattern) {
    int64_t i = 1;
    while ((i <= n)) {
        if ((((int64_t)(unsigned char)(self->src[((start + i) - 1) - 1])) != ((int64_t)(unsigned char)(pattern[i - 1])))) {
            return false;
        }
                i = (i + 1);
    }
    return true;
}

__attribute__((visibility("default"))) int64_t lookup(duo_rec_ae78087612f938ba *self, int64_t start, int64_t stop) {
    int64_t n = ((stop - start) + 1);
    if ((n == 2)) {
        if (word(self, start, n, "by")) {
            return 56;
        }
        if (word(self, start, n, "do")) {
            return 7;
        }
        if (word(self, start, n, "i8")) {
            return 31;
        }
        if (word(self, start, n, "if")) {
            return 17;
        }
        if (word(self, start, n, "in")) {
            return 18;
        }
        if (word(self, start, n, "or")) {
            return 22;
        }
        if (word(self, start, n, "u8")) {
            return 35;
        }
    } else if ((n == 3)) {
        if (word(self, start, n, "and")) {
            return 4;
        }
        if (word(self, start, n, "end")) {
            return 10;
        }
        if (word(self, start, n, "f32")) {
            return 39;
        }
        if (word(self, start, n, "f64")) {
            return 40;
        }
        if (word(self, start, n, "for")) {
            return 12;
        }
        if (word(self, start, n, "fun")) {
            return 14;
        }
        if (word(self, start, n, "i16")) {
            return 32;
        }
        if (word(self, start, n, "i32")) {
            return 33;
        }
        if (word(self, start, n, "i64")) {
            return 34;
        }
        if (word(self, start, n, "let")) {
            return 57;
        }
        if (word(self, start, n, "nil")) {
            return 20;
        }
        if (word(self, start, n, "not")) {
            return 21;
        }
        if (word(self, start, n, "str")) {
            return 43;
        }
        if (word(self, start, n, "try")) {
            return 45;
        }
        if (word(self, start, n, "u16")) {
            return 36;
        }
        if (word(self, start, n, "u32")) {
            return 37;
        }
        if (word(self, start, n, "u64")) {
            return 38;
        }
    } else if ((n == 4)) {
        if (word(self, start, n, "bool")) {
            return 41;
        }
        if (word(self, start, n, "else")) {
            return 8;
        }
        if (word(self, start, n, "enum")) {
            return 30;
        }
        if (word(self, start, n, "goto")) {
            return 16;
        }
        if (word(self, start, n, "then")) {
            return 25;
        }
        if (word(self, start, n, "true")) {
            return 26;
        }
        if (word(self, start, n, "void")) {
            return 42;
        }
    } else if ((n == 5)) {
        if (word(self, start, n, "alias")) {
            return 51;
        }
        if (word(self, start, n, "async")) {
            return 48;
        }
        if (word(self, start, n, "await")) {
            return 49;
        }
        if (word(self, start, n, "break")) {
            return 5;
        }
        if (word(self, start, n, "catch")) {
            return 46;
        }
        if (word(self, start, n, "const")) {
            return 29;
        }
        if (word(self, start, n, "defer")) {
            return 47;
        }
        if (word(self, start, n, "false")) {
            return 11;
        }
        if (word(self, start, n, "local")) {
            return 19;
        }
        if (word(self, start, n, "macro")) {
            return 54;
        }
        if (word(self, start, n, "match")) {
            return 44;
        }
        if (word(self, start, n, "until")) {
            return 27;
        }
        if (word(self, start, n, "while")) {
            return 28;
        }
    } else if ((n == 6)) {
        if (word(self, start, n, "elseif")) {
            return 9;
        }
        if (word(self, start, n, "global")) {
            return 15;
        }
        if (word(self, start, n, "repeat")) {
            return 23;
        }
        if (word(self, start, n, "return")) {
            return 24;
        }
    } else if ((n == 7)) {
        if (word(self, start, n, "concept")) {
            return 50;
        }
        if (word(self, start, n, "extends")) {
            return 53;
        }
        if (word(self, start, n, "private")) {
            return 52;
        }
    } else if ((n == 8)) {
        if (word(self, start, n, "comptime")) {
            return 55;
        }
        if (word(self, start, n, "continue")) {
            return 6;
        }
        if (word(self, start, n, "function")) {
            return 13;
        }
    }
    return 0;
}

__attribute__((visibility("default"))) int64_t classify_quote(int64_t family, int64_t quote) {
    if ((quote == 34)) {
        return 105;
    }
    if ((quote == 39)) {
        if ((family == 1)) {
            return 106;
        }
        return 107;
    }
    return 107;
}

__attribute__((visibility("default"))) int64_t long_bracket_level(duo_rec_ae78087612f938ba *self) {
    int64_t i = self->pos;
    if (((i > self->extent) || (((int64_t)(unsigned char)(self->src[i - 1])) != 91))) {
        return (-(1));
    }
        i = (i + 1);
    int64_t lvl = 0;
    while (((i <= self->extent) && (((int64_t)(unsigned char)(self->src[i - 1])) == 61))) {
                lvl = (lvl + 1);
                i = (i + 1);
    }
    if (((i > self->extent) || (((int64_t)(unsigned char)(self->src[i - 1])) != 91))) {
        return (-(1));
    }
    return lvl;
}

__attribute__((visibility("default"))) void _fail(duo_rec_ae78087612f938ba *self, int64_t code) {
    if ((!self->has_error)) {
        self->has_error = true;
        self->error_code = code;
        self->error_loc = cur_loc(self);
    }
    return;
}

__attribute__((visibility("default"))) void skip_long(duo_rec_ae78087612f938ba *self, int64_t level) {
    adv(self);
    int64_t i = 0;
    while ((i < level)) {
        adv(self);
                i = (i + 1);
    }
    adv(self);
    while ((self->pos <= self->extent)) {
        if ((peek_char(self) == 93)) {
            int64_t eq = 0;
            adv(self);
            while ((peek_char(self) == 61)) {
                adv(self);
                                eq = (eq + 1);
            }
            if (((eq == level) && (peek_char(self) == 93))) {
                adv(self);
                return;
            }
        } else {
            adv(self);
        }
    }
    _fail(self, 2);
}

__attribute__((visibility("default"))) void skip_ws(duo_rec_ae78087612f938ba *self) {
    while ((self->pos <= self->extent)) {
        int64_t c = peek_char(self);
        if (((((c == 32) || (c == 9)) || (c == 13)) || (c == 10))) {
            adv(self);
        } else {
            break;
        }
    }
    return;
}

__attribute__((visibility("default"))) void read_long_str(duo_rec_ae78087612f938ba *self, int64_t level) {
    adv(self);
    int64_t i = 0;
    while ((i < level)) {
        adv(self);
                i = (i + 1);
    }
    adv(self);
    if ((peek_char(self) == 10)) {
        adv(self);
    } else if ((peek_char(self) == 13)) {
        adv(self);
        if ((peek_char(self) == 10)) {
            adv(self);
        }
    }
    self->start = self->pos;
    while ((self->pos <= self->extent)) {
        if ((peek_char(self) == 93)) {
            adv(self);
            int64_t eq = 0;
            while ((peek_char(self) == 61)) {
                adv(self);
                                eq = (eq + 1);
            }
            if (((eq == level) && (peek_char(self) == 93))) {
                adv(self);
                return;
            }
        } else {
            adv(self);
        }
    }
    _fail(self, 2);
}

__attribute__((visibility("default"))) void read_str(duo_rec_ae78087612f938ba *self, int64_t quote) {
    adv(self);
    self->start = self->pos;
    while ((self->pos <= self->extent)) {
        int64_t c = peek_char(self);
        if ((c == quote)) {
            adv(self);
            return;
        }
        if (((c == 10) || (c == 13))) {
            _fail(self, 1);
            return;
        }
        if ((c == 92)) {
            adv(self);
            if ((self->pos > self->extent)) {
                _fail(self, 1);
                return;
            }
            int64_t esc = peek_char(self);
            if ((esc == 120)) {
                adv(self);
                if (((self->pos > self->extent) || (!is_hex(peek_char(self))))) {
                    _fail(self, 3);
                    return;
                }
                adv(self);
                if (((self->pos <= self->extent) && is_hex(peek_char(self)))) {
                    adv(self);
                }
            } else if ((esc == 117)) {
                adv(self);
                if ((peek_char(self) != 123)) {
                    _fail(self, 3);
                    return;
                }
                adv(self);
                bool has_digit = false;
                while (((self->pos <= self->extent) && (peek_char(self) != 125))) {
                    if ((!is_hex(peek_char(self)))) {
                        _fail(self, 3);
                        return;
                    }
                                        has_digit = true;
                    adv(self);
                }
                if ((((!has_digit) || (self->pos > self->extent)) || (peek_char(self) != 125))) {
                    _fail(self, 3);
                    return;
                }
                adv(self);
            } else if ((esc == 122)) {
                adv(self);
                while ((self->pos <= self->extent)) {
                    int64_t ws = peek_char(self);
                    if (((((ws == 32) || (ws == 9)) || (ws == 13)) || (ws == 10))) {
                        adv(self);
                    } else {
                        break;
                    }
                }
            } else if ((esc == 13)) {
                adv(self);
                if (((self->pos <= self->extent) && (peek_char(self) == 10))) {
                    adv(self);
                }
            } else {
                adv(self);
            }
        } else {
            adv(self);
        }
    }
    _fail(self, 1);
}

__attribute__((visibility("default"))) duo_rec_735fa21981531a8e _spanfull(int64_t kind, duo_rec_ddce63158070fd68 *loc, const char* text, int64_t off, int64_t len, int64_t integer, int64_t intclass, double decimal) {
    duo_rec_ddce63158070fd68 at = {
        .file = loc->file,
        .line = loc->line,
        .col = loc->col
    };
    return (duo_rec_735fa21981531a8e){
        .kind = kind,
        .loc = at,
        .text = text,
        .off = off,
        .len = len,
        .int_val = integer,
        .int_class = intclass,
        .float_val = decimal
    };
}

__attribute__((visibility("default"))) duo_rec_735fa21981531a8e _span(int64_t kind, duo_rec_ddce63158070fd68 *loc, const char* text, int64_t off, int64_t len, int64_t integer, double decimal) {
    return _spanfull(kind, loc, text, off, len, integer, 0, decimal);
}

__attribute__((visibility("default"))) int64_t _decimal_class(duo_rec_ae78087612f938ba *self, int64_t start, int64_t stop) {
    int64_t i = start;
    while (((i <= stop) && (((int64_t)(unsigned char)(self->src[i - 1])) == 48))) {
                i = (i + 1);
    }
    int64_t digits = ((stop - i) + 1);
    if (((digits <= 0) || (digits < 19))) {
        return 0;
    }
    if ((digits > 20)) {
        return 3;
    }
    const char* lower = "9223372036854775808";
        int64_t boundary_digit = 0;
        int64_t source_digit = 0;
    if ((digits == 19)) {
        int64_t j = 1;
        while ((j <= 19)) {
                        source_digit = ((int64_t)(unsigned char)(self->src[((i + j) - 1) - 1]));
                        boundary_digit = ((int64_t)(unsigned char)(lower[j - 1]));
            if ((source_digit < boundary_digit)) {
                return 0;
            }
            if ((source_digit > boundary_digit)) {
                return 2;
            }
                        j = (j + 1);
        }
        return 1;
    }
    const char* upper = "18446744073709551615";
    int64_t j = 1;
    while ((j <= 20)) {
                source_digit = ((int64_t)(unsigned char)(self->src[((i + j) - 1) - 1]));
                boundary_digit = ((int64_t)(unsigned char)(upper[j - 1]));
        if ((source_digit < boundary_digit)) {
            return 2;
        }
        if ((source_digit > boundary_digit)) {
            return 3;
        }
                j = (j + 1);
    }
    return 2;
}

__attribute__((visibility("default"))) int64_t _int_of(duo_rec_ae78087612f938ba *self, int64_t start, int64_t stop) {
    int64_t n = ((stop - start) + 1);
    if ((((n > 2) && (((int64_t)(unsigned char)(self->src[start - 1])) == 48)) && ((((int64_t)(unsigned char)(self->src[(start + 1) - 1])) == 120) || (((int64_t)(unsigned char)(self->src[(start + 1) - 1])) == 88)))) {
        uint64_t v = ((uint64_t)(0));
        int64_t i = (start + 2);
        while ((i <= stop)) {
            int64_t c = ((int64_t)(unsigned char)(self->src[i - 1]));
            int64_t d = 0;
            if (((c >= 48) && (c <= 57))) {
                                d = (c - 48);
            } else if (((c >= 97) && (c <= 102))) {
                                d = (c - 87);
            } else if (((c >= 65) && (c <= 70))) {
                                d = (c - 55);
            } else {
                return v;
            }
                        v = ((uint64_t)(((v * 16) + d)));
                        i = (i + 1);
        }
        return v;
    }
    uint64_t v = ((uint64_t)(0));
    int64_t i = start;
    while ((i <= stop)) {
        int64_t c = ((int64_t)(unsigned char)(self->src[i - 1]));
        if (((c < 48) || (c > 57))) {
            return v;
        }
                v = ((uint64_t)(((v * 10) + (c - 48))));
                i = (i + 1);
    }
    return v;
}

__attribute__((visibility("default"))) duo_rec_735fa21981531a8e read_num(duo_rec_ae78087612f938ba *self) {
    duo_rec_ddce63158070fd68 l = cur_loc(self);
    int64_t start = self->pos;
    bool is_float = false;
    int64_t c1 = peek_char(self);
    int64_t c2 = peek_char2(self);
    if (((c1 == 48) && ((c2 == 120) || (c2 == 88)))) {
        adv(self);
        adv(self);
        while (is_hex(peek_char(self))) {
            adv(self);
        }
        if ((peek_char(self) == 46)) {
                        is_float = true;
            adv(self);
            while (is_hex(peek_char(self))) {
                adv(self);
            }
        }
        int64_t p = peek_char(self);
        if (((p == 112) || (p == 80))) {
                        is_float = true;
            adv(self);
            int64_t sgn = peek_char(self);
            if (((sgn == 43) || (sgn == 45))) {
                adv(self);
            }
            while (is_digit(peek_char(self))) {
                adv(self);
            }
        }
    } else {
        while (is_digit(peek_char(self))) {
            adv(self);
        }
        if ((peek_char(self) == 46)) {
            int64_t n = peek_char2(self);
            if (is_digit(n)) {
                                is_float = true;
                adv(self);
                while (is_digit(peek_char(self))) {
                    adv(self);
                }
            }
        }
        int64_t e = peek_char(self);
        if (((e == 101) || (e == 69))) {
                        is_float = true;
            adv(self);
            int64_t sgn = peek_char(self);
            if (((sgn == 43) || (sgn == 45))) {
                adv(self);
            }
            while (is_digit(peek_char(self))) {
                adv(self);
            }
        }
    }
    if (is_float) {
        const char* text = duo_str_sub_cstr(self->src, (int64_t)(start), (int64_t)((self->pos - 1)));
        return _span(2, &l, text, (start - 1), (self->pos - start), 0, strtod(text, NULL));
    }
    int64_t class = 0;
    bool is_hex_number = ((c1 == 48) && ((c2 == 120) || (c2 == 88)));
    if ((!is_hex_number)) {
                class = _decimal_class(self, start, (self->pos - 1));
    }
    int64_t integer = 0;
    if ((class != 3)) {
                integer = _int_of(self, start, (self->pos - 1));
    }
    return _spanfull(1, &l, "", (start - 1), (self->pos - start), integer, class, 0e0);
}

__attribute__((visibility("default"))) duo_rec_735fa21981531a8e next_tok(duo_rec_ae78087612f938ba *self) {
        int64_t start = 0;
        duo_rec_ddce63158070fd68 l = {0};
    if ((((self->pos == 1) && (peek_char(self) == 35)) && (peek_char2(self) == 33))) {
                l = cur_loc(self);
                start = self->pos;
        while (((self->pos <= self->extent) && (peek_char(self) != 10))) {
            adv(self);
        }
        return _span(110, &l, "", (start - 1), (self->pos - start), 0, 0e0);
    }
    skip_ws(self);
    self->start = self->pos;
    if ((self->pos > self->extent)) {
        duo_rec_ddce63158070fd68 eof = cur_loc(self);
        return _span(109, &eof, "", (self->pos - 1), 0, 0, 0e0);
    }
        l = cur_loc(self);
    int64_t c = peek_char(self);
    if ((is_digit(c) || ((c == 46) && is_digit(peek_char2(self))))) {
        return read_num(self);
    }
        int64_t p = 0;
    if ((is_alpha(c) || (c == 95))) {
                start = self->pos;
        while ((self->pos <= self->extent)) {
                        p = peek_char(self);
            if ((is_alnum(p) || (p == 95))) {
                adv(self);
            } else {
                break;
            }
        }
        int64_t kind = lookup(self, start, (self->pos - 1));
        if ((kind == 0)) {
                        kind = 0;
        }
        return _span(kind, &l, "", (start - 1), (self->pos - start), 0, 0e0);
    }
    if (((c == 39) || (c == 34))) {
        int64_t lit_kind = classify_quote(self->family, c);
        read_str(self, c);
        if (self->has_error) {
            return _span(lit_kind, &l, "", (self->start - 1), 0, 0, 0e0);
        }
        return _span(lit_kind, &l, "", (self->start - 1), ((self->pos - self->start) - 1), 0, 0e0);
    }
        int64_t lvl = 0;
    if ((c == 91)) {
                lvl = long_bracket_level(self);
        if ((lvl >= 0)) {
            read_long_str(self, lvl);
            if (self->has_error) {
                return _span(108, &l, "", (self->start - 1), 0, lvl, 0e0);
            }
            return _span(108, &l, "", (self->start - 1), (((self->pos - self->start) - 2) - lvl), lvl, 0e0);
        }
    }
    if (((c == 35) && (self->family == 1))) {
                start = self->pos;
        while (((self->pos <= self->extent) && (peek_char(self) != 10))) {
            adv(self);
        }
        return _span(111, &l, "", (start - 1), (self->pos - start), 0, 0e0);
    }
    if (((c == 45) && (peek_char2(self) == 45))) {
                start = self->pos;
        adv(self);
        adv(self);
                lvl = long_bracket_level(self);
        if ((lvl >= 0)) {
            skip_long(self, lvl);
            return _span(113, &l, "", (start - 1), (self->pos - start), 0, 0e0);
        }
        bool is_triple = ((self->pos <= self->extent) && (peek_char(self) == 45));
        if (is_triple) {
            adv(self);
        }
        while (((self->pos <= self->extent) && (peek_char(self) != 10))) {
            adv(self);
        }
        return _span(112, &l, "", (start - 1), (self->pos - start), 0, 0e0);
    }
    adv(self);
        p = self->pos;
    if ((c == 43)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(99, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(64, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 42)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(101, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(66, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 37)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(103, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(68, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 94)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(104, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(69, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 35)) {
        if ((peek_char(self) == 35)) {
            adv(self);
            return _span(87, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(70, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 38)) {
        return _span(71, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 124)) {
        if (((self->pos <= self->extent) && (((int64_t)(unsigned char)(self->src[self->pos - 1])) == 62))) {
            self->pos = (self->pos + 1);
            return _span(97, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(72, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 40)) {
        return _span(58, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 41)) {
        return _span(59, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 91)) {
        return _span(60, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 93)) {
        return _span(61, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 123)) {
        return _span(62, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 125)) {
        return _span(63, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 59)) {
        return _span(77, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 44)) {
        return _span(79, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 45)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(100, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        if ((peek_char(self) == 62)) {
            adv(self);
            return _span(96, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(65, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 47)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(102, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        if ((peek_char(self) == 47)) {
            adv(self);
            return _span(94, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(67, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 46)) {
        if ((peek_char(self) == 46)) {
            adv(self);
            if ((peek_char(self) == 46)) {
                adv(self);
                return _span(86, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
            }
            return _span(85, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(80, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 61)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(88, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        if ((peek_char(self) == 62)) {
            adv(self);
            return _span(98, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(75, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 126)) {
        return _span(76, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 60)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(90, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        if ((peek_char(self) == 60)) {
            adv(self);
            return _span(92, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(73, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 62)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(91, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        if ((peek_char(self) == 62)) {
            adv(self);
            return _span(93, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(74, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 58)) {
        if ((peek_char(self) == 58)) {
            adv(self);
            return _span(95, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(78, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 64)) {
        return _span(81, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 63)) {
        return _span(82, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 33)) {
        if ((peek_char(self) == 61)) {
            adv(self);
            return _span(89, &l, "", (p - 2), ((self->pos - p) + 1), 0, 0e0);
        }
        return _span(83, &l, "", (p - 2), 1, 0, 0e0);
    } else if ((c == 96)) {
        if ((self->family == 1)) {
            _fail(self, 4);
            return _span(109, &l, "", (p - 2), 0, 0, 0e0);
        }
        return _span(84, &l, "", (p - 2), 1, 0, 0e0);
    } else {
        _fail(self, 4);
        return _span(109, &l, "", (p - 2), 0, 0, 0e0);
    }
}

__attribute__((visibility("default"))) duo_rec_735fa21981531a8e next(duo_rec_ae78087612f938ba *self) {
        duo_rec_735fa21981531a8e tok = {0};
    if (self->has_peeked) {
                tok = self->peeked_token;
        self->has_peeked = false;
        return tok;
    }
        tok = next_tok(self);
    if (((tok.len > 0) && (((int64_t)strlen(tok.text)) == 0))) {
        tok.text = duo_str_sub_cstr(self->src, (int64_t)((tok.off + 1)), (int64_t)((tok.off + tok.len)));
    }
    return tok;
}

__attribute__((visibility("default"))) duo_rec_735fa21981531a8e peek(duo_rec_ae78087612f938ba *self) {
    if ((!self->has_peeked)) {
        self->peeked_token = next(self);
        self->has_peeked = true;
    }
    return self->peeked_token;
}

__attribute__((visibility("default"))) duo_rec_8126e0d62b0fd79 save_state(duo_rec_ae78087612f938ba *self) {
    return (duo_rec_8126e0d62b0fd79){
        .pos = self->pos,
        .start = self->start,
        .line = self->line,
        .col = self->col,
        .has_peeked = self->has_peeked,
        .peeked_token = self->peeked_token
    };
}

__attribute__((visibility("default"))) void restore_state(duo_rec_ae78087612f938ba *self, duo_rec_8126e0d62b0fd79 *state) {
    self->pos = state->pos;
    self->start = state->start;
    self->line = state->line;
    self->col = state->col;
    self->has_peeked = state->has_peeked;
    self->peeked_token = state->peeked_token;
    self->peeked_token;
}

__attribute__((visibility("default"))) int64_t duo_lexer_error_line(const char* src, const char* file, int64_t family) {
    duo_rec_ae78087612f938ba lex = new(src, file, family);
    int64_t n = 0;
    while ((n < 10000000)) {
        duo_rec_735fa21981531a8e tok = next_tok(&lex);
                n = (n + 1);
        if (lex.has_error) {
            return lex.error_loc.line;
        }
        if ((tok.kind == 109)) {
            return 0;
        }
    }
    return 0;
}

__attribute__((visibility("default"))) int64_t duo_lexer_tokenize_full(const char* src, const char* file, int64_t family, int64_t out, int64_t cap, int64_t txt, int64_t txtcap) {
    duo_rec_ae78087612f938ba lex = new(src, file, family);
    int64_t* buf = ((int64_t*)(uintptr_t)(out));
    int64_t n = 0;
    while ((n < cap)) {
        duo_rec_735fa21981531a8e tok = next_tok(&lex);
        *(int64_t*)((uint8_t*)(buf) + (((n * 8) * 8))) = (int64_t)(tok.kind);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 8) + 1) * 8))) = (int64_t)(tok.loc.line);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 8) + 2) * 8))) = (int64_t)(tok.loc.col);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 8) + 3) * 8))) = (int64_t)(tok.int_val);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 8) + 4) * 8))) = (int64_t)(tok.off);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 8) + 5) * 8))) = (int64_t)(tok.len);
        *(double*)((uint8_t*)(buf) + ((((n * 8) + 6) * 8))) = (double)(tok.float_val);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 8) + 7) * 8))) = (int64_t)(tok.int_class);
                n = (n + 1);
        if (lex.has_error) {
            return (-100 - lex.error_code);
        }
        if ((tok.kind == 109)) {
            return n;
        }
    }
    return (-(1));
}

__attribute__((visibility("default"))) int64_t duo_lexer_tokenize_all(const char* src, const char* file, int64_t family, int64_t out, int64_t cap) {
    duo_rec_ae78087612f938ba lex = new(src, file, family);
    int64_t* buf = ((int64_t*)(uintptr_t)(out));
    int64_t n = 0;
    while ((n < cap)) {
        duo_rec_735fa21981531a8e tok = next_tok(&lex);
        *(int64_t*)((uint8_t*)(buf) + (((n * 4) * 8))) = (int64_t)(tok.kind);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 4) + 1) * 8))) = (int64_t)(tok.loc.line);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 4) + 2) * 8))) = (int64_t)(tok.loc.col);
        *(int64_t*)((uint8_t*)(buf) + ((((n * 4) + 3) * 8))) = (int64_t)(tok.int_val);
                n = (n + 1);
        if (lex.has_error) {
            return (-100 - lex.error_code);
        }
        if ((tok.kind == 109)) {
            return n;
        }
    }
    return (-(1));
}

__attribute__((visibility("default"))) int64_t duo_lexer_step(const char* src, const char* file, int64_t family, int64_t pos) {
    duo_rec_ae78087612f938ba lex = new(src, file, family);
    lex.pos = pos;
    duo_rec_735fa21981531a8e tok = next_tok(&lex);
    return ((tok.kind * 1099511627776) + lex.pos);
}

__attribute__((visibility("default"))) uint64_t duo_lexer_text_fingerprint(const char* src, const char* file, int64_t family) {
    duo_rec_ae78087612f938ba lex = new(src, file, family);
    uint64_t h = ((uint64_t)(0));
    while (1) {
        duo_rec_735fa21981531a8e tok = next_tok(&lex);
                h = ((uint64_t)(((h * 31) + tok.len)));
        int64_t bi = 0;
        while ((bi < tok.len)) {
                        h = ((uint64_t)(((h * 31) + ((int64_t)(unsigned char)(src[((tok.off + bi) + 1) - 1])))));
                        bi = (bi + 1);
        }
        if ((tok.kind == 109)) {
            return h;
        }
    }
    return h;
}

__attribute__((visibility("default"))) uint64_t duo_lexer_kind_fingerprint(const char* src, const char* file, int64_t family) {
    duo_rec_ae78087612f938ba lex = new(src, file, family);
    uint64_t h = ((uint64_t)(0));
    while (1) {
        duo_rec_735fa21981531a8e tok = next_tok(&lex);
                h = ((uint64_t)(((h * 31) + tok.kind)));
        if ((tok.kind == 109)) {
            return h;
        }
    }
    return h;
}

__attribute__((visibility("default"))) int64_t sourceformcount(void) {
    return 2;
}

__attribute__((visibility("default"))) const char* sourceformlaw(int64_t i) {
    if ((i == 1)) {
        return "idol";
    }
    if ((i == 2)) {
        return "lua";
    }
    return "";
}

__attribute__((visibility("default"))) const char* sourceformsuffix(int64_t i) {
    if ((i == 1)) {
        return ".id";
    }
    if ((i == 2)) {
        return ".lua";
    }
    return "";
}

__attribute__((visibility("default"))) bool sourceformcanonical(int64_t i) {
    return (i == 1);
}

__attribute__((visibility("default"))) int64_t sourceentrycount(void) {
    return 39;
}

__attribute__((visibility("default"))) const char* sourceentryrole(int64_t i) {
    if (((i >= 1) && (i <= 3))) {
        return "negative";
    }
    if ((((i == 5) || (i == 6)) || (i == 7))) {
        return "generated";
    }
    if ((((i == 9) || (i == 10)) || (i == 27))) {
        return "compatibility";
    }
    if (((i >= 11) && (i <= 26))) {
        return "canonical";
    }
    if (((i >= 1) && (i <= 39))) {
        return "foreign";
    }
    return "";
}

__attribute__((visibility("default"))) const char* sourceentrypattern(int64_t i) {
    if ((i == 1)) {
        return "examples/compile_fail/";
    }
    if ((i == 2)) {
        return "examples/native_differential/unsupported/";
    }
    if ((i == 3)) {
        return "error_test.id";
    }
    if ((i == 4)) {
        return "examples/native_differential/";
    }
    if ((i == 5)) {
        return "lib/token/classify.id";
    }
    if ((i == 6)) {
        return "lib/wasm/opcode_lookup.id";
    }
    if ((i == 7)) {
        return "lib/wasm/ward_mvp_opcodes.id";
    }
    if ((i == 8)) {
        return "examples/wasm/";
    }
    if ((i == 9)) {
        return "examples/lua";
    }
    if ((i == 10)) {
        return "examples/test_lua";
    }
    if ((i == 11)) {
        return "examples/json/";
    }
    if ((i == 12)) {
        return "examples/conversion/";
    }
    if ((i == 13)) {
        return "examples/projection/";
    }
    if ((i == 14)) {
        return "examples/infer/";
    }
    if ((i == 15)) {
        return "examples/demand/";
    }
    if ((i == 16)) {
        return "examples/hash/";
    }
    if ((i == 17)) {
        return "examples/native/";
    }
    if ((i == 18)) {
        return "examples/control/";
    }
    if ((i == 19)) {
        return "examples/nominal/";
    }
    if ((i == 20)) {
        return "examples/layout/";
    }
    if ((i == 21)) {
        return "examples/pack/";
    }
    if ((i == 22)) {
        return "examples/anchor/";
    }
    if ((i == 23)) {
        return "examples/case/";
    }
    if ((i == 24)) {
        return "examples/read/";
    }
    if ((i == 25)) {
        return "examples/boring/";
    }
    if ((i == 26)) {
        return "examples/table/";
    }
    if ((i == 27)) {
        return "examples/luahost/";
    }
    if ((i == 28)) {
        return "examples/parity/";
    }
    if ((i == 29)) {
        return "examples/host/";
    }
    if ((i == 30)) {
        return "examples/world/";
    }
    if ((i == 31)) {
        return "examples/tailslot/";
    }
    if ((i == 32)) {
        return "examples/shc/";
    }
    if ((i == 33)) {
        return "examples/cfloor/";
    }
    if ((i == 34)) {
        return "examples/benchmark.id";
    }
    if ((i == 35)) {
        return "examples/mandelbrot.id";
    }
    if ((i == 36)) {
        return "vendor/";
    }
    if ((i == 37)) {
        return "test.id";
    }
    if ((i == 38)) {
        return "test2.id";
    }
    if ((i == 39)) {
        return "examples/";
    }
    return "";
}

__attribute__((visibility("default"))) bool sourceequal(const char* left, const char* right) {
    int64_t n = ((int64_t)strlen(left));
    if ((n != ((int64_t)strlen(right)))) {
        return false;
    }
    int64_t i = 1;
    while ((i <= n)) {
        if ((((int64_t)(unsigned char)(left[i - 1])) != ((int64_t)(unsigned char)(right[i - 1])))) {
            return false;
        }
                i = (i + 1);
    }
    return true;
}

__attribute__((visibility("default"))) bool sourcerangeequal(const char* text, int64_t start, const char* pattern) {
    int64_t n = ((int64_t)strlen(pattern));
    if (((start < 1) || (((start + n) - 1) > ((int64_t)strlen(text))))) {
        return false;
    }
    int64_t i = 1;
    while ((i <= n)) {
        if ((((int64_t)(unsigned char)(text[((start + i) - 1) - 1])) != ((int64_t)(unsigned char)(pattern[i - 1])))) {
            return false;
        }
                i = (i + 1);
    }
    return true;
}

__attribute__((visibility("default"))) bool sourceends(const char* text, const char* suffix) {
    int64_t n = ((int64_t)strlen(text));
    int64_t m = ((int64_t)strlen(suffix));
    if ((m > n)) {
        return false;
    }
    return sourcerangeequal(text, ((n - m) + 1), suffix);
}

__attribute__((visibility("default"))) bool sourcepathmatches(const char* path, const char* pattern) {
    int64_t n = ((int64_t)strlen(path));
    int64_t m = ((int64_t)strlen(pattern));
    if (sourceequal(path, pattern)) {
        return true;
    }
    if (((n >= m) && sourcerangeequal(path, 1, pattern))) {
        if ((((int64_t)(unsigned char)(pattern[m - 1])) == 47)) {
            return true;
        }
        if (((n > m) && (((int64_t)(unsigned char)(path[(m + 1) - 1])) == 47))) {
            return true;
        }
    }
    if (((n > m) && (((int64_t)(unsigned char)(path[(n - m) - 1])) == 47))) {
        return sourcerangeequal(path, ((n - m) + 1), pattern);
    }
    return false;
}

__attribute__((visibility("default"))) const char* sourcepathrole(const char* path) {
    const char* best = "";
    int64_t bestlen = 0;
    int64_t i = 1;
    while ((i <= sourceentrycount())) {
        const char* pattern = sourceentrypattern(i);
        int64_t n = ((int64_t)strlen(pattern));
        if (((n >= bestlen) && sourcepathmatches(path, pattern))) {
                        best = sourceentryrole(i);
                        bestlen = n;
        }
                i = (i + 1);
    }
    return best;
}

__attribute__((visibility("default"))) const char* sourcepathformlaw(const char* path) {
    int64_t i = 1;
    while ((i <= sourceformcount())) {
        if (sourceends(path, sourceformsuffix(i))) {
            return sourceformlaw(i);
        }
                i = (i + 1);
    }
    return "";
}

__attribute__((visibility("default"))) const char* sourcepathformprovenance(const char* path) {
    int64_t i = 1;
    while ((i <= sourceformcount())) {
        if (sourceends(path, sourceformsuffix(i))) {
            if (sourceformcanonical(i)) {
                return "canonical";
            }
            return "foreign";
        }
                i = (i + 1);
    }
    return "unknown";
}

__attribute__((visibility("default"))) const char* sourcefactlaw(const char* path, const char* role) {
    if ((sourceequal(role, "canonical") || sourceequal(role, "generated"))) {
        return "idol";
    }
    if (sourceequal(role, "compatibility")) {
        return "lua";
    }
    const char* discovered = sourcepathformlaw(path);
    if ((sourceequal(role, "negative") || sourceequal(role, "foreign"))) {
        if (sourceequal(discovered, "lua")) {
            return "lua";
        }
        return "idol";
    }
    return discovered;
}

__attribute__((visibility("default"))) const char* sourcefactprovenance(const char* path, const char* role) {
    if ((sourceequal(role, "canonical") || sourceequal(role, "generated"))) {
        return "canonical";
    }
    if ((sourceequal(role, "compatibility") || sourceequal(role, "foreign"))) {
        return "foreign";
    }
    if (sourceequal(role, "negative")) {
        if (sourceequal(sourcepathformlaw(path), "lua")) {
            return "foreign";
        }
        return "canonical";
    }
    return sourcepathformprovenance(path);
}

__attribute__((visibility("default"))) int64_t recordslots(void) {
    return 8;
}

__attribute__((visibility("default"))) int64_t fieldkind(void) {
    return 0;
}

__attribute__((visibility("default"))) int64_t fieldline(void) {
    return 1;
}

__attribute__((visibility("default"))) int64_t fieldcol(void) {
    return 2;
}

__attribute__((visibility("default"))) int64_t fieldint(void) {
    return 3;
}

__attribute__((visibility("default"))) int64_t fieldoff(void) {
    return 4;
}

__attribute__((visibility("default"))) int64_t fieldlen(void) {
    return 5;
}

__attribute__((visibility("default"))) int64_t fieldfloat(void) {
    return 6;
}

__attribute__((visibility("default"))) int64_t _fieldintclass(void) {
    return 7;
}

__attribute__((visibility("default"))) int64_t rejectioncount(void) {
    return 5;
}

__attribute__((visibility("default"))) int64_t rejectioncode(int64_t i) {
    if ((i == 1)) {
        return (-(101));
    }
    if ((i == 2)) {
        return (-(102));
    }
    if ((i == 3)) {
        return (-(103));
    }
    if ((i == 4)) {
        return (-(104));
    }
    if ((i == 5)) {
        return (-(105));
    }
    return (-(1));
}

__attribute__((visibility("default"))) const char* rejectionname(int64_t code) {
    if ((code == (-(101)))) {
        return "UnterminatedString";
    }
    if ((code == (-(102)))) {
        return "UnterminatedLongString";
    }
    if ((code == (-(103)))) {
        return "InvalidEscape";
    }
    if ((code == (-(104)))) {
        return "UnexpectedChar";
    }
    if ((code == (-(105)))) {
        return "InsufficientIndent";
    }
    return "";
}

__attribute__((visibility("default"))) int64_t kindcount(void) {
    return 114;
}

__attribute__((visibility("default"))) const char* kindname(int64_t i) {
    if ((i == 0)) {
        return "name";
    }
    if ((i == 1)) {
        return "int_lit";
    }
    if ((i == 2)) {
        return "float_lit";
    }
    if ((i == 3)) {
        return "";
    }
    if ((i == 4)) {
        return "and";
    }
    if ((i == 5)) {
        return "break";
    }
    if ((i == 6)) {
        return "continue";
    }
    if ((i == 7)) {
        return "do";
    }
    if ((i == 8)) {
        return "else";
    }
    if ((i == 9)) {
        return "elseif";
    }
    if ((i == 10)) {
        return "end";
    }
    if ((i == 11)) {
        return "false";
    }
    if ((i == 12)) {
        return "for";
    }
    if ((i == 13)) {
        return "function";
    }
    if ((i == 14)) {
        return "fun";
    }
    if ((i == 15)) {
        return "global";
    }
    if ((i == 16)) {
        return "goto";
    }
    if ((i == 17)) {
        return "if";
    }
    if ((i == 18)) {
        return "in";
    }
    if ((i == 19)) {
        return "local";
    }
    if ((i == 20)) {
        return "nil";
    }
    if ((i == 21)) {
        return "not";
    }
    if ((i == 22)) {
        return "or";
    }
    if ((i == 23)) {
        return "repeat";
    }
    if ((i == 24)) {
        return "return";
    }
    if ((i == 25)) {
        return "then";
    }
    if ((i == 26)) {
        return "true";
    }
    if ((i == 27)) {
        return "until";
    }
    if ((i == 28)) {
        return "while";
    }
    if ((i == 29)) {
        return "const";
    }
    if ((i == 30)) {
        return "enum";
    }
    if ((i == 31)) {
        return "i8";
    }
    if ((i == 32)) {
        return "i16";
    }
    if ((i == 33)) {
        return "i32";
    }
    if ((i == 34)) {
        return "i64";
    }
    if ((i == 35)) {
        return "u8";
    }
    if ((i == 36)) {
        return "u16";
    }
    if ((i == 37)) {
        return "u32";
    }
    if ((i == 38)) {
        return "u64";
    }
    if ((i == 39)) {
        return "f32";
    }
    if ((i == 40)) {
        return "f64";
    }
    if ((i == 41)) {
        return "bool";
    }
    if ((i == 42)) {
        return "void";
    }
    if ((i == 43)) {
        return "str";
    }
    if ((i == 44)) {
        return "match";
    }
    if ((i == 45)) {
        return "try";
    }
    if ((i == 46)) {
        return "catch";
    }
    if ((i == 47)) {
        return "defer";
    }
    if ((i == 48)) {
        return "async";
    }
    if ((i == 49)) {
        return "await";
    }
    if ((i == 50)) {
        return "concept";
    }
    if ((i == 51)) {
        return "alias";
    }
    if ((i == 52)) {
        return "private";
    }
    if ((i == 53)) {
        return "extends";
    }
    if ((i == 54)) {
        return "macro";
    }
    if ((i == 55)) {
        return "comptime";
    }
    if ((i == 56)) {
        return "by";
    }
    if ((i == 57)) {
        return "let";
    }
    if ((i == 58)) {
        return "lparen";
    }
    if ((i == 59)) {
        return "rparen";
    }
    if ((i == 60)) {
        return "lbracket";
    }
    if ((i == 61)) {
        return "rbracket";
    }
    if ((i == 62)) {
        return "lbrace";
    }
    if ((i == 63)) {
        return "rbrace";
    }
    if ((i == 64)) {
        return "plus";
    }
    if ((i == 65)) {
        return "minus";
    }
    if ((i == 66)) {
        return "star";
    }
    if ((i == 67)) {
        return "slash";
    }
    if ((i == 68)) {
        return "percent";
    }
    if ((i == 69)) {
        return "caret";
    }
    if ((i == 70)) {
        return "hash";
    }
    if ((i == 71)) {
        return "amp";
    }
    if ((i == 72)) {
        return "pipe";
    }
    if ((i == 73)) {
        return "lt";
    }
    if ((i == 74)) {
        return "gt";
    }
    if ((i == 75)) {
        return "assign";
    }
    if ((i == 76)) {
        return "tilde";
    }
    if ((i == 77)) {
        return "semi";
    }
    if ((i == 78)) {
        return "colon";
    }
    if ((i == 79)) {
        return "comma";
    }
    if ((i == 80)) {
        return "dot";
    }
    if ((i == 81)) {
        return "at";
    }
    if ((i == 82)) {
        return "question";
    }
    if ((i == 83)) {
        return "bang";
    }
    if ((i == 84)) {
        return "backtick";
    }
    if ((i == 85)) {
        return "concat";
    }
    if ((i == 86)) {
        return "dots";
    }
    if ((i == 87)) {
        return "hash_hash";
    }
    if ((i == 88)) {
        return "eq";
    }
    if ((i == 89)) {
        return "neq";
    }
    if ((i == 90)) {
        return "leq";
    }
    if ((i == 91)) {
        return "geq";
    }
    if ((i == 92)) {
        return "lshift";
    }
    if ((i == 93)) {
        return "rshift";
    }
    if ((i == 94)) {
        return "idiv";
    }
    if ((i == 95)) {
        return "dcolon";
    }
    if ((i == 96)) {
        return "arrow";
    }
    if ((i == 97)) {
        return "pipe_gt";
    }
    if ((i == 98)) {
        return "fat_arrow";
    }
    if ((i == 99)) {
        return "plus_assign";
    }
    if ((i == 100)) {
        return "minus_assign";
    }
    if ((i == 101)) {
        return "star_assign";
    }
    if ((i == 102)) {
        return "slash_assign";
    }
    if ((i == 103)) {
        return "percent_assign";
    }
    if ((i == 104)) {
        return "caret_assign";
    }
    if ((i == 105)) {
        return "text_lit";
    }
    if ((i == 106)) {
        return "bytes_lit";
    }
    if ((i == 107)) {
        return "compat_text_lit";
    }
    if ((i == 108)) {
        return "long_text_lit";
    }
    if ((i == 109)) {
        return "eof";
    }
    if ((i == 110)) {
        return "shebang";
    }
    if ((i == 111)) {
        return "comment";
    }
    if ((i == 112)) {
        return "compat_comment";
    }
    if ((i == 113)) {
        return "compat_long_comment";
    }
    return "";
}

__attribute__((constructor)) static void duo_lib_initialize(void) {
}
